/-
  Find theorems whose proof is their own assumed hypothesis.

  Run:
    cd <repo root>
    ~/.elan/bin/lake env ~/.elan/bin/lean proofs/validation/inflation/Inflation.lean

  WHY THIS IS A LEAN METAPROGRAM AND NOT A GREP.  The question is what a proof
  TERM is, and that is only visible after elaboration.  Three separate text
  scans of this same question gave 2, 16 and 3 hits with no overlap in names,
  and one of them reported a word out of a docstring as a theorem.  The
  environment cannot make that mistake: a theorem is a `thmInfo`, its proof is
  an `Expr`, and a field access is a projection whether it was written
  `S.barrier`, `S.1`, or reached through dot notation.

  Writes `proofs/validation/inflation/inflation_results.json`: every hit by
  name, untruncated, stamped with the revision it was measured at.  Read that
  file rather than a commit message.  The 12/354/2 figures quoted for this tool
  were never backed by one and describe a tree 55 commits behind HEAD.
-/
import Calibrator
import Shared.DeclFilter
import Shared.Results

open Lean Elab Meta Command

namespace Inflation

/-- Is `n` declared in a `Calibrator` module (rather than in Mathlib)? -/
def isOurs (n : Name) : Bool := n.getRoot == `Calibrator

/-- Structures declared here that carry at least one `Prop`-valued field. -/
def assumptionCarriers (env : Environment) : MetaM (Array (Name × Array Name)) := do
  let mut out := #[]
  for (n, _ci) in env.constants.toList do
    unless isOurs n do continue
    let some info := getStructureInfo? env n | continue
    let mut props := #[]
    for f in info.fieldNames do
      let some proj := env.find? (n ++ f) | continue
      -- The `isProp` test MUST happen inside the telescope.  Returning the
      -- body out of `forallTelescopeReducing` leaks the fvars it bound, and the
      -- check then runs in a context where they do not exist -- which surfaces
      -- much later as `unknown free variable`, nowhere near the cause.
      let isP ← forallTelescopeReducing proj.type fun _ b => isProp b
      if isP then props := props.push f
    if props.size > 0 then out := out.push (n, props)
  return out

/-- Every constant name appearing in an expression.

    Lean's own `getUsedConstants` rather than a hand-rolled recursion: proof
    terms produced by tactic blocks are large and heavily shared, and an
    uncached structural walk re-visits the same subterms exponentially often.
    The first version of this file did exactly that and did not finish. -/
def constsOf (e : Expr) : NameSet :=
  e.getUsedConstants.foldl (fun s n => s.insert n) NameSet.empty

/-- Was this declaration written by a person, or generated by Lean?

    THIS FILTER IS THE DIFFERENCE BETWEEN A MEASUREMENT AND A NUMBER.  Without
    it both counts are garbage in opposite directions:

      * Pattern 1 reported 332 hits, and almost all of them were Lean's OWN
        projection functions.  `R2DecompositionData.hVarYhat_pos` is a theorem
        whose proof is the projection `hVarYhat_pos` -- necessarily, that is
        what a projection is.  It is not a corpus author claiming a hypothesis
        as a theorem.
      * Pattern 4 reported that 0 of 104 carriers are never constructed, which
        is false.  Every structure gets `S.mk.injEq`, `S.eta` and friends
        generated for it, and each of those mentions `S.mk` -- so scanning all
        constants for the constructor marks every structure as built.

    The definition itself now lives in `Shared.DeclFilter`, shared with the
    detectors under `proofs/validation/invariants/`.  It used to be a private
    copy here, one of three that disagreed; see `CROSSCHECK.md` §4. -/
abbrev userWritten (env : Environment) (n : Name) : Bool := Shared.userWritten env n

/-- Record every carrier whose CONSTRUCTOR appears among these constants.

    Pattern-matches on `.str p "mk"`.  `Name.getString!` PANICS on anonymous and
    numeric names, and the environment is full of both (`_private.…`, macro
    scopes), so calling it on every constant of every proof term brought the
    whole run down with `unreachable code has been reached`. -/
def noteConstructors (carriers : NameSet) (cs : NameSet) (acc : NameSet) : NameSet :=
  cs.fold (init := acc) fun acc c =>
    match c with
    | .str p "mk" => if carriers.contains p then acc.insert p else acc
    | _ => acc

/-- Strip leading lambdas, returning the body. -/
partial def stripLams : Expr → Expr
  | .lam _ _ b _ => stripLams b
  | .mdata _ b => stripLams b
  | e => e

/-- `Module.lean:LINE` for a declaration, from the environment's own ranges. -/
def whereIs (env : Environment) (n : Name) : CoreM String := do
  let mod := match env.getModuleFor? n with
    | some m => m.toString
    | none => "?"
  match ← findDeclarationRanges? n with
  | some r => return s!"{mod}:{r.range.pos.line}"
  | none => return mod

def run : MetaM Unit := do
  let env ← getEnv
  let carriers ← assumptionCarriers env
  let carrierNames : NameSet := carriers.foldl (fun s (n, _) => s.insert n) NameSet.empty
  -- projection constants for Prop fields, e.g. `Calibrator.ChaosSpectroscopy.barrier`
  let mut propProj : NameSet := NameSet.empty
  for (s, fs) in carriers do
    for f in fs do propProj := propProj.insert (s ++ f)

  let mut exactHits : Array (Name × Name) := #[]
  let mut usesHits  : Array (Name × Name) := #[]
  let mut builtInstances : NameSet := NameSet.empty
  let mut nthm := 0

  for (n, ci) in env.constants.toList do
    unless isOurs n do continue
    match ci with
    | .thmInfo ti =>
      unless userWritten env n do continue
      nthm := nthm + 1
      let body := stripLams ti.value
      -- PATTERN 1: the whole proof is a Prop-field projection of an argument.
      let hd := body.getAppFn
      match hd with
      | .const c _ => if propProj.contains c then exactHits := exactHits.push (n, c)
      | _ =>
        match body with
        | .proj s i _ =>
          match getStructureInfo? env s with
          | some info =>
            if i < info.fieldNames.size then
              let f := s ++ info.fieldNames[i]!
              if propProj.contains f then exactHits := exactHits.push (n, f)
          | none => pure ()
        | _ => pure ()
      -- PATTERNS 2/3: the proof MENTIONS such a projection anywhere.
      let cs := constsOf ti.value
      for c in propProj.toList do
        if cs.contains c then
          if !(exactHits.any (fun (a, b) => a == n && b == c)) then
            usesHits := usesHits.push (n, c)
      -- record which carrier structures ever get CONSTRUCTED
      builtInstances := noteConstructors carrierNames cs builtInstances
    | .defnInfo di =>
      unless userWritten env n do continue
      let cs := constsOf di.value
      builtInstances := noteConstructors carrierNames cs builtInstances
    | _ => pure ()

  -- Every loop below builds the console line and the stored JSON entry from the
  -- same values in the same pass.  Not a stylistic choice: a printed total and
  -- a stored list assembled separately can disagree, and a stored list that
  -- disagrees with the console is worse than no stored list at all.
  IO.println s!"theorems examined (Calibrator only): {nthm}"
  IO.println s!"assumption-carrying structures      : {carriers.size}"
  IO.println ""
  IO.println "=== PATTERN 1: the proof IS the hypothesis (exact projection)"
  IO.println s!"    {exactHits.size} theorem(s)"
  let mut exactJson : Array Json := #[]
  for (t, f) in exactHits do
    let loc ← whereIs env t
    let built := builtInstances.contains f.getPrefix
    IO.println s!"  {t}   [{loc}]"
    IO.println s!"      consumes: {f}   [carrier instance built: {built}]"
    exactJson := exactJson.push <| Json.mkObj
      [ ("theorem", toJson t.toString), ("location", toJson loc),
        ("consumes", toJson f.toString), ("carrierInstanceBuilt", toJson built) ]
  IO.println ""
  IO.println "=== PATTERNS 2/3: the proof MENTIONS an assumed field"
  let usedTheorems := usesHits.foldl (fun s (t, _) => s.insert t) NameSet.empty
  IO.println s!"    {usedTheorems.size} distinct theorem(s), {usesHits.size} theorem/field pair(s)"
  let mut usesJson : Array Json := #[]
  for (t, f) in usesHits do
    let loc ← whereIs env t
    IO.println s!"  {t}   [{loc}]  <- {f}"
    usesJson := usesJson.push <| Json.mkObj
      [ ("theorem", toJson t.toString), ("location", toJson loc),
        ("field", toJson f.toString) ]
  IO.println ""
  IO.println "=== PATTERN 4: assumption-carrying structures with NO instance built"
  let mut none_ := 0
  let mut uninhabitedJson : Array Json := #[]
  for (s, fs) in carriers do
    if !builtInstances.contains s then
      none_ := none_ + 1
      let loc ← whereIs env s
      IO.println s!"  {s}   ({fs.size} Prop field(s))  [{loc}]"
      uninhabitedJson := uninhabitedJson.push <| Json.mkObj
        [ ("structure", toJson s.toString), ("location", toJson loc),
          ("propFields", toJson (fs.map (fun f => f.toString))) ]
  IO.println s!"    {none_} of {carriers.size} carriers are never constructed"

  Shared.Results.write "proofs/validation/inflation/inflation_results.json" "Inflation"
    [ ("theoremsExamined", toJson nthm),
      ("assumptionCarryingStructures", toJson carriers.size),
      -- Pattern 1 pushes at most once per theorem, so this size IS a theorem count.
      ("pattern1Count", toJson exactHits.size),
      ("pattern1", Json.arr exactJson),
      -- Patterns 2/3 push once per (theorem, field), so the two differ and both
      -- are stored.  Reporting only the pair count as a theorem count is the
      -- error that turned an unknown number of theorems into the quoted "354".
      ("pattern23DistinctTheorems", toJson usedTheorems.size),
      ("pattern23PairCount", toJson usesHits.size),
      ("pattern23", Json.arr usesJson),
      ("pattern4UninhabitedCount", toJson none_),
      ("pattern4", Json.arr uninhabitedJson) ]

end Inflation

run_cmd Command.liftTermElabM do Inflation.run
