[package]
name = "gnomon-python"
version = "0.1.2"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
name = "_gnomon"
crate-type = ["cdylib"]

[dependencies]
gnomon = { path = "../..", default-features = false, features = ["python"] }
pyo3 = { version = "0.26", features = ["extension-module", "abi3-py39"] }
