[package]
name = "gnomon-python"
version = "0.2.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
name = "_gnomon"
crate-type = ["cdylib"]

[dependencies]
gnomon = { package = "gnomon-pgs", path = "../.." }
infer_sex = "0.1.0"
pyo3 = { version = "0.26", features = ["extension-module", "abi3-py39"] }
