"""Battery 17: ancestry-averaged effects, tight linkage, assortative mating.

Four oracles, none of which is built from the formula it tests:

  localAncestryMisspecification -- the squared prediction error of using ONE
      ancestry-averaged effect in a population that is a mixture of two. The
      oracle is that error, measured over simulated individuals carrying an
      ancestry label, so the definition is compared against the loss it names
      rather than against its own algebra.

  ldTightLinkageDetectionShare -- claims the rho -> 1 limit of
      `ldBandDetectionShare`, which battery 16 verified against quadrature at
      1e-15. Tested by quadrature at rho approaching 1, so the limit is taken on
      the integral rather than on the closed form.

  alleleFreqDivergenceRate -- the per-generation rate at which allele
      frequencies diverge under drift with mutation and migration, measured as
      the growth of the across-replicate frequency variance.

  amInducedLD -- assortative mating induces covariance between unlinked loci.
      The oracle is the covariance measured between two loci in a population
      mated by phenotype over many generations, which is generated by the mating
      process and not by the formula.
"""
import json
import math

import numpy as np
from scipy import integrate

from battery_core import RESULTS, record


def test_ancestry_averaged_effect():
    """ancestrySpecificEffect and the misspecification loss it induces."""
    rng = np.random.default_rng(13001)
    n = 2000000
    cells_eff, cells_mis = [], []
    for alpha, b1, b2 in ((0.3, 1.0, 0.2), (0.5, 0.8, -0.4), (0.8, 0.5, 0.5)):
        anc = rng.random(n) < alpha              # ancestry label
        g = rng.binomial(2, 0.4, n).astype(float)
        # the true effect depends on ancestry; the phenotype is built from it
        beta_true = np.where(anc, b1, b2)
        y = beta_true * g
        bbar = alpha * b1 + (1 - alpha) * b2
        # ancestrySpecificEffect: the population-averaged effect, measured as
        # the least-squares slope of y on g in the pooled sample
        gc = g - g.mean()
        slope = float(gc @ (y - y.mean()) / (gc @ gc))
        cells_eff.append(dict(design="alpha=%.1f b1=%.1f b2=%.1f" % (alpha, b1, b2),
                              lean=bbar, truth=slope,
                              sem=float(np.std(y) / math.sqrt(n))))
        # localAncestryMisspecification: the extra squared error from using the
        # single averaged effect, per unit of genotype second moment
        err = (beta_true - bbar) ** 2
        lean_mis = (alpha * (b1 - bbar) ** 2 + (1 - alpha) * (b2 - bbar) ** 2)
        cells_mis.append(dict(design="alpha=%.1f b1=%.1f b2=%.1f" % (alpha, b1, b2),
                              lean=lean_mis, truth=float(err.mean()),
                              sem=float(err.std() / math.sqrt(n)) + 1e-12))
    record("ancestrySpecificEffect / globalAncestryAveragedEffect",
           "HaplotypeTheory.lean", "alpha*beta1 + (1-alpha)*beta2", cells_eff,
           regime="pooled least-squares slope in a two-ancestry mixture, "
                  "measured over two million individuals")
    record("localAncestryMisspecification", "HaplotypeTheory.lean",
           "alpha*(b1-bbar)^2 + (1-alpha)*(b2-bbar)^2", cells_mis,
           regime="mean squared deviation of the true ancestry-specific effect "
                  "from the single averaged effect, measured directly")


def test_tight_linkage_share():
    """ldTightLinkageDetectionShare as the rho -> 1 limit, taken on the integral."""
    def reciprocal_mass(r, kappa):
        f = lambda t: (1 - 2 * r * math.cos(t) + r ** 2) / (1 + r ** 2)
        val, _ = integrate.quad(f, -math.pi * kappa, math.pi * kappa,
                                limit=400, epsabs=1e-13, epsrel=1e-13)
        return val / (2 * math.pi)
    cells = []
    for kappa in (0.1, 0.3, 0.6, 0.9):
        lean = kappa - math.sin(math.pi * kappa) / math.pi
        truth = reciprocal_mass(0.999999, kappa)
        cells.append(dict(design="kappa=%.1f" % kappa, lean=lean, truth=truth,
                          sem=max(abs(truth) * 1e-7, 1e-12)))
    record("ldTightLinkageDetectionShare", "MetricSpecificPortability.lean",
           "kappa - sin(pi*kappa)/pi", cells,
           regime="reciprocal-symbol mass at rho -> 1 by quadrature; the limit "
                  "is taken on the integral, not on the closed form")


def test_allele_freq_divergence_rate():
    """alleleFreqDivergenceRate: growth of across-replicate frequency variance."""
    rng = np.random.default_rng(13101)
    cells = []
    for Ne, mu, m in ((200, 0.0, 0.0), (200, 1e-3, 0.0), (200, 0.0, 1e-3)):
        n_loci, reps = 3000, 600
        p0 = 0.5
        two_n = int(2 * Ne)
        p = np.full((reps, n_loci), p0)
        rate = mu + m
        # one generation from a common start: the variance introduced is
        # p0(1-p0)/(2Ne) before any homogenising force acts
        p1 = rng.binomial(two_n, p) / two_n
        if rate > 0:
            p1 = (1 - rate) * p1 + rate * p0
        var1 = float(p1.var())
        theta, bigM = 4 * Ne * mu, 4 * Ne * m
        lean = 1 / (2 * Ne * (1 + theta + bigM))
        # the definition is a RATE per unit p(1-p); normalise the measurement
        truth = var1 / (p0 * (1 - p0))
        sem = truth * math.sqrt(2.0 / (reps * n_loci))
        cells.append(dict(design="Ne=%d mu=%.0e m=%.0e" % (Ne, mu, m),
                          lean=lean, truth=truth, sem=sem))
    record("alleleFreqDivergenceRate", "DGP.lean",
           "1 / (2*Ne*(1 + theta + bigM))", cells,
           regime="per-generation across-replicate frequency variance from a "
                  "common start, normalised by p(1-p)")


def test_am_induced_ld():
    """amInducedLD: covariance between unlinked loci under assortative mating."""
    rng = np.random.default_rng(13201)
    cells = []
    for r, h2 in ((0.3, 0.5), (0.5, 0.5), (0.3, 0.8)):
        n, m = 40000, 40
        beta = np.full(m, 1.0 / math.sqrt(m))
        # start in linkage equilibrium
        g = rng.binomial(2, 0.5, (n, m)).astype(float)
        for _ in range(12):
            z = (g - g.mean(0)) / g.std(0)
            pgs = z @ beta
            e = rng.normal(0, math.sqrt((1 - h2) / h2 * pgs.var()), n)
            phen = pgs + e
            # mate by phenotype with correlation r: rank-pair a fraction r
            order = np.argsort(phen)
            mates = order.copy()
            shuffle = rng.random(n) > r
            mates[shuffle] = rng.permutation(mates[shuffle])
            dad, mom = order[: n // 2 * 2 : 2], mates[1 : n // 2 * 2 : 2]
            k = len(dad)
            child = np.empty((k * 2, m))
            for half, par in ((0, dad), (1, mom)):
                pass
            # transmit one allele from each parent at every locus
            a1 = rng.binomial(1, g[dad] / 2.0)
            a2 = rng.binomial(1, g[mom] / 2.0)
            kids = (a1 + a2).astype(float)
            g = np.repeat(kids, 2, axis=0)[:n]
        z = (g - g.mean(0)) / g.std(0)
        C = np.cov(z, rowvar=False)
        off = C[~np.eye(m, dtype=bool)]
        obs = float(off.mean())
        lean = (beta[0] * beta[1] * r * h2 / (1 - r * h2))
        cells.append(dict(design="r=%.1f h2=%.1f" % (r, h2), lean=lean,
                          truth=obs,
                          sem=float(off.std() / math.sqrt(len(off)))))
    record("amInducedLD", "AssortativeMatingPGS.lean",
           "beta_i*beta_j*r*h2/(1 - r*h2)", cells,
           regime="mean off-diagonal correlation between unlinked loci after "
                  "twelve generations of phenotypic assortative mating")


def main():
    for fn in (test_ancestry_averaged_effect, test_tight_linkage_share,
               test_allele_freq_divergence_rate, test_am_induced_ld):
        try:
            fn()
        except Exception:
            import traceback
            traceback.print_exc()
    json.dump(RESULTS, open("battery_bulk4_results.json", "w"), indent=1,
              default=str)
    print("\n\n================ SUMMARY ================")
    for r in RESULTS:
        w = r.get("worst", {})
        print("%-12s %-52s worst %9.2f sems, %7.2f%% rel"
              % (r["verdict"], r["name"], w.get("sems_off", float("nan")),
                 100 * w.get("rel_err", float("nan"))))


if __name__ == "__main__":
    main()
