"""The explicit list `popgen_defs/coverage.py`'s regex was reaching for.

That script decides coverage with

    re.finditer(r"[\"']([a-z][A-Za-z0-9_']{4,})[\"']", txt)

over its own sources, so a definition counts as covered when its NAME APPEARS
IN A STRING LITERAL -- evaluated or not.  Of the 32 definition names it matches,
2 are never used as code anywhere in those scripts.  Presence of a name is
standing in for existence of a check.

This module is the replacement: names that appear as `lean_<name>` (an explicit
statement that a Python function transcribes that definition) or as a called
identifier.  Generated by validation/extract/popgen_names.py; regenerate rather
than hand-editing.

To adopt, in popgen_defs/coverage.py:

    import sys; sys.path.insert(0, "../extract")
    from simulated_names import SIMULATED
    def tested_names(script_dir):
        return SIMULATED

Expect the number to go DOWN.  That is the right direction for a figure that
has been quoted as a floor.
"""

# 29 names, none ambiguous as short names in the current corpus.
# (`expectedSegmentLength` was here; the definition was deleted as falsified and its
#  validated replacement `expectedTractLength` has not been simulated under that name.)
SIMULATED = {
    'admixedFst',
    'admixtureLD',
    'amEquilibriumVariance',
    'coalFst',
    'continentIslandStepSelectionFirst',
    'demoSteppingStoneFst',
    'discoveryNCP',
    'effectGeneticCorrelation',
    'expectedHeterozygosity',
    'heterozygosityLossDerived',
    'heterozygosityLossFromDrift',
    'islandModelFst',
    'kinshipInflation',
    'ldAfterGenerations',
    'ldCorrelationSq',
    'ldHalfLife',
    'ldRetentionPerGen',
    'ldsrExpectedChi2',
    'metricPPV',
    'mse',
    'noncentralityParam',
    'partialOverlapR2',
    'pgsVariance',
    'phaseAttenuation',
    'r2EstimatorVariance',
    'r2ScalingModel',
    'targetHet',
    'variance',
}
