"""What would have to be true for the 23 soft-core definitions to be covered.

`softcore.py` identifies 23 definitions that are simultaneously

    SINGLE-TIER   no other checking layer touches them
    CONJECTURED   the bound graded against is inferred from the definition's
                  name or docstring, not proved by any theorem
    ONE-MUTANT    the check rejects exactly one of the nearby wrong bodies tried

They are covered in name only.  This module says, per definition, what would
have to exist for that to stop being true -- so whoever picks one up builds the
missing thing rather than rediscovering which thing is missing.

HOW TO READ IT.  Each axis fails for a different reason and needs a different
fix, and fixing one does not fix the others:

  SINGLE-TIER is fixed by a SECOND TIER evaluating the definition at all.  It
      is not fixed by strengthening my check, however much I strengthen it.  A
      single tier that is wrong about a definition is wrong about it alone.

  CONJECTURED is fixed by a THEOREM in the corpus stating the bound, after
      which the same check becomes theorem-graded and a violation becomes a
      defect rather than a lead.  It is NOT fixed by me choosing a better
      range: any range I choose is still my reading of the name.  This is the
      cheapest of the three to fix and the one that most changes what the
      coverage number means -- it converts "conforms to my reading of its name"
      into "conforms to what the development asserts".

  ONE-MUTANT is fixed by a check with more DISCRIMINATING POWER over the same
      body.  A nonnegativity check on an unbounded-above quantity can only ever
      reject sign errors, so it kills one mutant out of six however many
      mutants are tried.  The fix is an invariant with more structure --
      monotonicity in a named argument, a limit, an identity against a second
      definition, or a value at a known point.

WHAT THIS FILE IS NOT.  It is not a claim that these 23 are wrong.  Nothing here
found a defect in any of them.  It is a statement that if one WERE wrong, the
current evidence would probably not notice, which is a different and more
useful thing to record.

STATUS.  Compiled without local execution (no compute is permitted on this
machine).  The axis assignments come from softcore.json, which was generated by
a verified run.  The per-definition notes below are grounded in the Lean source
where marked READ, and inferred from the definition's name and check record
where marked INFERRED.  Anything INFERRED should be confirmed against the body
before acting on it.  One concrete item to check first is recorded in
OPEN_QUESTIONS.
"""
from __future__ import annotations

# --------------------------------------------------------------------------
# Generic upgrade paths, by axis.  These are exact: they follow from how
# coverage_v2 grades, not from judgement.
# --------------------------------------------------------------------------

UPGRADE_PATHS = {
    "single_tier": (
        "Any second tier producing a verdict on the definition. The differential "
        "tier needs an independent analytic reference or a simulation; the range "
        "tier needs the body inside its arithmetic fragment; the symbolic tier "
        "needs it to participate in an identity or a fixed point. Cheapest is "
        "usually the range tier, since it already parses everything this table "
        "parses."
    ),
    "conjectured_bound": (
        "A Lean theorem stating the bound under explicit hypotheses, e.g. "
        "`theorem f_in_unit (h : ...) : 0 <= f x /\\ f x <= 1`. The accounting "
        "then mines it automatically: `range_lo_thm` / `range_hi_thm` populate, "
        "`source_lo` / `source_hi` become \"theorem\", and a violation is "
        "reclassified from RANGE-MISMATCH to DEFECT. No change to this tier is "
        "needed -- the check already exists and is already falsifiable; only its "
        "authority is missing."
    ),
    "one_mutant": (
        "An invariant with more discriminating power over the same body. In "
        "rough order of cost: (a) monotonicity in one named argument, which "
        "kills every mutant that changes the sign of a partial derivative; "
        "(b) a value at a distinguished point (f at 0, at 1, at the equilibrium) "
        "which kills constant-factor and off-by-one mutants; (c) an identity "
        "against a second definition, which is the strongest and is what the "
        "strong core has."
    ),
}

# --------------------------------------------------------------------------
# Per definition.  `kind` groups definitions whose upgrade is the same shape.
# `needs` is the specific missing artefact.  `grounding` is READ (I read the
# Lean) or INFERRED (from the name and the check record).
# --------------------------------------------------------------------------

REQUIREMENTS = {
    # ---- unbounded-above magnitudes: nonnegativity is the only invariant, so
    # the check can only ever catch a sign error.  The upgrade is a real upper
    # bound or a monotonicity statement, not a tighter guess at the range.
    "Calibrator.adaptationDifficultyIndex": {
        "kind": "unbounded-ratio",
        "grounding": "READ  MetricSpecificPortability.lean:527, body `nParams / infoPerSample`",
        "needs": "It is d/I, a ratio of a parameter count to Fisher information, with "
                 "no upper bound at all -- so [0, inf) is the true range and a "
                 "nonnegativity check is the strongest range check possible. The "
                 "upgrade is not a bound: it is MONOTONICITY, strictly increasing in "
                 "nParams and strictly decreasing in infoPerSample, which the "
                 "docstring already asserts in words (\"smaller values mean the target "
                 "task can be estimated more precisely\"). A monotonicity theorem would "
                 "kill every mutant that swaps the operands or inverts the division.",
    },
    "Calibrator.fisherTraceMSELowerBound": {
        "kind": "unbounded-ratio",
        "grounding": "READ  MetricSpecificPortability.lean:535, body "
                     "`adaptationDifficultyIndex nParams infoPerSample / nEff`",
        "needs": "A wrapper over adaptationDifficultyIndex divided by nEff, so it "
                 "inherits that definition's weakness and adds one: it is asserted to "
                 "be a LOWER BOUND on an estimator's trace MSE, and nothing checks it "
                 "against any estimator. Two upgrades, in order: (a) the same "
                 "monotonicity theorem, now in three arguments; (b) the real one -- a "
                 "simulation that estimates d orthogonal parameters at known I and "
                 "n_eff and confirms the achieved trace MSE is >= this bound. That "
                 "second is external evidence and would move it out of the soft core "
                 "on two axes at once.",
    },
    "Calibrator.recalibrationTraceMSELowerBound": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED  same family as fisherTraceMSELowerBound",
        "needs": "As above. If it is the same bound specialised to recalibration "
                 "parameters, the strongest cheap check is an IDENTITY against "
                 "fisherTraceMSELowerBound at matching arguments -- identities are what "
                 "the strong core is made of, and this project has already found that "
                 "one quantity with three formulas in three files had two of them "
                 "wrong.",
    },
    "Calibrator.expectedNewMutations": {
        "kind": "unbounded-ratio",
        "grounding": "READ  PopulationGeneticsFoundations.lean:773, body `θ / 2 * t`, "
                     "with theorem `expectedNewMutations_nonneg`",
        "needs": "SEE OPEN_QUESTIONS -- a nonnegativity theorem exists, so this may be "
                 "misclassified as conjectured. Assuming the classification is right, "
                 "the definition is exactly linear in both arguments, which makes it "
                 "unusually cheap to check hard: it is theta*t/2, so f(2*theta, t) = "
                 "2*f(theta, t) exactly, and f(theta, 0) = 0. A scaling identity plus a "
                 "value at a distinguished point would kill most mutants. Externally, "
                 "the expected number of new segregating sites over t generations is "
                 "directly measurable in any coalescent simulator.",
    },
    "Calibrator.expectedSegmentLength": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED  HaplotypeTheory.lean:680",
        "needs": "An expected haplotype segment length under recombination. The "
                 "external check is standard and cheap: simulate recombination at a "
                 "known rate and measure mean segment length. Until then, the "
                 "structural check is the limit -- segment length must diverge as the "
                 "recombination rate goes to zero and shrink monotonically as it rises.",
    },
    "Calibrator.introgressionVariants": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED",
        "needs": "A count. Counts admit an exact external check by construction: "
                 "simulate the admixture scenario and count. This is a strong "
                 "candidate for the differential tier rather than for a better "
                 "invariant here.",
    },
    "Calibrator.logRateSampleSize": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED",
        "needs": "A sample-size formula. Sample-size formulas invert a power "
                 "calculation, so the sharp check is a ROUND TRIP: feed the returned n "
                 "into the corresponding power definition and confirm the target power "
                 "comes back. That is an identity against a second definition and would "
                 "move it to the strong core in one step.",
    },
    "Calibrator.importanceWeightESS": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED",
        "needs": "Effective sample size for importance weights has two exactly known "
                 "endpoints: ESS = n when all weights are equal, and ESS -> 1 as one "
                 "weight dominates. Both are computable checks that no wrong body "
                 "survives, and neither needs a theorem.",
    },
    "Calibrator.realWorldPGSVariance": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED",
        "needs": "A variance, so nonnegative and unbounded above. The upgrade is a "
                 "decomposition identity -- if it is a sum of components defined "
                 "elsewhere, checking that it equals their sum is worth more than any "
                 "range check.",
    },
    "Calibrator.spikeAndSlabPriorVariance": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED  a sibling `spikeAndSlabVariance` exists and has "
                     "CONTRADICTORY mined bounds (see coverage.json)",
        "needs": "A mixture variance: pi*sigma_large + (1-pi)*sigma_small in some form. "
                 "Exactly checkable at both endpoints (pi=0 and pi=1 must return the "
                 "two component variances) and monotone in pi between them. Note the "
                 "sibling definition has two theorems bounding it in contradictory "
                 "directions, which the accounting refuses to grade; whoever takes this "
                 "should look at both together.",
    },
    "Calibrator.optimalSlopeFromVariance": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED",
        "needs": "An optimal slope is the solution of a minimisation, so the check that "
                 "actually tests it is OPTIMALITY: evaluate the objective at the "
                 "returned slope and at perturbations either side, and confirm the "
                 "returned value is lowest. That rejects essentially every wrong body "
                 "and needs no theorem.",
    },
    "Calibrator.taggedDriftR2Ratio": {
        "kind": "unbounded-ratio",
        "grounding": "INFERRED",
        "needs": "A ratio of R-squareds. If both numerator and denominator are defined "
                 "in the corpus, the check is an identity against their quotient. If "
                 "the name implies it lies in [0,1], that needs a theorem -- ratios of "
                 "R-squareds routinely exceed 1, and `neutralAFBenchmarkRatio` in this "
                 "same corpus returns 2.4 where its name implies at most 1.",
    },

    # ---- unit-interval quantities whose [0,1] is assumed and not proved.  The
    # cheapest possible fix in the whole set: one theorem each, and the existing
    # check is upgraded automatically with no new machinery.
    "Calibrator.sensFromR2": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  routes through Phi, so flagged numeric_standins",
        "needs": "Sensitivity is a probability and must lie in [0,1]. A theorem "
                 "`0 <= sensFromR2 r2 /\\ sensFromR2 r2 <= 1` under the stated "
                 "hypotheses converts this from conjectured to theorem-graded. NOTE it "
                 "depends on Calibrator.Phi, which is a numeric stand-in in this tier "
                 "(erf form of Mathlib's Gaussian CDF), so a numerical disagreement "
                 "could be the stand-in rather than the definition. The theorem is the "
                 "clean fix; it needs no numerics.",
    },
    "Calibrator.specFromR2": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  sibling of sensFromR2",
        "needs": "As sensFromR2. Additionally the pair should satisfy the ROC "
                 "constraint -- sensitivity and specificity cannot both be improved by "
                 "raising the same threshold -- which is an identity across the two and "
                 "worth more than either range check.",
    },
    "Calibrator.tagAlleleFreqRetentionAt": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  PortabilityDrift.lean, `...At` family (time-indexed)",
        "needs": "A retention fraction, so [0,1], and time-indexed. Two theorems would "
                 "do it: the range, and MONOTONE DECREASE in t. The second is the "
                 "valuable one -- a retention that does not decrease with time is "
                 "wrong in a way no range check sees, and this is the same family as "
                 "the drift definitions where the corpus's worst model error lives.",
    },
    "Calibrator.causalAlleleFreqRetentionAt": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  sibling of tagAlleleFreqRetentionAt, killed 1/1",
        "needs": "As above, and it is the weakest evidence in the whole set: only ONE "
                 "distinguishable mutant was generated at all, so the falsifiability "
                 "ratio of 1/1 is not the reassurance it looks like. Whoever takes this "
                 "should first check whether the body is simple enough that the mutation "
                 "operators barely apply -- if so, this needs a hand-written check "
                 "rather than a stronger invariant.",
    },
    "Calibrator.GenerationalPopGenParameters.tauAt": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  PortabilityDrift.lean:2152, killed 1/6",
        "needs": "Coalescent time in scaled units, time-indexed. 1 of 6 mutants "
                 "rejected is the worst ratio in the set: five nearby wrong bodies were "
                 "distinguishable and the check noticed none of them. Needs "
                 "monotonicity in t plus a value at t=0, both of which the coalescent "
                 "fixes exactly.",
    },
    "Calibrator.popgenDrivenProxyScale": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED",
        "needs": "A scale factor. If the name means it multiplies something and stays "
                 "in [0,1], that needs a theorem; if it can exceed 1, the current check "
                 "is grading against a range the definition does not obey and should "
                 "be reporting RANGE-MISMATCH rather than COVERED. Worth resolving "
                 "which before adding evidence.",
    },
    "Calibrator.popgenDrivenTagScale": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  sibling of popgenDrivenProxyScale",
        "needs": "As above, and the two should be checked together -- a proxy scale and "
                 "a tag scale that cannot be ordered relative to each other is a "
                 "missing invariant in itself.",
    },
    "Calibrator.reconstructionWeight": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  ProjectionShiftBounds.lean",
        "needs": "A weight. Weights usually come with a normalisation -- if a family of "
                 "these sums to 1, that sum is the check, and it is far stronger than "
                 "any per-weight range.",
    },
    "Calibrator.detectionWeight": {
        "kind": "unit-interval-unproved",
        "grounding": "INFERRED  ProjectionShiftBounds.lean:259, killed 1/1",
        "needs": "As reconstructionWeight, and same caveat as "
                 "causalAlleleFreqRetentionAt: only one distinguishable mutant existed, "
                 "so the ratio is uninformative rather than good.",
    },

    # ---- predicate / structural: covered by witness and non-witness, which is
    # the weakest form of falsifiability this accounting recognises.
    "Calibrator.gwasDiscovered": {
        "kind": "structural-predicate",
        "grounding": "INFERRED  GeneticArchitectureDiscovery.lean:82, killed 1/2",
        "needs": "Covered by exhibiting one input where it holds and one where it does "
                 "not. That proves only that the predicate is not constant. The real "
                 "check is a DECISION BOUNDARY: at the stated significance threshold, "
                 "the predicate must flip exactly where the test statistic crosses it. "
                 "Testing the boundary rather than two arbitrary points is what makes "
                 "a predicate check worth anything.",
    },
    "Calibrator.clusterCrossCheck": {
        "kind": "structural-predicate",
        "grounding": "INFERRED  DriftRegime.lean:218, killed 1/2",
        "needs": "As gwasDiscovered. DriftRegime is the file the lead cites as the "
                 "model for regime declarations, so this definition is a good candidate "
                 "to carry the first explicit `Regime:` marker as well as a boundary "
                 "check.",
    },
}

# --------------------------------------------------------------------------

OPEN_QUESTIONS = [
    "Calibrator.expectedNewMutations is classified CONJECTURED-bound, but "
    "PopulationGeneticsFoundations.lean:777 contains "
    "`theorem expectedNewMutations_nonneg (hθ : 0 <= θ) (ht : 0 <= t) : "
    "0 <= expectedNewMutations θ t`. If that theorem is real and mentions the "
    "definition in its conclusion, `range_lo_thm` should have populated and the "
    "definition should be theorem-graded on its lower bound. Either the range "
    "mining missed it -- in which case other definitions are misclassified the "
    "same way and the 111 conjectured is an overcount -- or the classification "
    "is right for a reason I have not seen. CHECK FIRST when compute returns: "
    "`api.definition('Calibrator.expectedNewMutations')['constraints']` and look "
    "for range_lo_thm. This is the single highest-value item in this file, "
    "because it questions the axis rather than one definition.",

    "Two definitions (causalAlleleFreqRetentionAt, detectionWeight) show "
    "killed 1/1 -- one distinguishable mutant generated, one rejected. A ratio "
    "of 1.0 there means the mutation operators barely applied to that body, not "
    "that the check is strong. The falsifiability ratio should probably be "
    "reported as undefined below some minimum number of distinguishable "
    "mutants rather than as 1.0.",
]

CHEAPEST_WINS = [
    "The nine unit-interval definitions need ONE THEOREM EACH and no new "
    "machinery: the check already exists and is already falsifiable, only its "
    "authority is missing. Nine theorems would move nine definitions off the "
    "conjectured axis and reclassify any future violation from lead to defect.",

    "logRateSampleSize and optimalSlopeFromVariance can be checked to a much "
    "higher standard with no theorem and no simulation -- a round trip through "
    "the corresponding power definition, and an optimality check against "
    "perturbations. Both reject essentially every wrong body.",

    "importanceWeightESS and expectedNewMutations have exactly known values at "
    "distinguished points (equal weights, t=0) that any wrong body fails.",
]
