import Calibrator.TransportIdentities
import Mathlib.LinearAlgebra.Matrix.Trace

namespace Calibrator

noncomputable section

/-!
# Imitation and rigidity: exact finite-dimensional cores

This file formalizes the algebraic mechanisms that survive independently of
asymptotics:

* adding a random rank-one signal changes the column covariance by an exact
  rank-one bump;
* any nuisance covariance class closed under that bump can imitate the signal
  at the level of second moments;
* constant-diagonal (hence Toeplitz) classes are rigid against every bump whose
  loading has nonconstant squared coordinates;
* the alive/dead row construction leaves an exact two-point resolvent entry
  with strictly positive variance.

The stronger distributional statement for Gaussian rows, concentration rates,
and asymptotic spectral limits require probability-law hypotheses beyond these
identities and are intentionally not asserted here.
-/

section CovarianceAlgebra

variable {Ω ι : Type*}

theorem covariance_comm_exp (E : ExpFunctional Ω) (X Y : Ω → ℝ) :
    covariance E X Y = covariance E Y X := by
  rw [covariance_eq_expect_mul_sub_means, covariance_eq_expect_mul_sub_means]
  have hmul : (fun ω => X ω * Y ω) = fun ω => Y ω * X ω := by
    funext ω
    ring
  rw [hmul]
  ring

theorem covariance_add_left_exp
    (E : ExpFunctional Ω) (X Y Z : Ω → ℝ) :
    covariance E (fun ω => X ω + Y ω) Z =
      covariance E X Z + covariance E Y Z := by
  rw [covariance_comm_exp, covariance_add_right]
  rw [covariance_comm_exp E Z X, covariance_comm_exp E Z Y]

theorem covariance_smul_left_exp
    (E : ExpFunctional Ω) (X Y : Ω → ℝ) (c : ℝ) :
    covariance E (c • X) Y = c * covariance E X Y := by
  rw [covariance_comm_exp, covariance_smul_right]
  rw [covariance_comm_exp E Y X]

/-- A rank-one random signal added to each coordinate of a noise row. -/
def addRankOneSignal
    (noise : Ω → ι → ℝ) (factor : Ω → ℝ) (scale : ℝ) (loading : ι → ℝ) :
    Ω → ι → ℝ :=
  fun ω i => noise ω i + scale * factor ω * loading i

/-- The deterministic covariance bump generated by `addRankOneSignal`. -/
def rankOneCovarianceBump (scale : ℝ) (loading : ι → ℝ) : Matrix ι ι ℝ :=
  fun i j => scale ^ 2 * loading i * loading j

/-- Under the usual sample normalization, the covariance bump has coefficient
`signal² / sampleSize`. This is the exact finite-sample normalization used by
the imitation threshold calculation. -/
theorem rankOneCovarianceBump_sampleNormalized
    (signal sampleSize : ℝ) (loading : ι → ℝ) (i j : ι)
    (hsampleSize : 0 < sampleSize) :
    rankOneCovarianceBump (signal / Real.sqrt sampleSize) loading i j =
      (signal ^ 2 / sampleSize) * loading i * loading j := by
  unfold rankOneCovarianceBump
  rw [div_pow, Real.sq_sqrt (le_of_lt hsampleSize)]

/-- **Exact covariance imitation identity.** A centered unit-variance factor
uncorrelated with the noise changes the covariance by precisely the rank-one
bump `scale² vvᵀ`. No distributional or asymptotic assumption is used. -/
theorem covarianceMatrix_addRankOneSignal
    (E : ExpFunctional Ω)
    (noise : Ω → ι → ℝ) (factor : Ω → ℝ)
    (scale : ℝ) (loading : ι → ℝ)
    (hfactor : covariance E factor factor = 1)
    (hleft : ∀ i, covariance E (fun ω => noise ω i) factor = 0)
    (hright : ∀ i, covariance E factor (fun ω => noise ω i) = 0) :
    covarianceMatrix E (addRankOneSignal noise factor scale loading) =
      covarianceMatrix E noise + rankOneCovarianceBump scale loading := by
  ext i j
  simp only [covarianceMatrix, Matrix.of_apply, addRankOneSignal,
    Matrix.add_apply, rankOneCovarianceBump]
  have hi :
      (fun ω => noise ω i + scale * factor ω * loading i) =
        fun ω => noise ω i + (scale * loading i) * factor ω := by
    funext ω
    ring
  have hj :
      (fun ω => noise ω j + scale * factor ω * loading j) =
        fun ω => noise ω j + (scale * loading j) * factor ω := by
    funext ω
    ring
  rw [hi, hj]
  rw [covariance_add_left_exp, covariance_add_right, covariance_add_right]
  have hscaledLeft :
      covariance E (fun ω => (scale * loading i) * factor ω)
          (fun ω => noise ω j) = 0 := by
    change covariance E ((scale * loading i) • factor) (fun ω => noise ω j) = 0
    rw [covariance_smul_left_exp, hright j, mul_zero]
  have hscaledRight :
      covariance E (fun ω => noise ω i)
          (fun ω => (scale * loading j) * factor ω) = 0 := by
    change covariance E (fun ω => noise ω i) ((scale * loading j) • factor) = 0
    rw [covariance_smul_right, hleft i, mul_zero]
  have hscaledBoth :
      covariance E (fun ω => (scale * loading i) * factor ω)
          (fun ω => (scale * loading j) * factor ω) =
        scale ^ 2 * loading i * loading j := by
    change covariance E ((scale * loading i) • factor)
      ((scale * loading j) • factor) = _
    rw [covariance_smul_left_exp, covariance_smul_right, hfactor]
    ring
  rw [hscaledLeft, hscaledRight, hscaledBoth]
  ring

/-- A covariance nuisance class can imitate a rank-one signal whenever it is
closed under the corresponding covariance bump. -/
theorem covariance_imitation_of_rankOne_closed
    (nuisanceClass : Set (Matrix ι ι ℝ))
    (E : ExpFunctional Ω)
    (noise : Ω → ι → ℝ) (factor : Ω → ℝ)
    (scale : ℝ) (loading : ι → ℝ)
    (hnoise : covarianceMatrix E noise ∈ nuisanceClass)
    (hclosed : ∀ A ∈ nuisanceClass,
      A + rankOneCovarianceBump scale loading ∈ nuisanceClass)
    (hfactor : covariance E factor factor = 1)
    (hleft : ∀ i, covariance E (fun ω => noise ω i) factor = 0)
    (hright : ∀ i, covariance E factor (fun ω => noise ω i) = 0) :
    covarianceMatrix E (addRankOneSignal noise factor scale loading) ∈ nuisanceClass := by
  rw [covarianceMatrix_addRankOneSignal E noise factor scale loading
    hfactor hleft hright]
  exact hclosed _ hnoise

end CovarianceAlgebra

section Rigidity

variable {ι : Type*}

/-- Constant diagonal is a necessary condition for every Toeplitz covariance
matrix and is enough to expose generic rank-one imitation failure. -/
def ConstantDiagonal (A : Matrix ι ι ℝ) : Prop :=
  ∀ i j, A i i = A j j

/-- Invariance of a matrix under simultaneous application of an index shift.
Toeplitz and stationary covariance classes are instances of this condition. -/
def ShiftInvariant (shift : ι → ι) (A : Matrix ι ι ℝ) : Prop :=
  ∀ i j, A (shift i) (shift j) = A i j

/-- A rank-one bump with nonconstant squared loadings leaves the
constant-diagonal class. This is the finite-dimensional rigidity mechanism
behind the failure of stationary nuisance classes to absorb a generic spike. -/
theorem add_rankOneBump_not_constantDiagonal
    (K : Matrix ι ι ℝ) (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ConstantDiagonal K)
    (hscale : scale ≠ 0)
    (hloading : loading i ^ 2 ≠ loading j ^ 2) :
    ¬ ConstantDiagonal (K + rankOneCovarianceBump scale loading) := by
  intro hconstant
  have hij := hconstant i j
  have hdiag := hK i j
  simp only [Matrix.add_apply, rankOneCovarianceBump] at hij
  have hscaleSq : 0 < scale ^ 2 := sq_pos_of_ne_zero hscale
  apply hloading
  nlinarith [hij, hdiag]

/-- Consequently the class of constant-diagonal covariances is not closed
under such a bump. -/
theorem constantDiagonal_class_is_rankOne_rigid
    (K : Matrix ι ι ℝ) (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ConstantDiagonal K)
    (hscale : scale ≠ 0)
    (hloading : loading i ^ 2 ≠ loading j ^ 2) :
    K + rankOneCovarianceBump scale loading ∉ {A | ConstantDiagonal A} :=
  add_rankOneBump_not_constantDiagonal K scale loading i j hK hscale hloading

/-- **Exact classification of stationary imitation.** For a nonzero signal,
adding its covariance bump preserves shift invariance exactly when the loading's
entire rank-one outer product is itself shift invariant. Thus the nuisance
geometry can imitate precisely the loadings satisfying this algebraic rigidity
condition, and no others. -/
theorem add_rankOneBump_shiftInvariant_iff_of_ne
    (shift : ι → ι) (K : Matrix ι ι ℝ)
    (scale : ℝ) (loading : ι → ℝ)
    (hK : ShiftInvariant shift K)
    (hscale : scale ≠ 0) :
    ShiftInvariant shift (K + rankOneCovarianceBump scale loading) ↔
      ∀ i j, loading (shift i) * loading (shift j) = loading i * loading j := by
  constructor
  · intro hinvariant i j
    have hbump := hinvariant i j
    have hbase := hK i j
    simp only [Matrix.add_apply, rankOneCovarianceBump] at hbump
    have hscaled :
        scale ^ 2 * (loading (shift i) * loading (shift j)) =
          scale ^ 2 * (loading i * loading j) := by
      nlinarith [hbump, hbase]
    exact mul_left_cancel₀ (pow_ne_zero 2 hscale) hscaled
  · intro hloading i j
    simp only [Matrix.add_apply, rankOneCovarianceBump]
    rw [hK i j]
    nlinarith [hloading i j]

/-- **Stationary rigidity.** A shift-invariant covariance cannot absorb a
rank-one bump whose pairwise loading products are changed by the shift. Unlike
the diagonal corollary above, this detects nonstationarity in off-diagonal
entries as well. -/
theorem add_rankOneBump_not_shiftInvariant
    (shift : ι → ι) (K : Matrix ι ι ℝ)
    (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ShiftInvariant shift K)
    (hscale : scale ≠ 0)
    (hloading :
      loading (shift i) * loading (shift j) ≠ loading i * loading j) :
    ¬ ShiftInvariant shift (K + rankOneCovarianceBump scale loading) := by
  rw [add_rankOneBump_shiftInvariant_iff_of_ne shift K scale loading hK hscale]
  exact not_forall_of_exists_not ⟨i, not_forall_of_exists_not ⟨j, hloading⟩⟩

/-- The whole shift-invariant nuisance class is therefore rigid against a
generic rank-one covariance bump. -/
theorem shiftInvariant_class_is_rankOne_rigid
    (shift : ι → ι) (K : Matrix ι ι ℝ)
    (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ShiftInvariant shift K)
    (hscale : scale ≠ 0)
    (hloading :
      loading (shift i) * loading (shift j) ≠ loading i * loading j) :
    K + rankOneCovarianceBump scale loading ∉ {A | ShiftInvariant shift A} :=
  add_rankOneBump_not_shiftInvariant shift K scale loading i j
    hK hscale hloading

end Rigidity

section DeadSensors

/-- Scalar Schur-complement resolvent entry for a row with latent amplitude. -/
def scalarRowResolvent (latent quadraticForm : ℝ) : ℝ :=
  1 / (1 + latent ^ 2 * quadraticForm)

@[simp] theorem scalarRowResolvent_dead (quadraticForm : ℝ) :
    scalarRowResolvent 0 quadraticForm = 1 := by
  simp [scalarRowResolvent]

@[simp] theorem scalarRowResolvent_alive (quadraticForm : ℝ) :
    scalarRowResolvent (Real.sqrt 2) quadraticForm =
      1 / (1 + 2 * quadraticForm) := by
  unfold scalarRowResolvent
  rw [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 2)]

/-- Variance of a fair two-point law. -/
def fairTwoPointVariance (a b : ℝ) : ℝ := (a - b) ^ 2 / 4

/-- **Exact nonconcentration witness.** If the leave-one-out quadratic form is
positive, an alive/dead row produces two separated resolvent values and hence
a strictly positive fair-mixture variance. -/
theorem deadSensor_resolvent_variance_pos
    (quadraticForm : ℝ) (hquadratic : 0 < quadraticForm) :
    0 < fairTwoPointVariance
      (scalarRowResolvent 0 quadraticForm)
      (scalarRowResolvent (Real.sqrt 2) quadraticForm) := by
  rw [scalarRowResolvent_dead, scalarRowResolvent_alive]
  have hden : 0 < 1 + 2 * quadraticForm := by linarith
  have hneq : (1 : ℝ) ≠ 1 / (1 + 2 * quadraticForm) := by
    intro h
    field_simp [ne_of_gt hden] at h
    linarith
  unfold fairTwoPointVariance
  exact div_pos (sq_pos_of_ne_zero (sub_ne_zero.mpr hneq)) (by norm_num)

end DeadSensors

end

end Calibrator
