import Calibrator.TransportIdentities
import Calibrator.LDDecayTheory
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.LinearAlgebra.Matrix.Symmetric
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic

namespace Calibrator

noncomputable section

/-!
# Imitation and rigidity: exact finite-dimensional cores

This file formalizes the algebraic mechanisms that survive independently of
asymptotics:

* adding a random rank-one signal changes the column covariance by an exact
  rank-one bump;
* any nuisance covariance class closed under that bump can imitate the signal
  at the level of second moments;
* constant-diagonal (hence Toeplitz) classes are rigid against every bump whose
  loading has nonconstant squared coordinates;
* the alive/dead row construction leaves an exact two-point resolvent entry
  with strictly positive variance.

The stronger distributional statement for Gaussian rows, concentration rates,
and asymptotic spectral limits require probability-law hypotheses beyond these
identities and are intentionally not asserted here.
-/

section CovarianceAlgebra

variable {Ω ι : Type*}

theorem covariance_comm_exp (E : ExpFunctional Ω) (X Y : Ω → ℝ) :
    covariance E X Y = covariance E Y X := by
  rw [covariance_eq_expect_mul_sub_means, covariance_eq_expect_mul_sub_means]
  have hmul : (fun ω => X ω * Y ω) = fun ω => Y ω * X ω := by
    funext ω
    ring
  rw [hmul]
  ring

theorem covariance_add_left_exp
    (E : ExpFunctional Ω) (X Y Z : Ω → ℝ) :
    covariance E (fun ω => X ω + Y ω) Z =
      covariance E X Z + covariance E Y Z := by
  rw [covariance_comm_exp, covariance_add_right]
  rw [covariance_comm_exp E Z X, covariance_comm_exp E Z Y]

theorem covariance_smul_left_exp
    (E : ExpFunctional Ω) (X Y : Ω → ℝ) (c : ℝ) :
    covariance E (c • X) Y = c * covariance E X Y := by
  rw [covariance_comm_exp, covariance_smul_right]
  rw [covariance_comm_exp E Y X]

/-- A rank-one random signal added to each coordinate of a noise row. -/
def addRankOneSignal
    (noise : Ω → ι → ℝ) (factor : Ω → ℝ) (scale : ℝ) (loading : ι → ℝ) :
    Ω → ι → ℝ :=
  fun ω i => noise ω i + scale * factor ω * loading i

/-- The deterministic covariance bump generated by `addRankOneSignal`. -/
def rankOneCovarianceBump (scale : ℝ) (loading : ι → ℝ) : Matrix ι ι ℝ :=
  fun i j => scale ^ 2 * loading i * loading j

/-- Under the usual sample normalization, the covariance bump has coefficient
`signal² / sampleSize`. This is the exact finite-sample normalization used by
the imitation threshold calculation. -/
theorem rankOneCovarianceBump_sampleNormalized
    (signal sampleSize : ℝ) (loading : ι → ℝ) (i j : ι)
    (hsampleSize : 0 < sampleSize) :
    rankOneCovarianceBump (signal / Real.sqrt sampleSize) loading i j =
      (signal ^ 2 / sampleSize) * loading i * loading j := by
  unfold rankOneCovarianceBump
  rw [div_pow, Real.sq_sqrt (le_of_lt hsampleSize)]

/-- **Exact covariance imitation identity.** A centered unit-variance factor
uncorrelated with the noise changes the covariance by precisely the rank-one
bump `scale² vvᵀ`. No distributional or asymptotic assumption is used. -/
theorem covarianceMatrix_addRankOneSignal
    (E : ExpFunctional Ω)
    (noise : Ω → ι → ℝ) (factor : Ω → ℝ)
    (scale : ℝ) (loading : ι → ℝ)
    (hfactor : covariance E factor factor = 1)
    (hleft : ∀ i, covariance E (fun ω => noise ω i) factor = 0)
    (hright : ∀ i, covariance E factor (fun ω => noise ω i) = 0) :
    covarianceMatrix E (addRankOneSignal noise factor scale loading) =
      covarianceMatrix E noise + rankOneCovarianceBump scale loading := by
  ext i j
  simp only [covarianceMatrix, Matrix.of_apply, addRankOneSignal,
    Matrix.add_apply, rankOneCovarianceBump]
  have hi :
      (fun ω => noise ω i + scale * factor ω * loading i) =
        fun ω => noise ω i + (scale * loading i) * factor ω := by
    funext ω
    ring
  have hj :
      (fun ω => noise ω j + scale * factor ω * loading j) =
        fun ω => noise ω j + (scale * loading j) * factor ω := by
    funext ω
    ring
  rw [hi, hj]
  rw [covariance_add_left_exp, covariance_add_right, covariance_add_right]
  have hscaledLeft :
      covariance E (fun ω => (scale * loading i) * factor ω)
          (fun ω => noise ω j) = 0 := by
    change covariance E ((scale * loading i) • factor) (fun ω => noise ω j) = 0
    rw [covariance_smul_left_exp, hright j, mul_zero]
  have hscaledRight :
      covariance E (fun ω => noise ω i)
          (fun ω => (scale * loading j) * factor ω) = 0 := by
    change covariance E (fun ω => noise ω i) ((scale * loading j) • factor) = 0
    rw [covariance_smul_right, hleft i, mul_zero]
  have hscaledBoth :
      covariance E (fun ω => (scale * loading i) * factor ω)
          (fun ω => (scale * loading j) * factor ω) =
        scale ^ 2 * loading i * loading j := by
    change covariance E ((scale * loading i) • factor)
      ((scale * loading j) • factor) = _
    rw [covariance_smul_left_exp, covariance_smul_right, hfactor]
    ring
  rw [hscaledLeft, hscaledRight, hscaledBoth]
  ring

/-- A covariance nuisance class can imitate a rank-one signal whenever it is
closed under the corresponding covariance bump. -/
theorem covariance_imitation_of_rankOne_closed
    (nuisanceClass : Set (Matrix ι ι ℝ))
    (E : ExpFunctional Ω)
    (noise : Ω → ι → ℝ) (factor : Ω → ℝ)
    (scale : ℝ) (loading : ι → ℝ)
    (hnoise : covarianceMatrix E noise ∈ nuisanceClass)
    (hclosed : ∀ A ∈ nuisanceClass,
      A + rankOneCovarianceBump scale loading ∈ nuisanceClass)
    (hfactor : covariance E factor factor = 1)
    (hleft : ∀ i, covariance E (fun ω => noise ω i) factor = 0)
    (hright : ∀ i, covariance E factor (fun ω => noise ω i) = 0) :
    covarianceMatrix E (addRankOneSignal noise factor scale loading) ∈ nuisanceClass := by
  rw [covarianceMatrix_addRankOneSignal E noise factor scale loading
    hfactor hleft hright]
  exact hclosed _ hnoise

end CovarianceAlgebra

section Rigidity

variable {ι : Type*}

/-- Constant diagonal is a necessary condition for every Toeplitz covariance
matrix and is enough to expose generic rank-one imitation failure. -/
def ConstantDiagonal (A : Matrix ι ι ℝ) : Prop :=
  ∀ i j, A i i = A j j

/-- Invariance of a matrix under simultaneous application of an index shift.
Toeplitz and stationary covariance classes are instances of this condition. -/
def ShiftInvariant (shift : ι → ι) (A : Matrix ι ι ℝ) : Prop :=
  ∀ i j, A (shift i) (shift j) = A i j

/-- A rank-one bump with nonconstant squared loadings leaves the
constant-diagonal class. This is the finite-dimensional rigidity mechanism
behind the failure of stationary nuisance classes to absorb a generic spike. -/
theorem add_rankOneBump_not_constantDiagonal
    (K : Matrix ι ι ℝ) (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ConstantDiagonal K)
    (hscale : scale ≠ 0)
    (hloading : loading i ^ 2 ≠ loading j ^ 2) :
    ¬ ConstantDiagonal (K + rankOneCovarianceBump scale loading) := by
  intro hconstant
  have hij := hconstant i j
  have hdiag := hK i j
  simp only [Matrix.add_apply, rankOneCovarianceBump] at hij
  have hscaleSq : 0 < scale ^ 2 := sq_pos_of_ne_zero hscale
  apply hloading
  nlinarith [hij, hdiag]

/-- Consequently the class of constant-diagonal covariances is not closed
under such a bump. -/
theorem constantDiagonal_class_is_rankOne_rigid
    (K : Matrix ι ι ℝ) (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ConstantDiagonal K)
    (hscale : scale ≠ 0)
    (hloading : loading i ^ 2 ≠ loading j ^ 2) :
    K + rankOneCovarianceBump scale loading ∉ {A | ConstantDiagonal A} :=
  add_rankOneBump_not_constantDiagonal K scale loading i j hK hscale hloading

/-- **Exact classification of stationary imitation.** For a nonzero signal,
adding its covariance bump preserves shift invariance exactly when the loading's
entire rank-one outer product is itself shift invariant. Thus the nuisance
geometry can imitate precisely the loadings satisfying this algebraic rigidity
condition, and no others. -/
theorem add_rankOneBump_shiftInvariant_iff_of_ne
    (shift : ι → ι) (K : Matrix ι ι ℝ)
    (scale : ℝ) (loading : ι → ℝ)
    (hK : ShiftInvariant shift K)
    (hscale : scale ≠ 0) :
    ShiftInvariant shift (K + rankOneCovarianceBump scale loading) ↔
      ∀ i j, loading (shift i) * loading (shift j) = loading i * loading j := by
  constructor
  · intro hinvariant i j
    have hbump := hinvariant i j
    have hbase := hK i j
    simp only [Matrix.add_apply, rankOneCovarianceBump] at hbump
    have hscaled :
        scale ^ 2 * (loading (shift i) * loading (shift j)) =
          scale ^ 2 * (loading i * loading j) := by
      nlinarith [hbump, hbase]
    exact mul_left_cancel₀ (pow_ne_zero 2 hscale) hscaled
  · intro hloading i j
    simp only [Matrix.add_apply, rankOneCovarianceBump]
    rw [hK i j]
    nlinarith [hloading i j]

/-- **Stationary rigidity.** A shift-invariant covariance cannot absorb a
rank-one bump whose pairwise loading products are changed by the shift. Unlike
the diagonal corollary above, this detects nonstationarity in off-diagonal
entries as well. -/
theorem add_rankOneBump_not_shiftInvariant
    (shift : ι → ι) (K : Matrix ι ι ℝ)
    (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ShiftInvariant shift K)
    (hscale : scale ≠ 0)
    (hloading :
      loading (shift i) * loading (shift j) ≠ loading i * loading j) :
    ¬ ShiftInvariant shift (K + rankOneCovarianceBump scale loading) := by
  rw [add_rankOneBump_shiftInvariant_iff_of_ne shift K scale loading hK hscale]
  exact not_forall_of_exists_not ⟨i, not_forall_of_exists_not ⟨j, hloading⟩⟩

/-- The whole shift-invariant nuisance class is therefore rigid against a
generic rank-one covariance bump. -/
theorem shiftInvariant_class_is_rankOne_rigid
    (shift : ι → ι) (K : Matrix ι ι ℝ)
    (scale : ℝ) (loading : ι → ℝ) (i j : ι)
    (hK : ShiftInvariant shift K)
    (hscale : scale ≠ 0)
    (hloading :
      loading (shift i) * loading (shift j) ≠ loading i * loading j) :
    K + rankOneCovarianceBump scale loading ∉ {A | ShiftInvariant shift A} :=
  add_rankOneBump_not_shiftInvariant shift K scale loading i j
    hK hscale hloading

end Rigidity

section DeadSensors

/-- Scalar Schur-complement resolvent entry for a row with latent amplitude. -/
def scalarRowResolvent (latent quadraticForm : ℝ) : ℝ :=
  1 / (1 + latent ^ 2 * quadraticForm)

@[simp] theorem scalarRowResolvent_dead (quadraticForm : ℝ) :
    scalarRowResolvent 0 quadraticForm = 1 := by
  simp [scalarRowResolvent]

@[simp] theorem scalarRowResolvent_alive (quadraticForm : ℝ) :
    scalarRowResolvent (Real.sqrt 2) quadraticForm =
      1 / (1 + 2 * quadraticForm) := by
  unfold scalarRowResolvent
  rw [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 2)]

/-- Variance of a fair two-point law. -/
def fairTwoPointVariance (a b : ℝ) : ℝ := (a - b) ^ 2 / 4

/-- **Exact nonconcentration witness.** If the leave-one-out quadratic form is
positive, an alive/dead row produces two separated resolvent values and hence
a strictly positive fair-mixture variance. -/
theorem deadSensor_resolvent_variance_pos
    (quadraticForm : ℝ) (hquadratic : 0 < quadraticForm) :
    0 < fairTwoPointVariance
      (scalarRowResolvent 0 quadraticForm)
      (scalarRowResolvent (Real.sqrt 2) quadraticForm) := by
  rw [scalarRowResolvent_dead, scalarRowResolvent_alive]
  have hden : 0 < 1 + 2 * quadraticForm := by linarith
  have hneq : (1 : ℝ) ≠ 1 / (1 + 2 * quadraticForm) := by
    intro h
    field_simp [ne_of_gt hden] at h
    linarith
  unfold fairTwoPointVariance
  exact div_pos (sq_pos_of_ne_zero (sub_ne_zero.mpr hneq)) (by norm_num)

end DeadSensors

section Headroom

/-!
## Headroom: exactly how large a polygenic signal a background class can imitate

The rank-one bump of the previous section is what a polygenic signal looks like
to a second-moment analysis: mixing the per-individual signal factor over its
own prior — the infinitesimal model — leaves a genotype covariance inflated by
`scale² vvᵀ`, where `v` is the direction of the effect vector. Whether that is
an *imitation* rather than a *signal* depends on one thing: whether the
inflated covariance is still a legal member of the background class.

For the class used by adaptive-detection formulations — every covariance whose
score variance is bounded by a ceiling `C₀` — the answer is a secular equation,
proved here exactly, with no asymptotics, no invertibility, and no eigenvalues:
the bumped background stays legal exactly when

    scale² · vᵀ (C₀ I - K)⁻¹ v ≤ 1.

Below that threshold the signal-carrying model has a covariance that is legal
under the null covariance class. This proves imitation for every procedure
whose input is restricted to second moments. Promoting covariance imitation to
an identity of full experiments requires Gaussian-law hypotheses and is not
asserted by the finite algebra below.
-/

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- Bilinear form `xᵀ A y` over a finite variant index. -/
def gramForm (A : Matrix ι ι ℝ) (x y : ι → ℝ) : ℝ :=
  ∑ i, ∑ j, x i * A i j * y j

/-- Quadratic form `xᵀ A x`. When `A` is a genotype second-moment matrix this
is the variance of the polygenic score with weights `x`, so every statement in
this section is a statement about score variances. -/
def quadForm (A : Matrix ι ι ℝ) (x : ι → ℝ) : ℝ := gramForm A x x

/-- A matrix is variance-nonnegative when no weighting of the variants produces
a negative score variance: positive semidefiniteness, in the form the genetics
uses it. -/
def VarianceNonneg (A : Matrix ι ι ℝ) : Prop := ∀ x : ι → ℝ, 0 ≤ quadForm A x

theorem gramForm_symm {A : Matrix ι ι ℝ} (hA : A.IsSymm) (x y : ι → ℝ) :
    gramForm A x y = gramForm A y x := by
  unfold gramForm
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl (fun i _ => Finset.sum_congr rfl (fun j _ => ?_))
  have hsym : A j i = A i j := hA.apply i j
  rw [hsym]; ring

theorem gramForm_sub_left (A : Matrix ι ι ℝ) (x y z : ι → ℝ) :
    gramForm A (x - y) z = gramForm A x z - gramForm A y z := by
  unfold gramForm
  rw [← Finset.sum_sub_distrib]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [← Finset.sum_sub_distrib]
  exact Finset.sum_congr rfl (fun j _ => by simp [sub_mul])

theorem gramForm_smul_left (A : Matrix ι ι ℝ) (c : ℝ) (x y : ι → ℝ) :
    gramForm A (c • x) y = c * gramForm A x y := by
  unfold gramForm
  rw [Finset.mul_sum]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [Finset.mul_sum]
  exact Finset.sum_congr rfl (fun j _ => by simp [Pi.smul_apply, smul_eq_mul]; ring)

theorem gramForm_sub_matrix (A B : Matrix ι ι ℝ) (x y : ι → ℝ) :
    gramForm (A - B) x y = gramForm A x y - gramForm B x y := by
  unfold gramForm
  rw [← Finset.sum_sub_distrib]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [← Finset.sum_sub_distrib]
  exact Finset.sum_congr rfl (fun j _ => by simp [Matrix.sub_apply, mul_sub, sub_mul])

theorem quadForm_sub_matrix (A B : Matrix ι ι ℝ) (x : ι → ℝ) :
    quadForm (A - B) x = quadForm A x - quadForm B x :=
  gramForm_sub_matrix A B x x

/-- Expansion of a score variance along a line: the only analytic input the
Cauchy–Schwarz step needs. -/
theorem quadForm_sub_smul {A : Matrix ι ι ℝ} (hA : A.IsSymm) (x y : ι → ℝ) (s : ℝ) :
    quadForm A (x - s • y) =
      quadForm A x - 2 * s * gramForm A y x + s ^ 2 * quadForm A y := by
  unfold quadForm
  have h1 : gramForm A x (x - s • y) = gramForm A x x - s * gramForm A y x := by
    rw [gramForm_symm hA x (x - s • y), gramForm_sub_left, gramForm_smul_left,
      gramForm_symm hA x x]
  have h2 : gramForm A y (x - s • y) = gramForm A y x - s * gramForm A y y := by
    rw [gramForm_symm hA y (x - s • y), gramForm_sub_left, gramForm_smul_left,
      gramForm_symm hA x y, gramForm_symm hA y y]
  rw [gramForm_sub_left, gramForm_smul_left, h1, h2]
  ring

/-- **Cauchy–Schwarz in the metric of a genotype covariance.** The covariance
between two polygenic scores is at most the geometric mean of their variances.
No invertibility is assumed, so a singular genotype second-moment matrix — the
normal case, more variants than individuals — is admissible. -/
theorem gramForm_sq_le {A : Matrix ι ι ℝ} (hA : A.IsSymm) (hpos : VarianceNonneg A)
    (x y : ι → ℝ) :
    gramForm A y x ^ 2 ≤ quadForm A x * quadForm A y := by
  rcases eq_or_lt_of_le (hpos y) with hzero | hposy
  · have hall : ∀ s : ℝ, 0 ≤ quadForm A x - 2 * s * gramForm A y x := by
      intro s
      have hs := hpos (x - s • y)
      rw [quadForm_sub_smul hA x y s, ← hzero] at hs
      simpa using hs
    have hb : gramForm A y x = 0 := by
      by_contra hne
      have hbig := hall ((quadForm A x + 1) / (2 * gramForm A y x))
      rw [mul_div_assoc'] at hbig
      have h2 : (2 : ℝ) * gramForm A y x ≠ 0 := by
        simpa using hne
      field_simp at hbig
      linarith
    rw [hb, ← hzero]; simp
  · have h := hpos (x - (gramForm A y x / quadForm A y) • y)
    rw [quadForm_sub_smul hA x y] at h
    have hq : quadForm A y ≠ 0 := ne_of_gt hposy
    field_simp at h
    nlinarith [h, hposy]

/-- The score variance contributed by a rank-one covariance bump is the squared
projection of the weights on the signal direction. -/
theorem quadForm_rankOneCovarianceBump (scale : ℝ) (loading x : ι → ℝ) :
    quadForm (rankOneCovarianceBump scale loading) x =
      scale ^ 2 * dot loading x ^ 2 := by
  unfold quadForm gramForm rankOneCovarianceBump dot
  have hrow : ∀ i : ι,
      (∑ j, x i * (scale ^ 2 * loading i * loading j) * x j) =
        (scale ^ 2 * (x i * loading i)) * ∑ j, loading j * x j := by
    intro i
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl (fun j _ => by ring)
  simp_rw [hrow]
  rw [← Finset.sum_mul, ← Finset.mul_sum]
  have hswap : (∑ i, x i * loading i) = ∑ i, loading i * x i :=
    Finset.sum_congr rfl (fun i _ => mul_comm _ _)
  rw [hswap]
  ring

/-- A vector that the covariance maps onto the signal direction — the solution
of `A w = v`, written without ever forming an inverse — reproduces the signal
functional. -/
theorem gramForm_witness {A : Matrix ι ι ℝ} (hA : A.IsSymm)
    {loading witness : ι → ℝ} (hwitness : A.mulVec witness = loading) (x : ι → ℝ) :
    gramForm A witness x = dot loading x := by
  have hexpand : gramForm A witness x = ∑ j, (A.mulVec witness) j * x j := by
    unfold gramForm
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl (fun j _ => ?_)
    simp only [Matrix.mulVec, dotProduct, Finset.sum_mul]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    have hsym : A j i = A i j := hA.apply i j
    rw [hsym]; ring
  rw [hexpand, hwitness]
  rfl

/-- **The secular criterion for imitation.** A background covariance `A`
(read: the headroom `C₀ I - K` left by the class ceiling) absorbs a rank-one
polygenic bump of size `scale²` in the direction `v` exactly when
`scale² · vᵀ A⁻¹ v ≤ 1`, with `A⁻¹ v` supplied as a witness rather than an
inverse. This is an exact finite-dimensional equivalence: no eigenvalues, no
proportional regime, no moment assumptions. -/
theorem varianceNonneg_sub_rankOne_iff
    {A : Matrix ι ι ℝ} (hA : A.IsSymm) (hpos : VarianceNonneg A)
    {loading witness : ι → ℝ} (hwitness : A.mulVec witness = loading)
    (scale : ℝ) :
    VarianceNonneg (A - rankOneCovarianceBump scale loading) ↔
      scale ^ 2 * quadForm A witness ≤ 1 := by
  have hproj : ∀ x, dot loading x = gramForm A witness x := fun x =>
    (gramForm_witness hA hwitness x).symm
  have hself : quadForm A witness = dot loading witness :=
    (gramForm_witness hA hwitness witness).symm ▸ rfl
  constructor
  · intro hclass
    have hw := hclass witness
    rw [quadForm_sub_matrix, quadForm_rankOneCovarianceBump, ← hself] at hw
    rcases eq_or_lt_of_le (hpos witness) with hzero | hpq
    · rw [← hzero]; simpa using zero_le_one
    · nlinarith [hw, hpq]
  · intro hthreshold x
    rw [quadForm_sub_matrix, quadForm_rankOneCovarianceBump, hproj x]
    have hcs : gramForm A witness x ^ 2 ≤ quadForm A x * quadForm A witness :=
      gramForm_sq_le hA hpos x witness
    have hscale : (0 : ℝ) ≤ scale ^ 2 := sq_nonneg scale
    have hx : 0 ≤ quadForm A x := hpos x
    nlinarith [hcs, hscale, hx, hthreshold]

/-- The spectral-ceiling background class: every polygenic score built from the
background has variance at most `ceiling`. This is the class that adaptive
detection formulations range over when only spectral bounds on the background
are assumed. -/
def BelowCeiling (ceiling : ℝ) (K : Matrix ι ι ℝ) : Prop :=
  VarianceNonneg (ceiling • (1 : Matrix ι ι ℝ) - K)

/-- **Imitation threshold for a spectral-ceiling class.** With `gap` the
headroom `C₀ I - K` left by the ceiling, a polygenic bump of size `scale²` in
direction `v` keeps the background inside its own class exactly when
`scale² vᵀ gap⁻¹ v ≤ 1`. Above the threshold the inflated background leaves the
class and the signal becomes, in principle, detectable. -/
theorem belowCeiling_add_rankOne_iff
    {ceiling : ℝ} {K : Matrix ι ι ℝ}
    (hsymm : (ceiling • (1 : Matrix ι ι ℝ) - K).IsSymm)
    (hgap : VarianceNonneg (ceiling • (1 : Matrix ι ι ℝ) - K))
    {loading witness : ι → ℝ}
    (hwitness : (ceiling • (1 : Matrix ι ι ℝ) - K).mulVec witness = loading)
    (scale : ℝ) :
    BelowCeiling ceiling (K + rankOneCovarianceBump scale loading) ↔
      scale ^ 2 * quadForm (ceiling • (1 : Matrix ι ι ℝ) - K) witness ≤ 1 := by
  have hrewrite :
      ceiling • (1 : Matrix ι ι ℝ) - (K + rankOneCovarianceBump scale loading) =
        (ceiling • (1 : Matrix ι ι ℝ) - K) - rankOneCovarianceBump scale loading := by
    ext i j; simp [Matrix.sub_apply, Matrix.add_apply]; ring
  unfold BelowCeiling
  rw [hrewrite]
  exact varianceNonneg_sub_rankOne_iff hsymm hgap hwitness scale

/-- **The imitation theorem, in genotype form.** Below the secular threshold the
covariance of the *signal-carrying* genotype matrix is itself a legal member of
the background class: the polygenic signal has been absorbed into background
structure exactly at the level of second moments. This alone does not identify
the full probability laws outside a Gaussian model. -/
theorem spiked_genotype_covariance_belowCeiling
    {Ω : Type*} (E : ExpFunctional Ω)
    (noise : Ω → ι → ℝ) (factor : Ω → ℝ)
    (scale : ℝ) (loading witness : ι → ℝ) (ceiling : ℝ)
    (hsymm : (ceiling • (1 : Matrix ι ι ℝ) - covarianceMatrix E noise).IsSymm)
    (hgap : VarianceNonneg (ceiling • (1 : Matrix ι ι ℝ) - covarianceMatrix E noise))
    (hwitness :
      (ceiling • (1 : Matrix ι ι ℝ) - covarianceMatrix E noise).mulVec witness = loading)
    (hfactor : covariance E factor factor = 1)
    (hleft : ∀ i, covariance E (fun ω => noise ω i) factor = 0)
    (hright : ∀ i, covariance E factor (fun ω => noise ω i) = 0)
    (hthreshold :
      scale ^ 2 *
        quadForm (ceiling • (1 : Matrix ι ι ℝ) - covarianceMatrix E noise) witness ≤ 1) :
    BelowCeiling ceiling
      (covarianceMatrix E (addRankOneSignal noise factor scale loading)) := by
  rw [covarianceMatrix_addRankOneSignal E noise factor scale loading hfactor hleft hright]
  exact (belowCeiling_add_rankOne_iff hsymm hgap hwitness scale).mpr hthreshold

end Headroom

section StationaryLD

/-!
## Stationary LD along a chromosome: symbol, hard edge, whitening gain

The rigidity that blocks imitation in the previous section is stationarity, and
for genotypes stationarity has a name: LD that depends on separation between
sites rather than on their absolute positions. The first-order Markov model of
LD along a chromosome — correlation `ρ^d` at separation `d`, the discrete
analogue of the Ohta–Kimura decay in `Calibrator.LDDecayTheory` — makes the
variant covariance a Toeplitz kernel, and every quantity the detection
literature phrases in terms of "the spectrum of the LD matrix" becomes an
explicit function of one scalar.

The three quantities are the symbol (the LD spectral density), its minimum (the
hard edge, which controls the conditioning of any whitening step), and its
harmonic mean (the whitening gain, which is the per-variant limit of
`tr K⁻¹`, the quantity every whitened detection threshold is stated in).
-/

/-- **Correlation between two variants at a given separation** under a
first-order Markov model of LD along a chromosome.

Empirical status: DERIVED. This is the discrete-separation analogue of the
Ohta–Kimura law `ldAfterGenerations`, with separation in place of elapsed
generations; `stationaryLDEntry_eq_ldAfterGenerations` below is the statement
relating the two. Whether a real chromosome's LD is Markov at the scale of
interest is exactly what the symbol analysis below can be falsified against. -/
def stationaryLDEntry (decay : ℝ) (separation : ℕ) : ℝ := decay ^ separation

/-- **One site of propagation along the chromosome.**

The first-order Markov model is a *process*, and `stationaryLDEntry` is its
stationary correlation sequence rather than a stipulated formula.  Given a
candidate correlation sequence `c`, one step of the model produces the sequence
whose value at separation `0` is the normalisation `c(0) = 1` — a site is
perfectly correlated with itself — and whose value at separation `d + 1` is
`decay * c d`, the Chapman–Kolmogorov relation for a chain whose one-site
transmission coefficient is `decay`.

Composition convention: separation is measured in sites, and the coefficient
`decay` is the *per-site* retention, applied once per step.  Reading `decay` as
a per-generation retention instead gives a numerically different kernel; that
reading is `ldAfterGenerations`, and
`stationaryLDEntry_eq_ldAfterGenerations` is the bridge between them.

Empirical status: UNTESTED. -/
def markovLDStep (decay : ℝ) (c : ℕ → ℝ) (separation : ℕ) : ℝ :=
  if separation = 0 then 1 else decay * c (separation - 1)

/-- **The geometric sequence is the stationary point of Markov propagation.**

This is the theorem that makes `decay ^ separation` derived rather than
asserted: it is the unique normalised sequence returned unchanged by
`markovLDStep`, so no other decay law can be substituted into the symbol,
hard-edge and whitening-gain results that follow. -/
theorem stationaryLDEntry_isFixedPoint (decay : ℝ) (separation : ℕ) :
    markovLDStep decay (stationaryLDEntry decay) separation =
      stationaryLDEntry decay separation := by
  cases separation with
  | zero => simp [markovLDStep, stationaryLDEntry]
  | succ n =>
      have hne : (n + 1 : ℕ) ≠ 0 := Nat.succ_ne_zero n
      simp only [markovLDStep, stationaryLDEntry, if_neg hne, Nat.add_sub_cancel]
      ring

/-- **The independent-sites boundary is attained.**  At `decay = 0` the kernel
is exactly the identity: every off-diagonal correlation is `0`, not merely
small.  This is the regime in which whitening is free, and a decay law that
could never reach it would be qualitatively wrong about it. -/
theorem stationaryLDEntry_of_no_decay (separation : ℕ) (h : separation ≠ 0) :
    stationaryLDEntry 0 separation = 0 := by
  unfold stationaryLDEntry
  exact zero_pow h

/-- **The complete-LD boundary is attained.**  At `decay = 1` every pair of
sites is perfectly correlated at every separation, the kernel is the all-ones
matrix, and the hard edge `ldHardEdge 1 = 0` is exactly zero: whitening is not
merely ill-conditioned but undefined. -/
theorem stationaryLDEntry_of_complete_ld (separation : ℕ) :
    stationaryLDEntry 1 separation = 1 := by
  unfold stationaryLDEntry
  exact one_pow separation

/-- **Symbol (spectral density) of the stationary LD kernel.** The Poisson
kernel: the Fourier transform of the geometric correlation sequence. Its values
are the limiting eigenvalues of the LD matrix, so the symbol replaces every
appeal to unknown spectral data.

Empirical status: DERIVED from `stationaryLDEntry` by summation of the
two-sided geometric series; the identities below are proved, not fitted. -/
def ldKernelSymbol (decay angle : ℝ) : ℝ :=
  (1 - decay ^ 2) / (1 - 2 * decay * Real.cos angle + decay ^ 2)

/-- **Hard edge of the LD spectrum**: the smallest limiting eigenvalue of the
stationary LD matrix, attained at the highest frequency. It is the conditioning
bottleneck of any whitening or LD-pruning step.

Empirical status: DERIVED. `ldKernelSymbol_ge_hardEdge` proves it is a lower
bound and `ldKernelSymbol_pi` proves it is attained. -/
def ldHardEdge (decay : ℝ) : ℝ := (1 - decay) / (1 + decay)

/-- **Whitening gain**: the per-variant limit of `tr K⁻¹` for the stationary LD
kernel, equal to the harmonic mean of the symbol. Every whitened detection
threshold in the second-moment-shift program is stated in terms of this
quantity, which is otherwise treated as unknown.

Empirical status: DERIVED. `ldKernelSymbol_harmonicMean` proves the identity
with the symbol integral, and `ldPrecisionTrace_div_sites_tendsto` proves it is
the per-variant limit of the exact finite-chromosome trace. -/
def ldWhiteningGain (decay : ℝ) : ℝ := (1 + decay ^ 2) / (1 - decay ^ 2)

theorem stationaryLDEntry_eq_ldAfterGenerations (r Ne : ℝ) (separation : ℕ) :
    stationaryLDEntry (ldRetentionPerGen r Ne) separation =
      ldAfterGenerations 1 r Ne separation := by
  unfold stationaryLDEntry ldAfterGenerations
  rw [one_mul]

theorem ldKernelSymbol_denom_pos {decay angle : ℝ} (hd : |decay| < 1) :
    0 < 1 - 2 * decay * Real.cos angle + decay ^ 2 := by
  have hcos_le : Real.cos angle ≤ 1 := Real.cos_le_one angle
  have hcos_ge : -1 ≤ Real.cos angle := Real.neg_one_le_cos angle
  have habs : |decay| < 1 := hd
  have h1 : decay ≤ |decay| := le_abs_self decay
  have h2 : -|decay| ≤ decay := neg_abs_le decay
  nlinarith [sq_nonneg (1 - |decay|), sq_nonneg (decay - Real.cos angle),
    abs_nonneg decay, sq_abs decay,
    mul_nonneg (abs_nonneg decay) (sub_nonneg.mpr hcos_le),
    mul_nonneg (abs_nonneg decay) (sub_nonneg.mpr (neg_le_iff_add_nonneg.mp hcos_ge))]

theorem ldKernelSymbol_pos {decay angle : ℝ} (hd : |decay| < 1) :
    0 < ldKernelSymbol decay angle := by
  unfold ldKernelSymbol
  have hnum : 0 < 1 - decay ^ 2 := by
    have := sq_abs decay
    nlinarith [abs_nonneg decay, hd]
  exact div_pos hnum (ldKernelSymbol_denom_pos hd)

/-- The symbol attains the hard edge at the highest frequency. -/
theorem ldKernelSymbol_pi {decay : ℝ} (hd : |decay| < 1) :
    ldKernelSymbol decay Real.pi = ldHardEdge decay := by
  unfold ldKernelSymbol ldHardEdge
  rw [Real.cos_pi]
  have hne : (1 : ℝ) + decay ≠ 0 := by
    have h2 : -|decay| ≤ decay := neg_abs_le decay
    have : -1 < decay := by cases abs_lt.mp hd with | intro hlo _ => exact hlo
    linarith
  have hden : 1 - 2 * decay * (-1) + decay ^ 2 = (1 + decay) ^ 2 := by ring
  rw [hden]
  field_simp [hne]
  ring

/-- **The hard edge is a lower bound on the whole LD spectrum.** No direction in
variant space is worse conditioned than `(1-ρ)/(1+ρ)`; the entire hard-edge
question for a stationary LD kernel is the minimum of one explicit function. -/
theorem ldKernelSymbol_ge_hardEdge {decay angle : ℝ} (hd : |decay| < 1)
    (hnonneg : 0 ≤ decay) :
    ldHardEdge decay ≤ ldKernelSymbol decay angle := by
  unfold ldHardEdge ldKernelSymbol
  have hden : 0 < 1 - 2 * decay * Real.cos angle + decay ^ 2 :=
    ldKernelSymbol_denom_pos (decay := decay) (angle := angle) hd
  have hplus : 0 < 1 + decay := by
    have : -1 < decay := by cases abs_lt.mp hd with | intro hlo _ => exact hlo
    linarith
  have hcos_ge : -1 ≤ Real.cos angle := Real.neg_one_le_cos angle
  have hminus : 0 ≤ 1 - decay := by
    have hlt : decay < 1 := (abs_lt.mp hd).2
    linarith
  have hfactor :
      0 ≤ (1 - decay) * (2 * decay * (1 + Real.cos angle)) := by
    exact mul_nonneg hminus
      (mul_nonneg (mul_nonneg (by norm_num) hnonneg) (by linarith))
  rw [div_le_div_iff₀ hplus hden, ← sub_nonneg]
  have hgap : (1 - decay ^ 2) * (1 + decay) -
      (1 - decay) * (1 - 2 * decay * Real.cos angle + decay ^ 2) =
      (1 - decay) * (2 * decay * (1 + Real.cos angle)) := by ring
  rw [hgap]
  exact hfactor

/-- **The whitening gain is the harmonic mean of the LD spectrum.** This is the
Szegő value of `tr K⁻¹` per variant, computed in closed form: the quantity that
detection thresholds are stated in but never evaluated. -/
theorem ldKernelSymbol_harmonicMean {decay : ℝ} (hd : |decay| < 1) :
    (∫ angle in (0 : ℝ)..(2 * Real.pi), (ldKernelSymbol decay angle)⁻¹) =
      2 * Real.pi * ldWhiteningGain decay := by
  have hnum : (0 : ℝ) < 1 - decay ^ 2 := by
    have := sq_abs decay
    nlinarith [abs_nonneg decay, hd]
  have hpoint : ∀ angle : ℝ, (ldKernelSymbol decay angle)⁻¹ =
      ((1 + decay ^ 2) - 2 * decay * Real.cos angle) / (1 - decay ^ 2) := by
    intro angle
    unfold ldKernelSymbol
    rw [inv_div]
    ring_nf
  simp only [hpoint]
  rw [intervalIntegral.integral_div,
    intervalIntegral.integral_sub intervalIntegrable_const
      ((continuous_const.mul Real.continuous_cos).intervalIntegrable _ _),
    intervalIntegral.integral_const_mul, integral_cos,
    intervalIntegral.integral_const]
  rw [Real.sin_two_pi, Real.sin_zero]
  unfold ldWhiteningGain
  simp only [smul_eq_mul]
  field_simp
  ring

theorem ldWhiteningGain_ge_one {decay : ℝ} (hd : |decay| < 1) :
    1 ≤ ldWhiteningGain decay := by
  unfold ldWhiteningGain
  have hnum : (0 : ℝ) < 1 - decay ^ 2 := by
    have := sq_abs decay
    nlinarith [abs_nonneg decay, hd]
  rw [le_div_iff₀ hnum]
  nlinarith [sq_nonneg decay]

/-- Stronger LD means a larger whitening gain: whitening has more to exploit
when neighbouring variants are more correlated. -/
theorem ldWhiteningGain_strictMono {decay₁ decay₂ : ℝ}
    (h₁ : 0 ≤ decay₁) (h₂ : |decay₂| < 1) (hlt : decay₁ < decay₂) :
    ldWhiteningGain decay₁ < ldWhiteningGain decay₂ := by
  unfold ldWhiteningGain
  have hd2 : (0 : ℝ) < 1 - decay₂ ^ 2 := by
    have := sq_abs decay₂
    nlinarith [abs_nonneg decay₂, h₂]
  have hd1 : (0 : ℝ) < 1 - decay₁ ^ 2 := by nlinarith [h₁, hlt, hd2]
  rw [div_lt_div_iff₀ hd1 hd2]
  nlinarith [hlt, h₁, sq_nonneg (decay₂ - decay₁)]

/-- **Recombination sets the whitening gain.** Tying the stationary kernel's
decay parameter to the Ohta–Kimura retention factor of
`Calibrator.LDDecayTheory` makes the detection-relevant spectral quantity an
explicit function of the recombination rate and the effective population size:
less recombination, more gain. -/
theorem ldWhiteningGain_of_ldRetention_antitone
    {r₁ r₂ Ne : ℝ} (hr₁ : 0 ≤ r₁) (hr₂ : r₂ < 1) (hNe : 1 < Ne) (hlt : r₁ < r₂) :
    ldWhiteningGain (ldRetentionPerGen r₂ Ne) <
      ldWhiteningGain (ldRetentionPerGen r₁ Ne) := by
  have hret₂ : 0 ≤ ldRetentionPerGen r₂ Ne :=
    ld_retention_nonneg r₂ Ne (by linarith) (le_of_lt hr₂) (le_of_lt hNe)
  have hlt' : ldRetentionPerGen r₂ Ne < ldRetentionPerGen r₁ Ne := by
    unfold ldRetentionPerGen
    have hfac : 0 < 1 - 1 / (2 * Ne) := by
      rw [sub_pos, div_lt_one (by linarith)]; linarith
    nlinarith [hlt, hfac]
  have hone : ldRetentionPerGen r₁ Ne < 1 := by
    rcases eq_or_lt_of_le hr₁ with hzero | hpos
    · unfold ldRetentionPerGen
      rw [← hzero]
      have hfac : 1 - 1 / (2 * Ne) < 1 := by
        have : 0 < 1 / (2 * Ne) := by positivity
        linarith
      nlinarith [hfac]
    · exact ld_retention_lt_one r₁ Ne hpos (by linarith) hNe
  have habs : |ldRetentionPerGen r₁ Ne| < 1 := by
    rw [abs_lt]
    constructor
    · nlinarith [ld_retention_nonneg r₁ Ne hr₁ (by linarith) (le_of_lt hNe)]
    · exact hone
  exact ldWhiteningGain_strictMono hret₂ habs hlt'

/-- **Exact whitening cost of a finite chromosome**: `tr K⁻¹` for the
stationary LD kernel on `nSites` variants, in closed form at every finite size
rather than only in the limit.

Empirical status: DERIVED from the first-order Markov structure — one
unconstrained variant plus `nSites - 1` variants each whitened against its
neighbour, which is the content of `ldPrecisionTrace_eq_boundary_add_interior`.
The stencil identities below verify both boundary and interior rows of the
tridiagonal inverse at every separation.  The Python validation remains an
independent numerical check, not part of the proof. -/
def ldPrecisionTrace (decay : ℝ) (nSites : ℕ) : ℝ :=
  ((nSites : ℝ) * (1 + decay ^ 2) - 2 * decay ^ 2) / (1 - decay ^ 2)

/-- Separation from a boundary row to the adjacent row.  At the diagonal the
adjacent entry is one step away; off the diagonal at separation `d+1`, it is
at separation `d`. -/
def adjacentBoundarySeparation : ℕ → ℕ
  | 0 => 1
  | d + 1 => d

/-- **Exact boundary-row inverse identity.**  The endpoint precision stencil
`[1, -ρ]` annihilates every off-diagonal geometric-correlation entry and
returns `1-ρ²` on the diagonal.  This closes the boundary case omitted by the
interior three-term calculation. -/
theorem stationaryLD_boundary_stencil (decay : ℝ) (separation : ℕ) :
    stationaryLDEntry decay separation -
        decay * stationaryLDEntry decay (adjacentBoundarySeparation separation) =
      if separation = 0 then 1 - decay ^ 2 else 0 := by
  cases separation with
  | zero =>
      simp [adjacentBoundarySeparation, stationaryLDEntry]
      ring
  | succ d =>
      simp [adjacentBoundarySeparation, stationaryLDEntry, pow_succ, mul_comm]

/-- **Interior three-term identity.** Away from the ends of the chromosome the
geometric LD sequence is annihilated by the tridiagonal AR(1) precision
stencil: this is why the inverse of a stationary LD matrix is banded, and hence
why whitening is a local operation on the genome rather than a global one. -/
theorem stationaryLD_three_term (decay : ℝ) (separation : ℕ) (h : 1 ≤ separation) :
    (1 + decay ^ 2) * stationaryLDEntry decay separation
      - decay * stationaryLDEntry decay (separation - 1)
      - decay * stationaryLDEntry decay (separation + 1) = 0 := by
  obtain ⟨e, rfl⟩ := Nat.exists_eq_add_of_le h
  unfold stationaryLDEntry
  simp only [Nat.add_sub_cancel_left, pow_add, pow_succ]
  ring

/-- The same stencil applied at zero separation returns the whitening constant
`1 - ρ²`: the diagonal of the identity, and the origin of the whitening gain. -/
theorem stationaryLD_three_term_diagonal (decay : ℝ) :
    (1 + decay ^ 2) * stationaryLDEntry decay 0
      - decay * stationaryLDEntry decay 1
      - decay * stationaryLDEntry decay 1 = 1 - decay ^ 2 := by
  unfold stationaryLDEntry
  ring

/-- **Complete interior-row inverse identity.**  Combining the diagonal and
off-diagonal calculations gives the tridiagonal precision stencil against an
arbitrary kernel column.  It equals `(1-ρ²)I` pointwise, with no unproved
boundary or distance case left over. -/
theorem stationaryLD_interior_stencil (decay : ℝ) (separation : ℕ) :
    (1 + decay ^ 2) * stationaryLDEntry decay separation
        - decay * stationaryLDEntry decay (adjacentBoundarySeparation separation)
        - decay * stationaryLDEntry decay (separation + 1) =
      if separation = 0 then 1 - decay ^ 2 else 0 := by
  cases separation with
  | zero =>
      have hif : (if (0 : ℕ) = 0 then 1 - decay ^ 2 else 0) = 1 - decay ^ 2 :=
        if_pos rfl
      rw [hif]
      exact stationaryLD_three_term_diagonal decay
  | succ d =>
      have hpos : 1 ≤ d + 1 := Nat.succ_le_succ (Nat.zero_le d)
      simpa using stationaryLD_three_term decay (d + 1) hpos

/-- **The whitening cost decomposes into one boundary variant plus interior
variants.** Each interior variant contributes exactly the whitening gain; the
first variant, having no left neighbour to be whitened against, contributes
one. This is the finite-chromosome correction that the limit hides. -/
theorem ldPrecisionTrace_eq_boundary_add_interior {decay : ℝ} (hd : |decay| < 1)
    (nSites : ℕ) (_hsites : 1 ≤ nSites) :
    ldPrecisionTrace decay nSites =
      1 + ((nSites : ℝ) - 1) * ldWhiteningGain decay := by
  have hne : (1 : ℝ) - decay ^ 2 ≠ 0 := by
    have := sq_abs decay
    nlinarith [abs_nonneg decay, hd]
  unfold ldPrecisionTrace ldWhiteningGain
  field_simp
  ring

/-- **The whitening gain is the per-variant limit of the whitening cost.** The
quantity that detection thresholds are stated in is the large-chromosome limit
of an exactly computable finite-size quantity. -/
theorem ldPrecisionTrace_div_sites_tendsto {decay : ℝ} (hd : |decay| < 1) :
    Filter.Tendsto (fun nSites : ℕ => ldPrecisionTrace decay nSites / (nSites : ℝ))
      Filter.atTop (nhds (ldWhiteningGain decay)) := by
  have hne : (1 : ℝ) - decay ^ 2 ≠ 0 := by
    have := sq_abs decay
    nlinarith [abs_nonneg decay, hd]
  have heq : (fun nSites : ℕ => ldPrecisionTrace decay nSites / (nSites : ℝ))
      =ᶠ[Filter.atTop] fun nSites : ℕ =>
        ldWhiteningGain decay + (1 - ldWhiteningGain decay) / (nSites : ℝ) := by
    filter_upwards [Filter.eventually_ge_atTop 1] with nSites hsites
    have hpos : (0 : ℝ) < (nSites : ℝ) := by
      exact_mod_cast Nat.lt_of_lt_of_le Nat.zero_lt_one hsites
    rw [ldPrecisionTrace_eq_boundary_add_interior hd nSites hsites]
    field_simp
    ring
  have hzero : Filter.Tendsto
      (fun nSites : ℕ => (1 - ldWhiteningGain decay) / (nSites : ℝ))
      Filter.atTop (nhds 0) := tendsto_const_div_atTop_nhds_zero_nat _
  apply (Filter.tendsto_congr' heq).mpr
  simpa using tendsto_const_nhds.add hzero

end StationaryLD

section Spectator

/-!
## The evaluation geometry is a spectator; ancestry heterogeneity is not

For ridge-penalized polygenic prediction the limiting risk is controlled by a
single scalar fixed point determined by the *design* — the genotype covariance
of the training sample, i.e. its LD and ancestry structure. The geometry of the
loss, which for portability work is the target population's own covariance, is
a test functional applied afterwards: it never multiplies the randomness and
never enters the fixed point. Whether the training and target covariances
commute, or are in general position, is therefore irrelevant to whether the
theory is scalar.

What does break scalarity lives inside the design: if individuals do not share
one genotype covariance — an admixed or ancestry-heterogeneous training
sample — the single scalar is replaced by one scalar per ancestry profile, and
they are provably distinct.
-/

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- Excess risk read off a deterministic equivalent: a linear functional of the
evaluation geometry. -/
def lossGeometryRisk (B M : Matrix ι ι ℝ) : ℝ := Matrix.trace (B * M)

theorem lossGeometryRisk_add (B₁ B₂ M : Matrix ι ι ℝ) :
    lossGeometryRisk (B₁ + B₂) M = lossGeometryRisk B₁ M + lossGeometryRisk B₂ M := by
  unfold lossGeometryRisk
  rw [Matrix.add_mul, Matrix.trace_add]

theorem lossGeometryRisk_smul (c : ℝ) (B M : Matrix ι ι ℝ) :
    lossGeometryRisk (c • B) M = c * lossGeometryRisk B M := by
  unfold lossGeometryRisk
  rw [Matrix.smul_mul, Matrix.trace_smul, smul_eq_mul]

/-- **The deterministic equivalent lies in the algebra of the design.** Whatever
the evaluation geometry, the equivalent commutes with the training genotype
covariance. The loss geometry cannot enter it, which is the precise sense in
which the joint geometry of (design, loss) is irrelevant. -/
theorem deterministicEquivalent_commutes_design
    (A M : Matrix ι ι ℝ) (shrink ridge : ℝ)
    (hinv : M * (shrink • A + ridge • (1 : Matrix ι ι ℝ)) = 1) :
    M * A = A * M := by
  set X : Matrix ι ι ℝ := shrink • A + ridge • (1 : Matrix ι ι ℝ) with hX
  have hXA : A * X = X * A := by
    rw [hX, Matrix.mul_add, Matrix.add_mul, Matrix.mul_smul, Matrix.smul_mul,
      Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_one, Matrix.one_mul]
  have hleft : X * M = 1 := Matrix.mul_eq_one_comm.mp hinv
  calc M * A = M * A * (X * M) := by rw [hleft, Matrix.mul_one]
    _ = M * (A * X) * M := by rw [Matrix.mul_assoc, Matrix.mul_assoc, Matrix.mul_assoc]
    _ = M * (X * A) * M := by rw [hXA]
    _ = (M * X) * (A * M) := by
        rw [Matrix.mul_assoc, Matrix.mul_assoc, Matrix.mul_assoc]
    _ = A * M := by rw [hinv, Matrix.one_mul]

/-- The self-consistency equation of the ridge deterministic equivalent, in the
variable `u = 1 + δ`. The left side is the increasing part, the right side the
LD-dependent decreasing part, and a solution is exactly a fixed point of the
usual equation. The evaluation geometry does not appear.

`aspect` is the variants-per-individual ratio of the training sample. It is not
optional: the fixed point is a functional of the design *and its aspect ratio*,
and dropping it — the first version of this definition did — misprices the
resolvent functional by 34 percent at `aspect = 0.3`, as
`proofs/validation/imitation_rigidity/check_imitation.py` records.

Empirical status: VALIDATED. Simulated ridge regression on genotype-like
designs matches `tr(B (S + ridge)⁻¹)/k` computed from this fixed point, for
evaluation geometries that commute with the design and for ones in general
position alike. -/
def ridgeBalance (aspect : ℝ) (eig : ι → ℝ) (ridge u : ℝ) : ℝ :=
  (1 - 1 / u) -
    aspect * ((∑ i, eig i / (eig i + ridge * u)) / (Fintype.card ι : ℝ))

/-- **The self-consistency equation read as a one-step map.**

`ridgeBalance` is the residual of the equation `1 - 1/u = A(u)`, where
`A(u) = aspect · mean_i eig_i/(eig_i + ridge·u)` is the resolvent functional of
the training spectrum.  Solving that equation for the `u` on the *left* gives
`u = 1/(1 - A(u))`, which is the map below: from a candidate `u` it recomputes
the resolvent functional and returns the `u` that functional implies.  A root
of `ridgeBalance` and a fixed point of this map are the same thing, which
`ridgeBalance_root_isFixedPoint` proves.

Composition convention: the resolvent is evaluated at the *current* iterate and
the reciprocal is taken afterwards.  The reversed arrangement — solving for the
`u` inside the resolvent instead — is a different iteration with the same roots
but different convergence behaviour, so this is part of the process rather than
of its presentation.

Empirical status: UNTESTED as an iteration; the root it characterises is the
VALIDATED quantity recorded on `ridgeBalance`. -/
def ridgeSelfConsistentStep (aspect : ℝ) (eig : ι → ℝ) (ridge u : ℝ) : ℝ :=
  1 / (1 - aspect * ((∑ i, eig i / (eig i + ridge * u)) / (Fintype.card ι : ℝ)))

/-- The scalar content of the ridge balance equation, with the spectral
functional abstracted to a single real `A`. -/
private theorem ridge_root_iff_aux (A u : ℝ) (hu : u ≠ 0) :
    (1 - 1 / u) - A = 0 ↔ 1 / (1 - A) = u := by
  constructor
  · intro h
    have hinv : 1 - A = 1 / u := by linarith
    rw [hinv, one_div_one_div]
  · intro h
    by_cases hA : 1 - A = 0
    · rw [hA, div_zero] at h
      exact absurd h.symm hu
    · have hinv : 1 - A = 1 / u := by rw [← h, one_div_one_div]
      linarith

/-- **The ridge balance root is a fixed point of a process.**

The deterministic equivalent is not a stipulated closed form — there is no
closed form — but it is also not merely "the zero of some function": it is the
rest point of the resolvent iteration, and this equivalence is what licenses
reading `ridgeBalance_root_unique` as uniqueness of a *state* of the model.
Only `u ≠ 0` is needed; the degenerate case `A = 1`, where the map returns `0`,
is excluded on both sides at once. -/
theorem ridgeBalance_root_isFixedPoint (aspect : ℝ) (eig : ι → ℝ) (ridge u : ℝ)
    (hu : u ≠ 0) :
    ridgeBalance aspect eig ridge u = 0 ↔
      ridgeSelfConsistentStep aspect eig ridge u = u := by
  unfold ridgeBalance ridgeSelfConsistentStep
  exact ridge_root_iff_aux _ u hu

/-- **The no-shrinkage boundary is attained exactly.**  With `aspect = 0` — an
infinitely long training sample, no variants-per-individual pressure — the
resolvent functional vanishes and the fixed point is exactly `u = 1`, i.e.
`δ = 0`: ridge regression at its unregularised-variance limit, with no
inflation at all.  The iteration reaches this boundary rather than approaching
it. -/
@[simp] theorem ridgeSelfConsistentStep_of_zero_aspect (eig : ι → ℝ) (ridge u : ℝ) :
    ridgeSelfConsistentStep 0 eig ridge u = 1 := by
  unfold ridgeSelfConsistentStep
  norm_num

/-- At `aspect = 0` the balance equation has `u = 1` as its root, matching the
boundary value of the map. -/
theorem ridgeBalance_of_zero_aspect (eig : ι → ℝ) (ridge : ℝ) :
    ridgeBalance 0 eig ridge 1 = 0 := by
  unfold ridgeBalance
  norm_num

theorem ridgeBalance_strictMonoOn (aspect : ℝ) (eig : ι → ℝ) (ridge : ℝ)
    (haspect : 0 ≤ aspect) (heig : ∀ i, 0 ≤ eig i) (hridge : 0 < ridge) :
    StrictMonoOn (ridgeBalance aspect eig ridge) (Set.Ici (1 : ℝ)) := by
  intro u hu w hw hlt
  have hu1 : (1 : ℝ) ≤ u := hu
  have hw1 : (1 : ℝ) ≤ w := hw
  have hupos : (0 : ℝ) < u := lt_of_lt_of_le zero_lt_one hu1
  have hwpos : (0 : ℝ) < w := lt_of_lt_of_le zero_lt_one hw1
  have hleft : 1 - 1 / u < 1 - 1 / w := by
    have : 1 / w < 1 / u := by
      exact one_div_lt_one_div_of_lt hupos hlt
    linarith
  have hright : ∀ i, eig i / (eig i + ridge * w) ≤ eig i / (eig i + ridge * u) := by
    intro i
    rcases eq_or_lt_of_le (heig i) with hzero | hpos
    · rw [← hzero]; simp
    · have hdu : 0 < eig i + ridge * u := by positivity
      have hdw : 0 < eig i + ridge * w := by positivity
      apply div_le_div_of_nonneg_left (le_of_lt hpos) hdu
      nlinarith [hlt, hridge]
  have hsum : (∑ i, eig i / (eig i + ridge * w)) ≤ ∑ i, eig i / (eig i + ridge * u) :=
    Finset.sum_le_sum (fun i _ => hright i)
  unfold ridgeBalance
  rcases Nat.eq_zero_or_pos (Fintype.card ι) with hcard | hcard
  · rw [hcard]; simpa using hleft
  · have hcardpos : (0 : ℝ) < (Fintype.card ι : ℝ) := by exact_mod_cast hcard
    have hdiv :
        (∑ i, eig i / (eig i + ridge * w)) / (Fintype.card ι : ℝ) ≤
          (∑ i, eig i / (eig i + ridge * u)) / (Fintype.card ι : ℝ) :=
      div_le_div_of_nonneg_right hsum hcardpos.le
    have hscaled :
        aspect * ((∑ i, eig i / (eig i + ridge * w)) / (Fintype.card ι : ℝ)) ≤
          aspect * ((∑ i, eig i / (eig i + ridge * u)) / (Fintype.card ι : ℝ)) :=
      mul_le_mul_of_nonneg_left hdiv haspect
    linarith

/-- **Uniqueness of the ridge fixed point.** The scalar that every ridge-PGS
risk formula depends on is well defined: there is at most one, and it is a
functional of the training genotype spectrum and aspect ratio alone. -/
theorem ridgeBalance_root_unique (aspect : ℝ) (eig : ι → ℝ) (ridge : ℝ)
    (haspect : 0 ≤ aspect) (heig : ∀ i, 0 ≤ eig i) (hridge : 0 < ridge)
    {u w : ℝ} (hu : 1 ≤ u) (hw : 1 ≤ w)
    (hru : ridgeBalance aspect eig ridge u = 0)
    (hrw : ridgeBalance aspect eig ridge w = 0) :
    u = w := by
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hgt
  · have := ridgeBalance_strictMonoOn aspect eig ridge haspect heig hridge hu hw hlt
    rw [hru, hrw] at this
    exact lt_irrefl 0 this
  · have := ridgeBalance_strictMonoOn aspect eig ridge haspect heig hridge hw hu hgt
    rw [hru, hrw] at this
    exact lt_irrefl 0 this

/-- **Ancestry heterogeneity breaks scalarity.** With two ancestry groups whose
genotype covariances differ in the functional the fixed point sees, the two
group-level scalars cannot coincide: no single scalar equivalent exists, and the
theory becomes function-valued in the ancestry profile. This is the boundary of
the scalar theory, and it lies inside the design, not between design and loss. -/
theorem ancestry_profile_scalars_differ
    {profileMap : ℝ → ℝ → ℝ} {scale₁ scale₂ η₁ η₂ : ℝ}
    (hmono : ∀ {a b c : ℝ}, a < b → profileMap a c < profileMap b c)
    (hscale : scale₁ < scale₂)
    (hshared : ℝ)
    (h₁ : η₁ = profileMap scale₁ hshared)
    (h₂ : η₂ = profileMap scale₂ hshared) :
    η₁ ≠ η₂ := by
  rw [h₁, h₂]
  exact ne_of_lt (hmono hscale)

end Spectator

section AbsorbingBoundary

/-!
## Information at an absorbing boundary: allele loss

An allele's frequency under neutral drift is a diffusion whose noise vanishes at
the boundary, and the boundary absorbs: the allele is lost. The transition law
is therefore not absolutely continuous — it has an atom at zero whose mass is
the loss probability — and this is the situation in which local asymptotic
normality is usually said to fail.

It does not fail. The atom is smooth in the parameter, so the square root of
the atom mass is differentiable and contributes an ordinary Fisher information
term. The loss/no-loss status of a variant is *information about its ancestral
frequency*, on the same footing as the observed frequency of the variants that
survive, and the two channels cross at a computable time.
-/

/-- **Probability that a neutral allele has been lost by time `t`**, started
from scaled initial frequency `x`: the absorbed mass of the boundary-degenerate
diffusion.

Empirical status: DERIVED for the squared-Bessel representative of neutral
drift with an absorbing boundary; it is the exponential absorption law, and the
identities below are proved from it rather than fitted. Its use as a model of a
real allele requires the diffusion approximation, which is standard and is not
re-derived here. -/
def alleleLossProbability (initial time : ℝ) : ℝ :=
  Real.exp (-(initial / (2 * time)))

/-- **Fisher information carried by the loss/no-loss status alone**: the
absorption channel. -/
def absorptionInformation (initial time : ℝ) : ℝ :=
  alleleLossProbability initial time / (4 * time ^ 2)

theorem alleleLossProbability_pos (initial time : ℝ) :
    0 < alleleLossProbability initial time := Real.exp_pos _

theorem alleleLossProbability_le_one {initial time : ℝ}
    (hinitial : 0 ≤ initial) (htime : 0 < time) :
    alleleLossProbability initial time ≤ 1 := by
  unfold alleleLossProbability
  rw [Real.exp_le_one_iff]
  have : 0 ≤ initial / (2 * time) := by positivity
  linarith

/-- The absorbed mass is differentiable in the ancestral frequency: the atom is
not an irregularity. -/
theorem hasDerivAt_alleleLossProbability (time initial : ℝ) :
    HasDerivAt (fun x => alleleLossProbability x time)
      (-(1 / (2 * time)) * alleleLossProbability initial time) initial := by
  have hbase : HasDerivAt (fun x : ℝ => -(x / (2 * time))) (-(1 / (2 * time))) initial := by
    have := ((hasDerivAt_id initial).div_const (2 * time)).neg
    simpa using this
  simpa [alleleLossProbability, one_div, mul_comm, mul_left_comm, mul_assoc] using hbase.exp

/-- The square-root mass itself is differentiable.  This is the actual
quadratic-mean derivative of the atomic coordinate, rather than merely a
formal Fisher-information calculation performed after the fact. -/
theorem hasDerivAt_sqrt_alleleLossProbability {time : ℝ}
    (htime : time ≠ 0) (initial : ℝ) :
    HasDerivAt (fun x => Real.sqrt (alleleLossProbability x time))
      (-(1 / (4 * time)) * Real.sqrt (alleleLossProbability initial time)) initial := by
  have hp : 0 < alleleLossProbability initial time :=
    alleleLossProbability_pos initial time
  have hsqrt := (hasDerivAt_alleleLossProbability time initial).sqrt hp.ne'
  convert hsqrt using 1
  have hsqrtPos : 0 < Real.sqrt (alleleLossProbability initial time) :=
    Real.sqrt_pos.2 hp
  have hsquare :
      Real.sqrt (alleleLossProbability initial time) ^ 2 =
        alleleLossProbability initial time := Real.sq_sqrt hp.le
  field_simp [htime, hsqrtPos.ne']
  nlinarith [hsquare]

/-- **Quadratic-mean differentiability tolerates the atom.** The square root of
the absorbed mass is smooth in the ancestral frequency, and four times its
squared derivative is exactly the absorption channel's Fisher information. The
atom contributes one ordinary coordinate to the local experiment; it does not
destroy local asymptotic normality. -/
theorem sqrt_alleleLoss_derivative_sq {initial time : ℝ} (htime : 0 < time) :
    4 * (-(1 / (4 * time)) * Real.sqrt (alleleLossProbability initial time)) ^ 2 =
      absorptionInformation initial time := by
  unfold absorptionInformation
  have hsq : Real.sqrt (alleleLossProbability initial time) ^ 2 =
      alleleLossProbability initial time := by
    rw [sq, Real.mul_self_sqrt (alleleLossProbability_pos initial time).le]
  have hne : time ≠ 0 := ne_of_gt htime
  calc
    4 * (-(1 / (4 * time)) * Real.sqrt (alleleLossProbability initial time)) ^ 2 =
        Real.sqrt (alleleLossProbability initial time) ^ 2 / (4 * time ^ 2) := by
          field_simp [hne]
    _ = alleleLossProbability initial time / (4 * time ^ 2) := by rw [hsq]

/-- Relative weight of the absorption channel against the diffusion channel,
whose information scale is of order `1 / (x t)`. -/
def absorptionChannelWeight (initial time : ℝ) : ℝ :=
  initial * alleleLossProbability initial time / (4 * time)

/-- **The information crossover time.** The absorption channel is dark at short
times (nothing has been lost yet) and dark again at long times (everything has),
and its weight against the diffusion channel peaks at half the scaled ancestral
frequency. Before that time the frequency of surviving variants carries the
information; after it, the pattern of losses does.

Empirical status: DERIVED from `alleleLossProbability`; the monotonicity
statements below are the proof that this is the maximizer. -/
def informationCrossoverTime (initial : ℝ) : ℝ := initial / 2

theorem hasDerivAt_absorptionChannelWeight {initial time : ℝ} (htime : 0 < time) :
    HasDerivAt (fun t => absorptionChannelWeight initial t)
      (initial * alleleLossProbability initial time *
        (initial / 2 - time) / (4 * time ^ 3)) time := by
  have hne : time ≠ 0 := ne_of_gt htime
  have hexp : HasDerivAt (fun t : ℝ => Real.exp (-(initial / (2 * t))))
      (Real.exp (-(initial / (2 * time))) * (initial / (2 * time ^ 2))) time := by
    have hinner : HasDerivAt (fun t : ℝ => -(initial / (2 * t)))
        (initial / (2 * time ^ 2)) time := by
      have hdiv : HasDerivAt (fun t : ℝ => initial / (2 * t))
          (-(initial * 2) / (2 * time) ^ 2) time := by
        have := (hasDerivAt_const time (2 : ℝ)).mul (hasDerivAt_id time)
        have hdenNe : (2 * time : ℝ) ≠ 0 := mul_ne_zero (by norm_num) hne
        simpa using
          ((hasDerivAt_const time initial).div (by simpa using this) hdenNe)
      have : HasDerivAt (fun t : ℝ => -(initial / (2 * t)))
          (-(-(initial * 2) / (2 * time) ^ 2)) time := hdiv.neg
      convert this using 1
      field_simp
    simpa [Real.exp_ne_zero] using hinner.exp
  have hquot : HasDerivAt (fun t : ℝ => Real.exp (-(initial / (2 * t))) / (4 * t))
      ((Real.exp (-(initial / (2 * time))) * (initial / (2 * time ^ 2)) * (4 * time) -
        Real.exp (-(initial / (2 * time))) * 4) / (4 * time) ^ 2) time := by
    have hden : HasDerivAt (fun t : ℝ => 4 * t) 4 time := by
      simpa using (hasDerivAt_id time).const_mul (4 : ℝ)
    exact hexp.div hden (by positivity)
  have hscaled := hquot.const_mul initial
  convert hscaled using 1
  · funext t
    unfold absorptionChannelWeight alleleLossProbability
    ring
  · unfold alleleLossProbability
    field_simp

/-- Before the crossover time the absorption channel is strictly gaining: as
time passes, the pattern of losses becomes progressively more informative about
the ancestral frequency. -/
theorem absorptionChannelWeight_strictMonoOn {initial : ℝ} (hinitial : 0 < initial) :
    StrictMonoOn (absorptionChannelWeight initial)
      (Set.Ioc 0 (informationCrossoverTime initial)) := by
  apply strictMonoOn_of_deriv_pos (convex_Ioc _ _)
  · intro t ht
    exact ((hasDerivAt_absorptionChannelWeight ht.1).differentiableAt.continuousAt).continuousWithinAt
  · intro t ht
    rw [interior_Ioc] at ht
    have htpos : 0 < t := ht.1
    have hlt : t < initial / 2 := by
      simpa [informationCrossoverTime] using ht.2
    rw [(hasDerivAt_absorptionChannelWeight htpos).deriv]
    have hp := alleleLossProbability_pos initial t
    have hnum : 0 < initial * alleleLossProbability initial t * (initial / 2 - t) := by
      have : 0 < initial / 2 - t := by linarith
      positivity
    have hden : 0 < 4 * t ^ 3 := by positivity
    exact div_pos hnum hden

/-- After the crossover time the absorption channel decays again: once most
copies are already lost, the losses stop discriminating between ancestral
frequencies. -/
theorem absorptionChannelWeight_strictAntiOn {initial : ℝ} (hinitial : 0 < initial) :
    StrictAntiOn (absorptionChannelWeight initial)
      (Set.Ici (informationCrossoverTime initial)) := by
  apply strictAntiOn_of_deriv_neg (convex_Ici _)
  · intro t ht
    have hcrossover : 0 < informationCrossoverTime initial := by
      simpa [informationCrossoverTime] using half_pos hinitial
    have htpos : 0 < t := lt_of_lt_of_le hcrossover ht
    exact ((hasDerivAt_absorptionChannelWeight htpos).differentiableAt.continuousAt).continuousWithinAt
  · intro t ht
    rw [interior_Ici] at ht
    have hgt : initial / 2 < t := by
      simpa [informationCrossoverTime] using ht
    have htpos : 0 < t := lt_trans (half_pos hinitial) hgt
    rw [(hasDerivAt_absorptionChannelWeight htpos).deriv]
    have hp := alleleLossProbability_pos initial t
    have hnum : initial * alleleLossProbability initial t * (initial / 2 - t) < 0 := by
      have hneg : initial / 2 - t < 0 := by linarith
      have hpos : 0 < initial * alleleLossProbability initial t := by positivity
      exact mul_neg_of_pos_of_neg hpos hneg
    have hden : 0 < 4 * t ^ 3 := by positivity
    exact div_neg_of_neg_of_pos hnum hden

end AbsorbingBoundary

section Unification

/-!
## Unification with the rest of the development

The results above are stated in their own vocabulary; this section connects
each of them to a quantity the rest of the corpus already reasons about, so
that a disagreement between them is a failed proof rather than two coexisting
answers.

* the imitation bump acts on the normal equations of `Calibrator.SecondMomentShift`
  through a single scalar, so a residual-score analysis cannot separate it from
  a background;
* whitening — the operation `Calibrator.WhiteningEquivalence` formalizes — maps
  the bump to another bump, which is why no whitening scheme escapes the
  identifiability wall;
* the dropout floor of the dead-sensor construction caps the fraction of
  individual-level variation that any group-level covariate can explain, which
  is the mechanism behind open question 1 of `Calibrator.OpenQuestions`.
-/

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The imitation bump acts on any weight vector through one scalar: the
projection of the weights on the signal direction. -/
theorem mulVec_add_rankOneCovarianceBump
    (K : Matrix ι ι ℝ) (scale : ℝ) (loading weights : ι → ℝ) :
    (K + rankOneCovarianceBump scale loading).mulVec weights =
      K.mulVec weights + (scale ^ 2 * dot loading weights) • loading := by
  funext i
  simp only [Matrix.mulVec, dotProduct, Matrix.add_apply, Pi.add_apply,
    rankOneCovarianceBump, Pi.smul_apply, smul_eq_mul, dot, add_mul]
  rw [Finset.sum_add_distrib]
  congr 1
  have hterm : ∀ j : ι,
      scale ^ 2 * loading i * loading j * weights j =
        (scale ^ 2 * loading i) * (loading j * weights j) := by
    intro j; ring
  simp_rw [hterm]
  rw [← Finset.mul_sum]
  ring

/-- **The imitation is invisible to the normal equations of a score orthogonal
to the signal.** The second-moment matrix of `Calibrator.SecondMomentShift`
moves by a rank-one term, so a deployed polygenic score uncorrelated with the
signal direction sees no change at all: the two experiments agree exactly on
everything that score can measure. -/
theorem secondMoment_imitation_shift
    {Ω : Type*} (E : ExpFunctional Ω) (X : Ω → ι → ℝ)
    (scale : ℝ) (loading weights : ι → ℝ) :
    (secondMomentMatrix E X + rankOneCovarianceBump scale loading).mulVec weights =
      (secondMomentMatrix E X).mulVec weights +
        (scale ^ 2 * dot loading weights) • loading :=
  mulVec_add_rankOneCovarianceBump (secondMomentMatrix E X) scale loading weights

theorem secondMoment_imitation_invisible_to_orthogonal_score
    {Ω : Type*} (E : ExpFunctional Ω) (X : Ω → ι → ℝ)
    (scale : ℝ) (loading weights : ι → ℝ)
    (horth : dot loading weights = 0) :
    (secondMomentMatrix E X + rankOneCovarianceBump scale loading).mulVec weights =
      (secondMomentMatrix E X).mulVec weights := by
  rw [secondMoment_imitation_shift, horth]
  simp

/-- **Whitening cannot destroy the imitation, only rotate it.** Conjugating the
bump by any right-side transform — the operation `rightWhiten` performs on data
rows — returns a bump of the same size in the transformed direction. Every
whitening or LD-pruning scheme therefore faces the same secular threshold, in
new coordinates. -/
theorem rankOneCovarianceBump_conjugate
    (transform : Matrix ι ι ℝ) (scale : ℝ) (loading : ι → ℝ) :
    transform.transpose * rankOneCovarianceBump scale loading * transform =
      rankOneCovarianceBump scale (transform.transpose.mulVec loading) := by
  ext i j
  have hinner : ∀ a : ι,
      (∑ b, transform b i * (scale ^ 2 * loading b * loading a) * transform a j) =
        (∑ b, transform b i * loading b) *
          (scale ^ 2 * (loading a * transform a j)) := by
    intro a
    have hterm : ∀ b : ι,
        transform b i * (scale ^ 2 * loading b * loading a) * transform a j =
          (transform b i * loading b) * (scale ^ 2 * (loading a * transform a j)) := by
      intro b; ring
    simp_rw [hterm]
    exact (Finset.sum_mul _ _ _).symm
  have hexpand :
      (transform.transpose * rankOneCovarianceBump scale loading * transform) i j =
        ∑ a, (∑ b, transform b i * loading b) *
          (scale ^ 2 * (loading a * transform a j)) := by
    simp only [Matrix.mul_apply, rankOneCovarianceBump, Matrix.transpose_apply]
    exact Finset.sum_congr rfl (fun a _ => by rw [← hinner a, Finset.sum_mul])
  have hright :
      rankOneCovarianceBump scale (transform.transpose.mulVec loading) i j =
        scale ^ 2 * ((∑ b, transform b i * loading b) *
          (∑ a, transform a j * loading a)) := by
    simp only [rankOneCovarianceBump, Matrix.mulVec, dotProduct, Matrix.transpose_apply]
    ring
  have hswap : (∑ a, loading a * transform a j) = ∑ a, transform a j * loading a :=
    Finset.sum_congr rfl (fun a _ => mul_comm _ _)
  rw [hexpand, hright, ← Finset.mul_sum, ← Finset.mul_sum, hswap]
  ring

/-- **The dropout floor caps individual-level explanation.** With a positive
leave-one-out quadratic form, a fair alive/dead genotyping mixture leaves a
strictly positive variance floor in the per-individual quantity, so the
`explainableFraction` of any group-level covariate — genetic distance included —
is strictly below one no matter how much between-group signal there is. This is
the technical mechanism underneath open question 1: individual accuracy is not
a function of population-level distance, and part of the residue is not
genetics at all. -/
theorem dropout_floor_caps_explainable_fraction
    (between quadraticForm : ℝ)
    (hbetween : 0 ≤ between) (hquadratic : 0 < quadraticForm) :
    explainableFraction between
        (between +
          fairTwoPointVariance (scalarRowResolvent 0 quadraticForm)
            (scalarRowResolvent (Real.sqrt 2) quadraticForm)) < 1 := by
  have hfloor := deadSensor_resolvent_variance_pos quadraticForm hquadratic
  unfold explainableFraction
  rw [div_lt_one (by linarith)]
  linarith

end Unification

end

end Calibrator
