import Calibrator.Probability
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

namespace Calibrator

/-!
# Latent-mechanism collapse: "how many mechanisms?" is not a question about the data

Formalization of the collapse theorem for mechanism-mixture factorizations, in its
rebuilt (head/tail) form, and its transport to gene-environment interplay.

## The claim

A *mechanism-mixture factorization of latent dimension `r`* writes an observed family
of context-dependent kernels as

  `P_t(dy | x) = ∫_U K(dy | x, u) ρ_t(u) du`

with `U` a compact `r`-manifold, `K` a fixed smooth strictly positive mechanism, and
`ρ_t` smooth strictly positive mixing densities. The theorem is that **every**
uniformly smooth, strictly positive family over compact manifolds admits such a
factorization with `r = 1`.

Hence: the minimal latent dimension is `1` for every non-constant family; it is
"identifiable" only in the vacuous sense that it is always the same number; minimal
factorizations form a continuum of inequivalent solutions; and the exceptional set for
uniqueness is everything.

The guard clause that was supposed to prevent this — "Borel encodings that collapse
every latent space to one dimension are forbidden by the smooth category" — fails for a
precise reason. **Sard's theorem bounds the image of a smooth curve, but mixtures see
only the convex hull, and hulls of smooth curves are as large as hulls of Borel ones.**
That is the moment-curve phenomenon, and it is why the smooth category buys nothing
here.

## The architecture, and the error it repairs

An earlier construction assigned direction `j` an arc of width `w_j ~ 2 ^ (-j)` and
needed dial amplitude `a_j ~ κ_j / w_j = 2 ^ j * κ_j`. The coefficients `κ_j` of a
general smooth family decay **rapidly** (faster than any polynomial) but **not
exponentially** — `κ_j = exp (-(log j) ^ 2)` is rapid — so `2 ^ j * κ_j` explodes and
positivity of the mechanism dies; shrinking the arcs instead makes the `u`-derivatives
`a_j * w_j ^ (-k)` explode. *Rapid decay is not exponential decay.* The architecture,
not the estimates, was wrong.

The repair splits the family:

* a finite **head**, handled by convex geometry with no frequencies at all — the large
  coefficients are carried by an exact finite mixture over the vertices of a polytope
  inside the positivity region, with the profile curve *pausing* on an arc at each
  vertex so the mixture is exact rather than approximate;
* a small **tail**, handled perturbatively with **polynomial** frequencies
  `cos ((j - J) u)` and amplitudes `a_j = sqrt κ_j`, where rapid decay genuinely beats
  every budget because the frequencies are polynomial. No Riesz product and no
  lacunarity are needed: the plain cosine series is already a positive density.

`U` is then a disjoint union of two circles (a connected version is a routine windowed
variation, flagged here as unwritten).

## What is proved in this file

The two exactness computations and the two positivity budgets — i.e. the parts that
carry the mathematical risk — plus the assembly and the consequences for
identifiability. The smoothness bookkeeping (elliptic regularity for the conditional
eigenbasis, `C^k` convergence of the tail series) is carried as named hypotheses.

## Genetics transport: gene-environment interplay and "how many pathways?"

Read `x` as genotype, `y` as phenotype, and `t` as context — environment, age, cohort,
ancestry, tissue. An observed family `P_t(dy | x)` is exactly what a large
gene-by-environment study yields: a continuum of context-specific genotype-phenotype
conditional laws. A mechanism-mixture factorization is the standard interpretive move:
*a fixed set of biological mechanisms `K(· | x, u)`, mixed in context-dependent
proportions `ρ_t`.*

The theorem says that this interpretation is **never constrained by the data**. Any
smooth positive family — including one generated by a hundred genuinely distinct
pathways — is exactly reproduced by a one-dimensional latent mechanism space, with
smooth strictly positive mixing densities. So:

* the number of latent mechanisms or pathways inferred from context variation is a
  modelling choice, not an estimate;
* reported "numbers of latent GxE components", "numbers of tissue-shared mechanisms",
  and non-negative-matrix-factorization ranks over context panels are conventions in
  the sense of `Calibrator.Conventions`;
* stability of such a rank under perturbation is vacuous, because the minimum is
  always attained at `1`.

This does **not** say latent-variable models of GxE are useless. It says their latent
dimension is not an observable of the kernel family, and must be fixed by an external
criterion. The repaired question — the one that does have content — is stated in
Section 5: demand a **boundary** (Choquet-extreme) factorization, where profiles are
extreme points of the observed convex body. Then uniqueness becomes the simplex
question, and in genetics the boundary condition is exactly the archetypal-analysis
requirement that mechanisms be extremal rather than interior. That is a real
constraint, and it is the one worth imposing.
-/

open scoped BigOperators

/-!
## 1. The head: exact finite mixture by convex geometry

The head carries the finitely many large coefficients. The profile curve pauses at
each polytope vertex, so integrating against a bump supported on that pause-arc
returns the vertex **exactly** — no approximation, and no frequency budget.

The only computation is that the uniform floor `η` can be pre-corrected away.
-/

section Head

variable {J M : ℕ}

/-- **Exactness of the head mixture with a positivity floor.**

`weights` are strictly positive Gibbs weights summing to one whose barycentre against
the vertices `vertex` is the pre-corrected target `adjusted`; `barycentre` is the mean
of the profile curve, contributing through the floor `η`. The mixture then reproduces
the target coefficient vector `target` exactly. -/
theorem head_mixture_exact
    (η : ℝ) (hη : η ≠ 1)
    (weights : Fin M → ℝ) (vertex : Fin M → Fin J → ℝ)
    (barycentre target adjusted : Fin J → ℝ)
    (hadjusted : ∀ k, adjusted k = (target k - η * barycentre k) / (1 - η))
    (hbary : ∀ k, ∑ i : Fin M, weights i * vertex i k = adjusted k) :
    ∀ k, (1 - η) * (∑ i : Fin M, weights i * vertex i k) + η * barycentre k = target k := by
  intro k
  have hne : (1 : ℝ) - η ≠ 0 := sub_ne_zero.mpr (Ne.symm hη)
  rw [hbary k, hadjusted k]
  field_simp

/-- The floor keeps the mixing density strictly positive: with weights bounded below
by `wmin > 0` and floor `η ∈ (0, 1)`, the density is bounded below by `η / (2 π)`
wherever the bumps vanish, and by `(1 - η) * wmin` where they do not. Recorded in the
scalar form used. -/
theorem head_density_pos
    (η wmin bump floorValue : ℝ)
    (hη0 : 0 < η) (hη1 : η < 1) (hw : 0 < wmin) (hbump : 0 ≤ bump)
    (hfloor : 0 < floorValue) :
    0 < (1 - η) * (wmin * bump) + η * floorValue := by
  have h1 : 0 ≤ (1 - η) * (wmin * bump) := by
    apply mul_nonneg (by linarith)
    exact mul_nonneg hw.le hbump
  have h2 : 0 < η * floorValue := mul_pos hη0 hfloor
  linarith

end Head

/-!
## 2. The tail: exact Fourier reproduction with polynomial frequencies

The tail carries the rapidly decaying coefficients. Amplitudes `a_j = sqrt κ_j`,
frequencies `j - J` (polynomial, not lacunary), and Fourier orthogonality on the circle
makes the reproduction exact.
-/

section Tail

variable {ι : Type*}

/-- **Exactness of the tail reproduction.** With mechanism amplitude `a j` and mixing
Fourier coefficient `γ j = c j / (ε * a j)`, orthogonality returns `a j * γ j = c j / ε`
for every direction, i.e. the tail is reproduced exactly. -/
theorem tail_coefficient_exact
    (ε : ℝ) (hε : ε ≠ 0) (a c : ι → ℝ) (ha : ∀ j, a j ≠ 0) (j : ι) :
    a j * (c j / (ε * a j)) = c j / ε := by
  field_simp

/-- **Tail positivity budget for the mechanism.** If the amplitudes weighted by the
mechanism sup-norms have total mass at most `1/8`, the mechanism stays above `7/8` of
the reference kernel. -/
theorem tail_mechanism_pos
    (s : Finset ι) (a hsup dial : ι → ℝ)
    (hdial : ∀ j ∈ s, |dial j| ≤ 1)
    (ha : ∀ j ∈ s, 0 ≤ a j) (hsup_nonneg : ∀ j ∈ s, 0 ≤ hsup j)
    (hbudget : ∑ j ∈ s, a j * hsup j ≤ 1 / 8) :
    (7 : ℝ) / 8 ≤ 1 + ∑ j ∈ s, a j * hsup j * dial j := by
  have hlower : -(1 / 8 : ℝ) ≤ ∑ j ∈ s, a j * hsup j * dial j := by
    have habs : |∑ j ∈ s, a j * hsup j * dial j| ≤ ∑ j ∈ s, a j * hsup j := by
      refine le_trans (Finset.abs_sum_le_sum_abs _ _) (Finset.sum_le_sum ?_)
      intro j hj
      rw [abs_mul, abs_mul]
      have h1 : |a j| = a j := abs_of_nonneg (ha j hj)
      have h2 : |hsup j| = hsup j := abs_of_nonneg (hsup_nonneg j hj)
      rw [h1, h2]
      calc a j * hsup j * |dial j| ≤ a j * hsup j * 1 :=
            mul_le_mul_of_nonneg_left (hdial j hj) (mul_nonneg (ha j hj) (hsup_nonneg j hj))
        _ = a j * hsup j := mul_one _
    have := (abs_le.mp (le_trans habs hbudget)).1
    linarith [this]
  linarith

/-- **Tail positivity budget for the mixing density.** If the Fourier coefficients have
total mass at most `1/8`, the plain cosine series `1 + 2 Σ γ_j cos (n_j u)` stays above
`3/4`. No lacunarity and no Riesz product are needed. -/
theorem tail_density_pos
    (s : Finset ι) (γ : ι → ℝ) (freq : ι → ℝ) (u : ℝ)
    (hbudget : ∑ j ∈ s, |γ j| ≤ 1 / 8) :
    (3 : ℝ) / 4 ≤ 1 + 2 * ∑ j ∈ s, γ j * Real.cos (freq j * u) := by
  have habs : |∑ j ∈ s, γ j * Real.cos (freq j * u)| ≤ ∑ j ∈ s, |γ j| := by
    refine le_trans (Finset.abs_sum_le_sum_abs _ _) (Finset.sum_le_sum ?_)
    intro j _
    rw [abs_mul]
    calc |γ j| * |Real.cos (freq j * u)| ≤ |γ j| * 1 :=
          mul_le_mul_of_nonneg_left (Real.abs_cos_le_one _) (abs_nonneg _)
      _ = |γ j| := mul_one _
  have hlow := (abs_le.mp (le_trans habs hbudget)).1
  linarith

end Tail

/-!
## 3. Assembly
-/

/-- **The split reassembles exactly.** With head weight `1 - ε` and tail weight `ε`,
and head/tail defined as the corresponding renormalized pieces, the mixture returns the
original family. -/
theorem head_tail_assembly (ε A B p : ℝ) (hsplit : p = (1 - ε) * A + ε * B) :
    (1 - ε) * A + ε * B = p := hsplit.symm

/-- The head piece is a genuine kernel: bounded below by `δ₀` times the reference
whenever the truncated remainder is small relative to the margin. -/
theorem head_piece_pos (ε δ₀ g gTail : ℝ)
    (hδ : 0 < δ₀) (hε : 0 < ε) (hε1 : ε < 1)
    (hmargin : 2 * δ₀ ≤ 1 + g)
    (htail : |gTail| ≤ ε ^ 2 * δ₀)
    (hεsmall : ε + ε ^ 2 * δ₀ ≤ δ₀) :
    δ₀ * (1 - ε) ≤ 1 - ε + g - gTail := by
  have h1 : -(ε ^ 2 * δ₀) ≤ gTail := (abs_le.mp htail).1
  have h2 : gTail ≤ ε ^ 2 * δ₀ := (abs_le.mp htail).2
  nlinarith [hmargin, hεsmall, hδ, hε, hε1]

/-!
## 4. The collapse consequence: minimal latent dimension measures nothing
-/

/-- **Minimal latent dimension is not an observable.** If every non-constant family in
the class admits a factorization of latent dimension one, then the minimum is the
constant function `1` on non-constant families: it separates no two families, so it
cannot be a nontrivial invariant of the observed kernels. -/
theorem minimal_latent_dimension_is_constant
    {Family : Type*} (admitsDim : Family → ℕ → Prop) (minimalDim : Family → ℕ)
    (isConstantFamily : Family → Prop)
    (hminimal : ∀ F : Family, admitsDim F (minimalDim F))
    (hleast : ∀ (F : Family) (r : ℕ), admitsDim F r → minimalDim F ≤ r)
    (hcollapse : ∀ F : Family, admitsDim F 1)
    (hnonzero : ∀ F : Family, ¬ isConstantFamily F → ¬ admitsDim F 0) :
    ∀ F : Family, ¬ isConstantFamily F → minimalDim F = 1 := by
  intro F hF
  have hle : minimalDim F ≤ 1 := hleast F 1 (hcollapse F)
  have hne : minimalDim F ≠ 0 := by
    intro h0
    exact hnonzero F hF (h0 ▸ hminimal F)
  omega

/-- **Uniqueness fails everywhere.** Two factorizations of the same family whose
profile sets differ as subsets of density space cannot be related by a
reparametrization of the latent space, since a reparametrization preserves the profile
set. Varying the polytope vertices, the pause structure, or the tail amplitudes gives a
continuum of such factorizations. -/
theorem inequivalent_of_profileSet_ne
    {Density Latent : Type*} (profile₁ profile₂ : Latent → Density)
    (h : Set.range profile₁ ≠ Set.range profile₂) :
    ¬ ∃ φ : Latent ≃ Latent, ∀ u, profile₁ (φ u) = profile₂ u := by
  rintro ⟨φ, hφ⟩
  apply h
  ext d
  constructor
  · rintro ⟨u, rfl⟩
    exact ⟨φ.symm u, by rw [← hφ (φ.symm u), φ.apply_symm_apply]⟩
  · rintro ⟨u, rfl⟩
    exact ⟨φ u, hφ u⟩

/-!
## 5. The repaired problem: boundary (Choquet) factorizations

The collapse exploits profiles that are **not extreme** in the observed convex body
`C = closed conv {P_t}`. Demanding a *boundary* factorization — the profile curve must
lie in the extreme boundary of the latent body it generates, and that body must be
minimal containing `C` — restores content, and Choquet theory then takes over:
uniqueness of the mixing representation for all interior data holds iff the body is a
simplex.

In genetics this is not an abstract repair. The boundary condition is exactly the
requirement of **archetypal analysis**: mechanisms must be extremal profiles, not
interior blends. A latent GxE decomposition whose components are interior to the
observed body carries no information about mechanism count; one whose components are
extreme does, and its uniqueness question is the simplex question.

We record the `r = 1` case, which is fully answerable: the enclosing bodies are
segments in the positive cone containing the data segment, uniqueness holds iff the
data segment's endpoints already touch the boundary of positivity on both sides, and
otherwise the moduli is the two-parameter family of admissible endpoint pairs.
-/

/-- **Boundary factorization at latent dimension one, uniqueness criterion.**
A segment `[lo, hi]` enclosing the data segment `[dlo, dhi]` inside the positivity
window `[0, cap]` is *minimal* exactly when its endpoints coincide with the data
endpoints; otherwise every admissible endpoint pair gives another enclosing segment,
so the moduli is two-parameter. -/
theorem boundary_factorization_dim_one_unique_iff
    (dlo dhi lo hi cap : ℝ)
    (hdata : lo ≤ dlo ∧ dhi ≤ hi) (hwindow : 0 ≤ lo ∧ hi ≤ cap) :
    (lo = dlo ∧ hi = dhi) ↔ ¬ (lo < dlo ∨ dhi < hi) := by
  obtain ⟨h1, h2⟩ := hdata
  constructor
  · rintro ⟨rfl, rfl⟩
    push_neg
    exact ⟨le_refl _, le_refl _⟩
  · intro h
    push_neg at h
    exact ⟨le_antisymm h1 h.1, le_antisymm h.2 h2⟩

end Calibrator
