/-
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Calibrator.SecondMomentShift
import Calibrator.QuadraticShift
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

namespace Calibrator

noncomputable section

/-!
# Discrepancy--curvature bounds for projection movement

This module isolates the analytic engine behind sharp projection-artifact
bounds.  The expectation abstraction used by the project is only linear, so
Cauchy--Schwarz and positivity are stated explicitly.  Actual probability
measures discharge those hypotheses in the usual `L²` space.
-/

variable {Ω ι : Type*} [Fintype ι] [DecidableEq ι]

/-- Squared `L²` magnitude of a density-ratio perturbation. -/
def chiSquareBudget (P : ExpFunctional Ω) (densityRatio : Ω → ℝ) : ℝ :=
  P (fun ω ↦ (densityRatio ω - 1) ^ 2)

/-- Residual curvature seen along a coefficient direction. -/
def directionalResidualCurvature (P : ExpFunctional Ω)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ) (direction : ι → ℝ) : ℝ :=
  P (fun ω ↦ (dot direction (X ω) * residual ω) ^ 2)

/-- Moment movement generated by reweighting a residual with a density ratio. -/
def weightedResidualMoment (P : ExpFunctional Ω)
    (densityRatio : Ω → ℝ) (X : Ω → ι → ℝ)
    (residual : Ω → ℝ) : ι → ℝ :=
  rawCrossMoment P X (fun ω ↦ (densityRatio ω - 1) * residual ω)

/-- Pairing the shifted residual moment with a direction is exactly the scalar
`L²` pairing to which Cauchy--Schwarz applies. -/
theorem dot_weightedResidualMoment
    (P : ExpFunctional Ω) (densityRatio : Ω → ℝ)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ) (direction : ι → ℝ) :
    dot direction (weightedResidualMoment P densityRatio X residual) =
      P (fun ω ↦
        (densityRatio ω - 1) * (dot direction (X ω) * residual ω)) := by
  unfold weightedResidualMoment rawCrossMoment dot
  have hexpand :
      (fun ω ↦
        (densityRatio ω - 1) *
          ((∑ i, direction i * X ω i) * residual ω)) =
        ∑ i, (direction i) •
          (fun ω ↦ X ω i * ((densityRatio ω - 1) * residual ω)) := by
    funext ω
    calc
      (densityRatio ω - 1) *
          ((∑ i, direction i * X ω i) * residual ω) =
          ((densityRatio ω - 1) * residual ω) *
            ∑ i, direction i * X ω i := by ring
      _ = ∑ i, ((densityRatio ω - 1) * residual ω) *
            (direction i * X ω i) := by rw [Finset.mul_sum]
      _ = ∑ i, (direction i) •
            (fun ω ↦ X ω i * ((densityRatio ω - 1) * residual ω)) ω := by
          apply Finset.sum_congr rfl
          intro i _
          simp only [smul_eq_mul]
          ring
      _ = (∑ i, (direction i) •
            (fun ω ↦ X ω i * ((densityRatio ω - 1) * residual ω))) ω := by
          simp only [Finset.sum_apply, Pi.smul_apply]
  rw [hexpand, ExpFunctional.eval_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [P.smul_eval]

/-- Directional chi-square bound.  This is the exact product of distributional
discrepancy and residual nonlinearity before optimizing over directions. -/
theorem weighted_residual_moment_directional_bound
    (P : ExpFunctional Ω) (densityRatio : Ω → ℝ)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ) (direction : ι → ℝ)
 :
    dot direction (weightedResidualMoment P densityRatio X residual) ^ 2 ≤
      chiSquareBudget P densityRatio *
        directionalResidualCurvature P X residual direction := by
  rw [dot_weightedResidualMoment]
  exact P.cauchy_schwarz
    (fun ω ↦ densityRatio ω - 1)
    (fun ω ↦ dot direction (X ω) * residual ω)

/-- Quadratic energy associated with a second-moment matrix. -/
def coefficientEnergy (B : Matrix ι ι ℝ) (x : ι → ℝ) : ℝ :=
  dot x (B.mulVec x)

theorem dot_add_right_shift (x y z : ι → ℝ) :
    dot x (y + z) = dot x y + dot x z := by
  simp [dot, mul_add, Finset.sum_add_distrib]

/-- Sharp discrepancy--curvature product bound for projection artifacts.

`B a = g` is the residual-score equation for the coefficient movement `a`.
The curvature-domination hypothesis is the generalized Rayleigh bound
`M ≤ Λ B` evaluated in the relevant direction.  The conclusion is the full
quadratic excess-risk bound, with no invertibility assumption on `B`. -/
theorem projection_artifact_energy_le_chiSquare_mul_curvature
    (P : ExpFunctional Ω) (densityRatio : Ω → ℝ)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ)
    (B : Matrix ι ι ℝ) (artifact : ι → ℝ) (Λ : ℝ)
    (hmoment : B.mulVec artifact =
      weightedResidualMoment P densityRatio X residual)

    (henergy : 0 ≤ coefficientEnergy B artifact)
    (hchiSquare : 0 ≤ chiSquareBudget P densityRatio)
    (hΛ : 0 ≤ Λ)
    (hcurvature : directionalResidualCurvature P X residual artifact ≤
      Λ * coefficientEnergy B artifact) :
    coefficientEnergy B artifact ≤ chiSquareBudget P densityRatio * Λ := by
  have hdirectional := weighted_residual_moment_directional_bound
    P densityRatio X residual artifact
  have hpairing :
      dot artifact (weightedResidualMoment P densityRatio X residual) =
        coefficientEnergy B artifact := by
    unfold coefficientEnergy
    rw [← hmoment]
  rw [hpairing] at hdirectional
  have hproduct :
      chiSquareBudget P densityRatio *
          directionalResidualCurvature P X residual artifact ≤
        chiSquareBudget P densityRatio *
          (Λ * coefficientEnergy B artifact) :=
    mul_le_mul_of_nonneg_left hcurvature hchiSquare
  have hquadratic :
      coefficientEnergy B artifact ^ 2 ≤
        (chiSquareBudget P densityRatio * Λ) *
          coefficientEnergy B artifact := by
    calc
      coefficientEnergy B artifact ^ 2
          ≤ chiSquareBudget P densityRatio *
              directionalResidualCurvature P X residual artifact := hdirectional
      _ ≤ chiSquareBudget P densityRatio *
              (Λ * coefficientEnergy B artifact) := hproduct
      _ = (chiSquareBudget P densityRatio * Λ) *
              coefficientEnergy B artifact := by ring
  by_cases hzero : coefficientEnergy B artifact = 0
  · rw [hzero]
    exact mul_nonneg hchiSquare hΛ
  · have hpositive : 0 < coefficientEnergy B artifact :=
      lt_of_le_of_ne henergy (Ne.symm hzero)
    nlinarith

/-- Under identifiability of the target second-moment operator, the moment-level
genuine/artifact decomposition uniquely lifts to coefficient space.  This is
the precise point at which nonsingularity is required: all preceding moment and
risk identities remain valid without it. -/
theorem projection_shift_eq_genuine_add_artifact
    (Q : ExpFunctional Ω) (X : Ω → ι → ℝ)
    (hOld hNew : Ω → ℝ) (u v genuine artifact : ι → ℝ)
    (htarget : residualScoreMoment Q X hNew v = 0)
    (hgenuine : (secondMomentMatrix Q X).mulVec genuine =
      rawCrossMoment Q X (fun ω ↦ hNew ω - hOld ω))
    (hartifact : (secondMomentMatrix Q X).mulVec artifact =
      residualScoreMoment Q X hOld u)
    (hinjective : Function.Injective (secondMomentMatrix Q X).mulVec) :
    (fun i ↦ v i - u i) = fun i ↦ genuine i + artifact i := by
  apply hinjective
  rw [projection_shift_genuine_artifact_decomposition Q X hOld hNew u v htarget]
  rw [matrix_mulVec_add, hgenuine, hartifact]

/-- Exact energy expansion for the sum of a genuine component and a projection
artifact. -/
theorem coefficientEnergy_add
    (B : Matrix ι ι ℝ) (x y : ι → ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B) :
    coefficientEnergy B (fun i ↦ x i + y i) =
      coefficientEnergy B x + coefficientEnergy B y +
        2 * dot x (B.mulVec y) := by
  unfold coefficientEnergy
  rw [matrix_mulVec_add, dot_add_left]
  rw [dot_add_right_shift, dot_add_right_shift]
  rw [hsymmetric y x]
  ring

/-- Risk-level genuine/artifact decomposition with sharp norm budgets.  If the
cross term obeys the corresponding Cauchy--Schwarz budget, total movement is
bounded by the square of the sum of component budgets. -/
theorem total_shift_energy_le_sum_budget_sq
    (B : Matrix ι ι ℝ) (genuine artifact : ι → ℝ)
    (genuineBudget artifactBudget : ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B)
    (hgenuine : coefficientEnergy B genuine ≤ genuineBudget ^ 2)
    (hartifact : coefficientEnergy B artifact ≤ artifactBudget ^ 2)
    (hcross : dot genuine (B.mulVec artifact) ≤
      genuineBudget * artifactBudget) :
    coefficientEnergy B (fun i ↦ genuine i + artifact i) ≤
      (genuineBudget + artifactBudget) ^ 2 := by
  rw [coefficientEnergy_add B genuine artifact hsymmetric]
  nlinarith

/-!
## The detection/reconstruction frontier for rank-limited reductions

Everything above bounds the movement of a projection.  This section asks a
different question about the same object: **what is a dimension reduction
for?**

Fix a background covariance already diagonalised, with eigenvalues
`spectrum i > 0`.  Two tasks are run on the same reduced data.

* **Detection** of a weak spike.  The optimal linear certificate weights each
  eigendirection by the inverse background variance, `1 / σᵢ`: a direction with
  little background noise is a direction in which a small signal is visible.
  Detection power is therefore carried by the *smallest*-variance directions.
* **Reconstruction / denoising.**  The optimal weights are the signal-variance
  shares, increasing in `σᵢ`; the fraction of variance retained is exactly what
  a principal-component truncation maximises.  Reconstruction accuracy is
  carried by the *largest*-variance directions.

The two weight profiles are inversely ordered (`weight_orders_reversed`), and
that single fact drives everything else here.

### Why this is about LD pruning

LD pruning and clumping keep one representative marker per correlated block and
discard the rest.  In the eigenbasis of the LD kernel that is precisely the
operation "keep the high-variance directions, discard the low-variance ones":
the discarded directions are the tightly-linked contrasts, which are exactly
where the *inverse* LD kernel is large.  `Calibrator.ImitationRigidity` computes
that inverse trace in closed form for a stationary chromosome
(`ldWhiteningGain`), so pruning is not being accused of a vague inefficiency —
it discards a computable amount of the quantity every whitened detection
threshold is stated in.  `topVariance_minimizes_detection` below turns that into
a prohibition: among reductions of a given rank, the variance-greedy one is the
*worst possible* choice for detection.

### Scope, stated honestly

Everything below is proved for **linear, projection-type reductions**, relaxed
to the spectrahedron `{0 ≤ M ≤ I, tr M ≤ k}` and then diagonalised.  The
diagonalisation is legitimate here because both objective matrices are functions
of the background and hence commute with it, so the Pareto problem is a linear
program in the eigenvalue coordinates; that is why the allocations below are
vectors `M : ι → ℝ` rather than matrices.  This is *not* proved for arbitrary
measurable reductions, and it should not be quoted as if it were: extending it
would need a joint data-processing inequality for the pair of tasks, and no such
inequality exists — applying data processing to each task separately yields only
the trivial unit box.
-/

section DetectionReconstructionFrontier

/-- **Detection weight of an eigendirection** with background variance `s`.

The whitened certificate that maximises noncentrality against a weak spike
weights each direction by the inverse background variance.  This is the same
`1/σ` that produces the inverse-kernel trace in
`Calibrator.ImitationRigidity.ldWhiteningGain`.

Empirical status: UNTESTED. -/
def detectionWeight (s : ℝ) : ℝ := s⁻¹

/-- **detectionWeight at its junk point, named.** A signal of zero scale should carry unbounded
inverse-variance weight. The inverse of zero is junk-zero, so it carries NO weight and drops
silently out of any weighted combination it enters. Consumers must exclude the argument that
makes the guard vanish. -/
theorem detectionWeight_zero_scale_is_junk :
    detectionWeight 0 = 0 := by
  unfold detectionWeight
  simp

/-- **Reconstruction weight of an eigendirection** with background variance `s`:
the direction's own variance, i.e. its share of the total signal energy.  A
rank-`k` truncation maximising `∑ σᵢ` over retained directions is what
principal-component truncation does.

Empirical status: UNTESTED. -/
def reconstructionWeight (s : ℝ) : ℝ := s

/-- **Wiener (denoising) weight** `σ / (σ + noise)`: the shrinkage factor of the
optimal linear denoiser in a direction with signal variance `s` and additive
noise level `noise`.  Recorded so that the inverse-ordering conclusion is not an
artefact of the particular reconstruction profile chosen — `wienerWeight` is a
different, strictly increasing function of `s` and gives the same ordering.

Empirical status: UNTESTED. -/
def wienerWeight (noise s : ℝ) : ℝ := s / (s + noise)

/-- **wienerWeight where its denominator vanishes, named.** The guard `s + noise` is zero at `noise
= 0`, `s = 0`. Lean returns `0` there rather than the value the modelled quantity takes, and no
type error marks the point. Consumers must require `s + noise ≠ 0`. -/
theorem wienerWeight_at_noise0s0_is_junk :
    wienerWeight 0 0 = 0 := by
  unfold wienerWeight
  norm_num

/-- **Detection weights are strictly decreasing in the background variance.** -/
theorem detectionWeight_strictAnti {s₁ s₂ : ℝ} (h₁ : 0 < s₁) (h : s₁ < s₂) :
    detectionWeight s₂ < detectionWeight s₁ := by
  have h₂ : 0 < s₂ := lt_trans h₁ h
  have hprod : 0 < s₁ * s₂ := mul_pos h₁ h₂
  have e1 : s₂⁻¹ * (s₁ * s₂) = s₁ := by
    rw [show s₁ * s₂ = s₂ * s₁ by ring, ← mul_assoc,
      inv_mul_cancel₀ (ne_of_gt h₂), one_mul]
  have e2 : s₁⁻¹ * (s₁ * s₂) = s₂ := by
    rw [← mul_assoc, inv_mul_cancel₀ (ne_of_gt h₁), one_mul]
  have key : s₂⁻¹ * (s₁ * s₂) < s₁⁻¹ * (s₁ * s₂) := by
    rw [e1, e2]; exact h
  unfold detectionWeight
  exact lt_of_mul_lt_mul_right key (le_of_lt hprod)

/-! `reconstructionWeight_strictMono` used to sit here. `reconstructionWeight` is the
identity `fun s ↦ s`, so its statement `reconstructionWeight s₁ < reconstructionWeight s₂`
under the hypothesis `s₁ < s₂` was the hypothesis itself and its proof was `h`. It is
deleted for the same reason `factor_lt_one_of_cos_lt` was. The monotonicity that carries
content is `wienerWeight_strictMono` below, whose weight profile is not the identity;
`weight_orders_reversed` now discharges its reconstruction conjunct with `h` directly, so
the tautology is visible at the point of use instead of hidden behind a name. -/

/-- The Wiener profile is strictly increasing too: the inverse ordering is a
property of the two *tasks*, not of the particular reconstruction weight. -/
theorem wienerWeight_strictMono {noise s₁ s₂ : ℝ}
    (hn : 0 < noise) (h₁ : 0 < s₁) (h : s₁ < s₂) :
    wienerWeight noise s₁ < wienerWeight noise s₂ := by
  have h₂ : 0 < s₂ := lt_trans h₁ h
  have d₁ : 0 < s₁ + noise := by linarith
  have d₂ : 0 < s₂ + noise := by linarith
  unfold wienerWeight
  rw [div_lt_div_iff₀ d₁ d₂]
  nlinarith [mul_pos hn (sub_pos.mpr h)]

/-- **The two weight profiles are inversely ordered.**  On a background with
distinct eigenvalues, moving to a higher-variance direction strictly increases
the reconstruction weight and strictly decreases the detection weight.  No
reduction can therefore be greedy for both tasks at once, and the rest of this
section quantifies the resulting loss. -/
theorem weight_orders_reversed {s₁ s₂ : ℝ} (h₁ : 0 < s₁) (h : s₁ < s₂) :
    reconstructionWeight s₁ < reconstructionWeight s₂ ∧
      detectionWeight s₂ < detectionWeight s₁ :=
  ⟨h, detectionWeight_strictAnti h₁ h⟩

/-- **A relaxed rank-`k` reduction**, written in the eigenbasis of the
background.  `M i` is the fraction of eigendirection `i` that survives the
reduction; `0 ≤ M ≤ 1` is the operator constraint `0 ≤ M ≤ I` and the trace
condition is the rank budget.  Genuine rank-`k` projections are the `0/1`
points of this set; the relaxation is what makes both task efficiencies linear.

The trace is pinned to `k` rather than bounded by it because the minimisation
results below are statements about reductions that actually *use* their budget:
with `tr M ≤ k` the detection minimum is attained trivially by `M = 0`.

Empirical status: UNTESTED. -/
structure IsRankAllocation (k : ℝ) (M : ι → ℝ) : Prop where
  lower : ∀ i, 0 ≤ M i
  upper : ∀ i, M i ≤ 1
  trace : ∑ i, M i = k

/-- **The predicate is satisfiable.**  Every theorem below assumes an allocation
exists; the zero allocation at budget `0` is one.  Without this they are conditional on
a hypothesis nothing in the corpus discharges. -/
theorem IsRankAllocation.witness : IsRankAllocation (ι := ι) 0 (fun _ ↦ 0) where
  lower := fun _ ↦ le_refl 0
  upper := fun _ ↦ by norm_num
  trace := by simp

/-- Weight captured by an allocation: the linear functional both task
efficiencies are built from.

Empirical status: UNTESTED. -/
def spectralCapture (w M : ι → ℝ) : ℝ := ∑ i, M i * w i

/-- Total available weight of a profile: the denominator of both efficiencies.

Empirical status: UNTESTED. -/
def spectralTotal (w : ι → ℝ) : ℝ := ∑ i, w i

/-- **Reconstruction efficiency**: the fraction of total background variance
retained by the reduction.  This is the quantity a scree plot reports.

Empirical status: UNTESTED. -/
def reconstructionEfficiency (spectrum M : ι → ℝ) : ℝ :=
  spectralCapture (fun i ↦ reconstructionWeight (spectrum i)) M /
    spectralTotal (fun i ↦ reconstructionWeight (spectrum i))

/-- **Detection efficiency**: the fraction of the total inverse-variance
(whitened) weight retained by the reduction.  For an LD kernel the denominator
is the inverse-kernel trace whose closed form is
`Calibrator.ImitationRigidity.ldWhiteningGain`.

Empirical status: UNTESTED. -/
def detectionEfficiency (spectrum M : ι → ℝ) : ℝ :=
  spectralCapture (fun i ↦ detectionWeight (spectrum i)) M /
    spectralTotal (fun i ↦ detectionWeight (spectrum i))

/-- The variance-greedy ("pruning") allocation: keep the directions in `S`
entirely and discard everything else.  LD pruning and clumping are of this form
with `S` the high-variance block representatives.

Empirical status: UNTESTED. -/
def pruneAllocation (S : Finset ι) : ι → ℝ := fun i ↦ if i ∈ S then 1 else 0

/-- Dividing a proved capture inequality by a fixed positive total.  Stated
separately so that no efficiency-level result depends on the exact name of a
division-monotonicity lemma. -/
theorem captureRatio_le_of_le {a b c : ℝ} (h : a ≤ b) (hc : 0 < c) :
    a / c ≤ b / c := by
  rw [div_eq_mul_inv, div_eq_mul_inv]
  exact mul_le_mul_of_nonneg_right h (le_of_lt (inv_pos.mpr hc))

/-- A profile of nonnegative weights has nonnegative total.

This is what replaces the caller-supplied positivity of the efficiency
denominator in `topVariance_maximizes_reconstruction` and
`topVariance_minimizes_detection`: on a positive spectrum the total is never
negative, and in the degenerate case where it vanishes — only possible when `ι`
is empty — both efficiencies are `0` by `div_zero`, so the comparison holds
anyway.  The positivity of the denominator was never a restriction on the
inputs, so it should not have been a premise. -/
theorem spectralTotal_nonneg {w : ι → ℝ} (hw : ∀ i, 0 ≤ w i) :
    0 ≤ spectralTotal w := by
  unfold spectralTotal
  exact Finset.sum_nonneg (fun i _ ↦ hw i)

theorem spectralCapture_pruneAllocation (w : ι → ℝ) (S : Finset ι) :
    spectralCapture w (pruneAllocation S) = ∑ i ∈ S, w i := by
  have hzero : ∀ i, i ∉ S → pruneAllocation S i * w i = 0 := by
    intro i hi
    simp [pruneAllocation, hi]
  have hS : ∀ i ∈ S, pruneAllocation S i * w i = w i := by
    intro i hi
    simp [pruneAllocation, hi]
  have h1 : ∑ i ∈ S, pruneAllocation S i * w i ≤
      ∑ i, pruneAllocation S i * w i :=
    Finset.sum_le_sum_of_subset_of_nonneg (Finset.subset_univ S)
      (fun i _ hi ↦ le_of_eq (hzero i hi).symm)
  have h2 : ∑ i ∈ S, (-(pruneAllocation S i * w i)) ≤
      ∑ i, (-(pruneAllocation S i * w i)) :=
    Finset.sum_le_sum_of_subset_of_nonneg (Finset.subset_univ S)
      (fun i _ hi ↦ by rw [hzero i hi]; norm_num)
  rw [Finset.sum_neg_distrib, Finset.sum_neg_distrib] at h2
  have heq : ∑ i, pruneAllocation S i * w i =
      ∑ i ∈ S, pruneAllocation S i * w i := by linarith
  unfold spectralCapture
  rw [heq]
  exact Finset.sum_congr rfl hS

theorem pruneAllocation_isRankAllocation (S : Finset ι) :
    IsRankAllocation (S.card : ℝ) (pruneAllocation S) := by
  refine ⟨?_, ?_, ?_⟩
  · intro i
    by_cases hi : i ∈ S
    · simp [pruneAllocation, hi]
    · simp [pruneAllocation, hi]
  · intro i
    by_cases hi : i ∈ S
    · simp [pruneAllocation, hi]
    · simp [pruneAllocation, hi]
  · have h := spectralCapture_pruneAllocation (fun _ ↦ (1 : ℝ)) S
    unfold spectralCapture at h
    simp only [mul_one] at h
    rw [Finset.sum_const, nsmul_eq_mul, mul_one] at h
    exact h

/-!
### The exchange (threshold) lemma

The whole frontier rests on one dual certificate.  If a set `S` of cardinality
`k` is separated from its complement by a threshold `t` in some weight profile
`w`, then no relaxed rank-`k` allocation can capture more `w`-weight than `S`
does, and none can capture less than `S` does when the ordering is reversed.
Nothing here needs a sort, an eigenvector, or a compactness argument.
-/

/-- **Threshold optimality.**  `S` is `w`-dominant above the threshold `t`; then
`S` maximises captured `w`-weight over all relaxed rank-`|S|` allocations. -/
theorem spectralCapture_le_of_threshold
    (w M : ι → ℝ) (S : Finset ι) (t : ℝ)
    (hM : IsRankAllocation (S.card : ℝ) M)
    (hin : ∀ i ∈ S, t ≤ w i)
    (hout : ∀ i ∉ S, w i ≤ t) :
    spectralCapture w M ≤ ∑ i ∈ S, w i := by
  have hstep1 : ∑ i, M i * (w i - t) ≤ ∑ i ∈ S, M i * (w i - t) := by
    have hneg : ∑ i ∈ S, (-(M i * (w i - t))) ≤
        ∑ i, (-(M i * (w i - t))) := by
      refine Finset.sum_le_sum_of_subset_of_nonneg (Finset.subset_univ S) ?_
      intro i _ hi
      have hw : w i - t ≤ 0 := sub_nonpos.mpr (hout i hi)
      nlinarith [mul_nonneg (hM.lower i) (neg_nonneg.mpr hw)]
    rw [Finset.sum_neg_distrib, Finset.sum_neg_distrib] at hneg
    linarith
  have hstep2 : ∑ i ∈ S, M i * (w i - t) ≤ ∑ i ∈ S, (w i - t) := by
    refine Finset.sum_le_sum ?_
    intro i hi
    have hw : 0 ≤ w i - t := sub_nonneg.mpr (hin i hi)
    nlinarith [mul_le_mul_of_nonneg_right (hM.upper i) hw]
  have hL : ∑ i, M i * (w i - t) = (∑ i, M i * w i) - t * ∑ i, M i := by
    calc ∑ i, M i * (w i - t)
        = ∑ i, (M i * w i - t * M i) :=
          Finset.sum_congr rfl (fun i _ ↦ by ring)
      _ = (∑ i, M i * w i) - ∑ i, t * M i := by rw [Finset.sum_sub_distrib]
      _ = (∑ i, M i * w i) - t * ∑ i, M i := by rw [← Finset.mul_sum]
  have hR : ∑ i ∈ S, (w i - t) = (∑ i ∈ S, w i) - t * (S.card : ℝ) := by
    calc ∑ i ∈ S, (w i - t)
        = (∑ i ∈ S, w i) - ∑ i ∈ S, t := by rw [Finset.sum_sub_distrib]
      _ = (∑ i ∈ S, w i) - t * (S.card : ℝ) := by
          rw [Finset.sum_const, nsmul_eq_mul]; ring
  rw [hL, hM.trace] at hstep1
  rw [hR] at hstep2
  unfold spectralCapture
  linarith

/-- **Threshold pessimality**, the mirror statement.  If `S` sits *below* the
threshold in the profile `w`, then `S` captures less `w`-weight than any relaxed
rank-`|S|` allocation.  This is the half that turns "pruning is greedy for
variance" into "pruning is anti-greedy for detection". -/
theorem spectralCapture_ge_of_threshold
    (w M : ι → ℝ) (S : Finset ι) (t : ℝ)
    (hM : IsRankAllocation (S.card : ℝ) M)
    (hin : ∀ i ∈ S, w i ≤ t)
    (hout : ∀ i ∉ S, t ≤ w i) :
    ∑ i ∈ S, w i ≤ spectralCapture w M := by
  have hstep1 : ∑ i ∈ S, M i * (w i - t) ≤ ∑ i, M i * (w i - t) := by
    refine Finset.sum_le_sum_of_subset_of_nonneg (Finset.subset_univ S) ?_
    intro i _ hi
    have hw : 0 ≤ w i - t := sub_nonneg.mpr (hout i hi)
    exact mul_nonneg (hM.lower i) hw
  have hstep2 : ∑ i ∈ S, (w i - t) ≤ ∑ i ∈ S, M i * (w i - t) := by
    refine Finset.sum_le_sum ?_
    intro i hi
    have hw : w i - t ≤ 0 := sub_nonpos.mpr (hin i hi)
    nlinarith [mul_le_mul_of_nonneg_right (hM.upper i) (neg_nonneg.mpr hw)]
  have hL : ∑ i, M i * (w i - t) = (∑ i, M i * w i) - t * ∑ i, M i := by
    calc ∑ i, M i * (w i - t)
        = ∑ i, (M i * w i - t * M i) :=
          Finset.sum_congr rfl (fun i _ ↦ by ring)
      _ = (∑ i, M i * w i) - ∑ i, t * M i := by rw [Finset.sum_sub_distrib]
      _ = (∑ i, M i * w i) - t * ∑ i, M i := by rw [← Finset.mul_sum]
  have hR : ∑ i ∈ S, (w i - t) = (∑ i ∈ S, w i) - t * (S.card : ℝ) := by
    calc ∑ i ∈ S, (w i - t)
        = (∑ i ∈ S, w i) - ∑ i ∈ S, t := by rw [Finset.sum_sub_distrib]
      _ = (∑ i ∈ S, w i) - t * (S.card : ℝ) := by
          rw [Finset.sum_const, nsmul_eq_mul]; ring
  rw [hL, hM.trace] at hstep1
  rw [hR] at hstep2
  unfold spectralCapture
  linarith

/-!
### The pruning prohibition

`S` is a top-`k` set by background variance: separated above a threshold `t`.
Because the detection profile is the *reciprocal* of the reconstruction profile,
the very same set is separated *below* the threshold `1/t` in the detection
profile.  So one hypothesis yields both conclusions, in opposite directions.
-/

/-- A variance-dominant set is inverse-variance-dominated: the reversal of the
weight order transports the separating threshold `t` to the threshold `t⁻¹`. -/
theorem detection_threshold_of_variance_threshold
    (spectrum : ι → ℝ) (S : Finset ι) (t : ℝ)
    (hpos : ∀ i, 0 < spectrum i) (ht : 0 < t)
    (hin : ∀ i ∈ S, t ≤ spectrum i)
    (hout : ∀ i ∉ S, spectrum i ≤ t) :
    (∀ i ∈ S, detectionWeight (spectrum i) ≤ detectionWeight t) ∧
      (∀ i ∉ S, detectionWeight t ≤ detectionWeight (spectrum i)) := by
  constructor
  · intro i hi
    rcases eq_or_lt_of_le (hin i hi) with heq | hlt
    · simp [heq]
    · exact le_of_lt (detectionWeight_strictAnti ht hlt)
  · intro i hi
    rcases eq_or_lt_of_le (hout i hi) with heq | hlt
    · simp [heq]
    · exact le_of_lt (detectionWeight_strictAnti (hpos i) hlt)

/-- **Variance-greedy reduction maximises reconstruction efficiency.**  This is
the half of the story the field already relies on: a top-`k` truncation is the
best rank-`k` linear reconstruction there is. -/
theorem topVariance_maximizes_reconstruction
    (spectrum M : ι → ℝ) (S : Finset ι) (t : ℝ)
    (hpos : ∀ i, 0 < spectrum i)
    (hM : IsRankAllocation (S.card : ℝ) M)
    (hin : ∀ i ∈ S, t ≤ spectrum i)
    (hout : ∀ i ∉ S, spectrum i ≤ t) :
    reconstructionEfficiency spectrum M ≤
      reconstructionEfficiency spectrum (pruneAllocation S) := by
  have hin' : ∀ i ∈ S, t ≤ reconstructionWeight (spectrum i) := by
    intro i hi
    unfold reconstructionWeight
    exact hin i hi
  have hout' : ∀ i ∉ S, reconstructionWeight (spectrum i) ≤ t := by
    intro i hi
    unfold reconstructionWeight
    exact hout i hi
  have hcap : spectralCapture (fun i ↦ reconstructionWeight (spectrum i)) M ≤
      spectralCapture (fun i ↦ reconstructionWeight (spectrum i))
        (pruneAllocation S) := by
    rw [spectralCapture_pruneAllocation]
    exact spectralCapture_le_of_threshold
      (fun i ↦ reconstructionWeight (spectrum i)) M S t hM hin' hout'
  have hnonneg : 0 ≤ spectralTotal (fun i ↦ reconstructionWeight (spectrum i)) :=
    spectralTotal_nonneg (fun i ↦ le_of_lt (hpos i))
  unfold reconstructionEfficiency
  rcases eq_or_lt_of_le hnonneg with hzero | htotal
  · rw [← hzero]
    simp
  · exact captureRatio_le_of_le hcap htotal

/-- **Variance-greedy reduction minimises detection efficiency.**

*The pruning prohibition.*  Among all relaxed rank-`k` reductions of the same
background, the one that keeps the top `k` directions by variance — the
eigenbasis form of LD pruning and clumping — captures the least detection weight
of any of them.  It is not merely suboptimal for detection; it is the extreme
point in the wrong direction.

Together with `topVariance_maximizes_reconstruction` this is the trade-off in
its sharpest form: the single reduction that is best for reconstruction is
simultaneously worst for detection, at every rank. -/
theorem topVariance_minimizes_detection
    (spectrum M : ι → ℝ) (S : Finset ι) (t : ℝ)
    (hpos : ∀ i, 0 < spectrum i) (ht : 0 < t)
    (hM : IsRankAllocation (S.card : ℝ) M)
    (hin : ∀ i ∈ S, t ≤ spectrum i)
    (hout : ∀ i ∉ S, spectrum i ≤ t) :
    detectionEfficiency spectrum (pruneAllocation S) ≤
      detectionEfficiency spectrum M := by
  obtain ⟨hlow, hhigh⟩ :=
    detection_threshold_of_variance_threshold spectrum S t hpos ht hin hout
  have hcap : spectralCapture (fun i ↦ detectionWeight (spectrum i))
      (pruneAllocation S) ≤
      spectralCapture (fun i ↦ detectionWeight (spectrum i)) M := by
    rw [spectralCapture_pruneAllocation]
    exact spectralCapture_ge_of_threshold
      (fun i ↦ detectionWeight (spectrum i)) M S (detectionWeight t) hM hlow hhigh
  have hnonneg : 0 ≤ spectralTotal (fun i ↦ detectionWeight (spectrum i)) :=
    spectralTotal_nonneg (fun i ↦ le_of_lt (inv_pos.mpr (hpos i)))
  unfold detectionEfficiency
  rcases eq_or_lt_of_le hnonneg with hzero | htotal
  · rw [← hzero]
    simp
  · exact captureRatio_le_of_le hcap htotal

/-!
### The frontier itself

Both efficiencies are affine in `M` and the feasible set is convex, so the
achievable region in the `(reconstruction, detection)` plane is convex; its
upper-right boundary is therefore a concave curve.  The scalarisation theorem
below says that every supporting line of that curve is attained at a coordinate
split — a threshold set of the combined score `λσ + μ/σ`.  That is the content
of "the extreme solutions are coordinate splits with at most one fractional
index"; the fractional index appears only when the score has a tie at the
threshold, which is exactly when the threshold set of a given cardinality is not
unique.
-/

theorem spectralCapture_linear
    (w₁ w₂ M : ι → ℝ) (lam mu : ℝ) :
    spectralCapture (fun i ↦ lam * w₁ i + mu * w₂ i) M =
      lam * spectralCapture w₁ M + mu * spectralCapture w₂ M := by
  unfold spectralCapture
  calc ∑ i, M i * (lam * w₁ i + mu * w₂ i)
      = ∑ i, (lam * (M i * w₁ i) + mu * (M i * w₂ i)) :=
        Finset.sum_congr rfl (fun i _ ↦ by ring)
    _ = (∑ i, lam * (M i * w₁ i)) + ∑ i, mu * (M i * w₂ i) :=
        Finset.sum_add_distrib
    _ = lam * (∑ i, M i * w₁ i) + mu * ∑ i, M i * w₂ i := by
        rw [← Finset.mul_sum, ← Finset.mul_sum]

/-- The relaxed feasible set is convex. -/
theorem isRankAllocation_convex {k lam : ℝ} {M N : ι → ℝ}
    (hM : IsRankAllocation k M) (hN : IsRankAllocation k N)
    (h0 : 0 ≤ lam) (h1 : lam ≤ 1) :
    IsRankAllocation k (fun i ↦ lam * M i + (1 - lam) * N i) := by
  refine ⟨?_, ?_, ?_⟩
  · intro i
    show 0 ≤ lam * M i + (1 - lam) * N i
    have hA : 0 ≤ lam * M i := mul_nonneg h0 (hM.lower i)
    have hB : 0 ≤ (1 - lam) * N i :=
      mul_nonneg (by linarith : (0:ℝ) ≤ 1 - lam) (hN.lower i)
    linarith
  · intro i
    show lam * M i + (1 - lam) * N i ≤ 1
    have hA : lam * M i ≤ lam * 1 := mul_le_mul_of_nonneg_left (hM.upper i) h0
    have hB : (1 - lam) * N i ≤ (1 - lam) * 1 :=
      mul_le_mul_of_nonneg_left (hN.upper i) (by linarith)
    linarith
  · calc ∑ i, (lam * M i + (1 - lam) * N i)
        = (∑ i, lam * M i) + ∑ i, (1 - lam) * N i := Finset.sum_add_distrib
      _ = lam * (∑ i, M i) + (1 - lam) * ∑ i, N i := by
          rw [← Finset.mul_sum, ← Finset.mul_sum]
      _ = k := by rw [hM.trace, hN.trace]; ring

/-- Captured weight is affine along segments of the feasible set; hence so are
both efficiencies, and hence the achievable region is convex. -/
theorem spectralCapture_affine (w M N : ι → ℝ) (lam : ℝ) :
    spectralCapture w (fun i ↦ lam * M i + (1 - lam) * N i) =
      lam * spectralCapture w M + (1 - lam) * spectralCapture w N := by
  unfold spectralCapture
  calc ∑ i, (lam * M i + (1 - lam) * N i) * w i
      = ∑ i, (lam * (M i * w i) + (1 - lam) * (N i * w i)) :=
        Finset.sum_congr rfl (fun i _ ↦ by ring)
    _ = (∑ i, lam * (M i * w i)) + ∑ i, (1 - lam) * (N i * w i) :=
        Finset.sum_add_distrib
    _ = lam * (∑ i, M i * w i) + (1 - lam) * ∑ i, N i * w i := by
        rw [← Finset.mul_sum, ← Finset.mul_sum]

/-- **Every scalarisation of the two tasks is maximised by a coordinate
split.**

Given nonnegative task priorities `lam` (reconstruction) and `mu` (detection),
the combined objective is maximised over relaxed rank-`k` allocations by the
threshold set of the combined score `lam * σ + mu / σ`.  Since every supporting
line of the achievable region's upper boundary is such a scalarisation, the
Pareto frontier is carried entirely by these threshold allocations — the
"coordinate splits" of the statement.

Note the shape of the combined score: it is a *sum* of an increasing and a
decreasing function of `σ`, so its threshold sets are in general neither a
prefix nor a suffix of the variance ordering.  That is the precise sense in
which a reduction that serves both tasks is neither pruning nor its opposite. -/
theorem scalarized_optimum_is_coordinate_split
    (spectrum M : ι → ℝ) (S : Finset ι) (lam mu t : ℝ)
    (hM : IsRankAllocation (S.card : ℝ) M)
    (hin : ∀ i ∈ S,
      t ≤ lam * reconstructionWeight (spectrum i) +
        mu * detectionWeight (spectrum i))
    (hout : ∀ i ∉ S,
      lam * reconstructionWeight (spectrum i) +
        mu * detectionWeight (spectrum i) ≤ t) :
    lam * spectralCapture (fun i ↦ reconstructionWeight (spectrum i)) M +
        mu * spectralCapture (fun i ↦ detectionWeight (spectrum i)) M ≤
      lam * spectralCapture (fun i ↦ reconstructionWeight (spectrum i))
          (pruneAllocation S) +
        mu * spectralCapture (fun i ↦ detectionWeight (spectrum i))
          (pruneAllocation S) := by
  have hcombM := spectralCapture_linear
    (fun i ↦ reconstructionWeight (spectrum i))
    (fun i ↦ detectionWeight (spectrum i)) M lam mu
  have hcombS := spectralCapture_linear
    (fun i ↦ reconstructionWeight (spectrum i))
    (fun i ↦ detectionWeight (spectrum i)) (pruneAllocation S) lam mu
  have hthr := spectralCapture_le_of_threshold
    (fun i ↦ lam * reconstructionWeight (spectrum i) +
      mu * detectionWeight (spectrum i)) M S t hM hin hout
  rw [spectralCapture_pruneAllocation] at hcombS
  rw [hcombM] at hthr
  rw [← hcombS]
  exact hthr

/-!
### The two-coordinate frontier, in closed form

Two directions, rank one.  Here the frontier is not merely concave — it is an
exact straight line, and the trade-off is a conservation law: reconstruction
efficiency and detection efficiency sum to one, for *every* allocation.  Spend a
fraction `m` of the single retained dimension on the high-variance direction and
you have spent `1 - m` of it on detection.  There is no allocation, fractional
or not, that escapes.
-/

/-- **Exact two-coordinate frontier.**  For a two-direction background with
variances `σ₁, σ₂` and a rank-one budget split as `(m, 1 - m)`, the
reconstruction and detection efficiencies sum to exactly `1`.

The trade-off is therefore not asymptotic, not a large-`n` phenomenon, and not
an artefact of relaxation: it holds at every `m`, including the two integral
endpoints `m = 1` (pure pruning) and `m = 0` (pure whitening). -/
theorem twoCoordinate_frontier_line
    (σ₁ σ₂ m : ℝ) (h₁ : 0 < σ₁) (h₂ : 0 < σ₂) :
    (m * σ₁ + (1 - m) * σ₂) / (σ₁ + σ₂) +
        (m * σ₁⁻¹ + (1 - m) * σ₂⁻¹) / (σ₁⁻¹ + σ₂⁻¹) = 1 := by
  have hu : σ₁ * σ₁⁻¹ = 1 := mul_inv_cancel₀ (ne_of_gt h₁)
  have hv : σ₂ * σ₂⁻¹ = 1 := mul_inv_cancel₀ (ne_of_gt h₂)
  have hS : σ₁ + σ₂ ≠ 0 := ne_of_gt (add_pos h₁ h₂)
  have hT : σ₁⁻¹ + σ₂⁻¹ ≠ 0 :=
    ne_of_gt (add_pos (inv_pos.mpr h₁) (inv_pos.mpr h₂))
  rw [div_add_div _ _ hS hT, div_eq_iff (mul_ne_zero hS hT)]
  linear_combination (2 * m - 1) * hu + (1 - 2 * m) * hv

/-- The two-coordinate frontier lies strictly inside the unit box whenever both
directions carry variance: perfect reconstruction efficiency is unattainable at
rank one, and so is perfect detection efficiency.  The pruning corner `m = 1`
attains reconstruction efficiency `σ₁ / (σ₁ + σ₂)` and, by
`twoCoordinate_frontier_line`, detection efficiency `σ₂ / (σ₁ + σ₂)` — which for
a strongly correlated pair (`σ₁ ≫ σ₂`) is close to zero. -/
theorem twoCoordinate_pruning_corner_lt_one
    (σ₁ σ₂ : ℝ) (h₁ : 0 < σ₁) (h₂ : 0 < σ₂) :
    σ₁ / (σ₁ + σ₂) < 1 := by
  rw [div_lt_one (add_pos h₁ h₂)]
  linarith

/-- **A score profile admits threshold sets at every rank**: for each `k` there
is a set of `k` indices, no more and no fewer, separated from its complement by
a cut value.

This is the one ingredient the frontier packaging needs beyond the analytic
lemmas above.  It is not an empirical assumption or an external input: it holds
for every score on a finite type.  The proof below chooses, among all `k`-sets,
one maximizing total score.  Exchanging a selected minimum with a larger
unselected value would improve that maximum, so the selected and unselected
values are separated by the minimum selected score.

What is proved without it: every threshold set is a scalarised optimum
(`scalarized_optimum_is_coordinate_split`), so every supporting line of the
achievable region that is attained at all is attained by a coordinate split, and
the region is convex (`isRankAllocation_convex`, `spectralCapture_affine`).
What needs it: that a supporting line exists in every direction, i.e. that the
frontier is the concave envelope of the split values rather than merely bounded
by it.

Empirical status: UNTESTED — and untestable, being a finite-combinatorial
statement rather than a claim about genotypes. -/
def HasThresholdSetAtEveryRank (score : ι → ℝ) : Prop :=
  ∀ k : ℕ, k ≤ Fintype.card ι →
    ∃ (S : Finset ι) (t : ℝ), S.card = k ∧
      (∀ i ∈ S, t ≤ score i) ∧ (∀ i ∉ S, score i ≤ t)

/-- Constant scores have a threshold set at every rank: every subset of the
right size works and the cut is at the common value. -/
theorem hasThresholdSetAtEveryRank_const (c : ℝ) :
    HasThresholdSetAtEveryRank (fun _ : ι ↦ c) := by
  intro k hk
  obtain ⟨S, -, hS⟩ :=
    Finset.exists_subset_card_eq
      (s := (Finset.univ : Finset ι)) (n := k) (by simpa [Finset.card_univ] using hk)
  exact ⟨S, c, hS, fun _ _ ↦ le_rfl, fun _ _ ↦ le_rfl⟩

/-- **Every score on a finite type has a threshold set at every rank.**

The maximizing-set proof works with ties and requires no order on the index
type.  At rank zero the cut is a maximum score (or arbitrary when the type is
empty).  At positive rank, the cut is the minimum score in a maximum-total-score
`k`-set. -/
theorem hasThresholdSetAtEveryRank_of_fintype (score : ι → ℝ) :
    HasThresholdSetAtEveryRank score := by
  intro k hk
  have hcandidates : ((Finset.univ : Finset ι).powersetCard k).Nonempty :=
    Finset.powersetCard_nonempty.mpr (by simpa [Finset.card_univ] using hk)
  obtain ⟨S, hSmem, hSmax⟩ :=
    ((Finset.univ : Finset ι).powersetCard k).exists_max_image
      (fun T ↦ ∑ i ∈ T, score i) hcandidates
  have hScard : S.card = k := (Finset.mem_powersetCard.mp hSmem).2
  by_cases hk0 : k = 0
  · have hSempty : S = ∅ := Finset.card_eq_zero.mp (hScard.trans hk0)
    subst S
    by_cases hι : (Finset.univ : Finset ι).Nonempty
    · obtain ⟨i, -, himax⟩ :=
        (Finset.univ : Finset ι).exists_max_image score hι
      exact ⟨∅, score i, by simpa [hk0], by simp,
        fun j _ ↦ himax j (Finset.mem_univ j)⟩
    · refine ⟨∅, 0, by simpa [hk0], by simp, ?_⟩
      intro j _
      exact False.elim (hι ⟨j, Finset.mem_univ j⟩)
  · have hSnonempty : S.Nonempty := Finset.card_pos.mp (by omega)
    obtain ⟨i, hiS, himin⟩ := S.exists_min_image score hSnonempty
    refine ⟨S, score i, hScard, himin, ?_⟩
    intro j hjS
    by_contra hji
    have hij : score i < score j := lt_of_not_ge hji
    let T := insert j (S.erase i)
    have hjErase : j ∉ S.erase i := by simp [hjS]
    have hTcard : T.card = k := by
      simp [T, hjErase, hiS, hScard]
      omega
    have hTmem : T ∈ (Finset.univ : Finset ι).powersetCard k :=
      Finset.mem_powersetCard.mpr ⟨Finset.subset_univ T, hTcard⟩
    have hmax := hSmax T hTmem
    have hsumErase :
        (∑ x ∈ S.erase i, score x) + score i = ∑ x ∈ S, score x := by
      exact Finset.sum_erase_add _ _ hiS
    have hsumT :
        (∑ x ∈ T, score x) = (∑ x ∈ S.erase i, score x) + score j := by
      simp [T, hjErase, add_comm]
    rw [hsumT] at hmax
    linarith

/-- **The frontier is carried by coordinate splits of the prescribed rank.**

For every pair of task priorities there is a single set of exactly `k` retained
directions whose scalarised value is at least that of *every* relaxed rank-`k`
allocation.  Combined with convexity of the achievable region this is the
statement that the Pareto frontier is the concave envelope of the
coordinate-split values.

The existence of the threshold set is supplied by
`hasThresholdSetAtEveryRank_of_fintype`, which is proved: a maximum-total-score
`k`-set has its own minimum as a cut, since swapping in any higher-scoring
outsider would raise the total. -/
theorem exists_split_attaining_scalarized_optimum
    (spectrum : ι → ℝ) (k : ℕ) (lam mu : ℝ) (hk : k ≤ Fintype.card ι) :
    ∃ S : Finset ι, S.card = k ∧
      ∀ M : ι → ℝ, IsRankAllocation (k : ℝ) M →
        lam * spectralCapture (fun i ↦ reconstructionWeight (spectrum i)) M +
            mu * spectralCapture (fun i ↦ detectionWeight (spectrum i)) M ≤
          lam * spectralCapture (fun i ↦ reconstructionWeight (spectrum i))
              (pruneAllocation S) +
            mu * spectralCapture (fun i ↦ detectionWeight (spectrum i))
              (pruneAllocation S) := by
  obtain ⟨S, t, hcard, hin, hout⟩ :=
    hasThresholdSetAtEveryRank_of_fintype
      (fun i ↦ lam * reconstructionWeight (spectrum i) +
        mu * detectionWeight (spectrum i)) k hk
  refine ⟨S, hcard, ?_⟩
  intro M hM
  have hM' : IsRankAllocation (S.card : ℝ) M := by
    rw [hcard]
    exact hM
  exact scalarized_optimum_is_coordinate_split spectrum M S lam mu t hM' hin hout

end DetectionReconstructionFrontier

/-!
## Rescaling is removable, rotation is not

A predictor `beta` carried to a new population is wrong in two separable ways.
It can be wrong in *scale*, and it can be wrong in *direction*.  This section
proves that the first costs nothing that a single scalar cannot undo, and the
second costs a quantity no scalar can touch — the target-metric angle between
the transported direction and the target truth, scaled by target signal energy.

That is the formal content behind `MetricSpecificPortability`'s
`recalibration_easier_than_rediscovery`: recalibration searches the orbit
`{a * beta}`, and `irreducibleDegradation` is exactly what that orbit cannot
reach.

Everything is stated over the corpus's own second-moment objects: `B` is
instantiated at `secondMomentMatrix` or `covarianceMatrix` of the target
population, `beta` is the transported coefficient vector and `theta` the target
optimum.  No abstract covariance is introduced.
-/

section RescalingAndRotation

/-- Rescaling a coefficient vector scales its energy by the square.

Stated with `•` rather than `fun i ↦ c * x i` so that the scalar-multiplication
lemmas of `Calibrator.QuadraticShift` apply on the nose. -/
theorem coefficientEnergy_smul (B : Matrix ι ι ℝ) (c : ℝ) (x : ι → ℝ) :
    coefficientEnergy B (c • x) = c ^ 2 * coefficientEnergy B x := by
  unfold coefficientEnergy
  rw [matrix_mulVec_smul, dot_smul_left, dot_smul_right]
  ring

/-- The `show`/`ring` in the conversion below is deliberate and should not be
shortened back to `simp`.

`simp` reduces the goal to `x i - y i = x i + -y i` and stops: closing it means
reconciling `a - b` with `a + -b`, which is a question about simp's normal form
rather than a fact, and it went the wrong way here. Stating the arithmetic goal
with `show` — where the `•` unfolds definitionally, exactly as the sibling
conversion in `coefficientEnergy_rescaled_expand` discharges with `rfl` — and
closing with `ring` depends on nobody's normal form. -/
theorem coefficientEnergy_sub (B : Matrix ι ι ℝ) (x y : ι → ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B) :
    coefficientEnergy B (fun i ↦ x i - y i) =
      coefficientEnergy B x + coefficientEnergy B y -
        2 * dot x (B.mulVec y) := by
  have hrw : (fun i ↦ x i - y i) = (fun i ↦ x i + ((-1 : ℝ) • y) i) := by
    funext i
    show x i - y i = x i + (-1 : ℝ) * y i
    ring
  rw [hrw, coefficientEnergy_add B x ((-1 : ℝ) • y) hsymmetric,
    coefficientEnergy_smul, matrix_mulVec_smul, dot_smul_right]
  ring

/-- **Excess risk along the recalibration orbit.**  Expanding the energy of
`a * beta - theta` in the target metric gives a quadratic in the single scalar
`a`; every statement below is about that quadratic. -/
theorem coefficientEnergy_rescaled_expand
    (B : Matrix ι ι ℝ) (beta theta : ι → ℝ) (a : ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B) :
    coefficientEnergy B (fun i ↦ a * beta i - theta i) =
      a ^ 2 * coefficientEnergy B beta -
        2 * a * dot beta (B.mulVec theta) + coefficientEnergy B theta := by
  have hrw : (fun i ↦ a * beta i - theta i) =
      (fun i ↦ (a • beta) i - theta i) := by
    funext i
    rfl
  rw [hrw, coefficientEnergy_sub B (a • beta) theta hsymmetric,
    coefficientEnergy_smul, dot_smul_left]
  ring

/-- **The optimal recalibration of a transported predictor for one target.**

`a* = (beta' B theta) / (beta' B beta)`, the scalar that best rescales the
transported direction `beta` towards the target optimum `theta` in the target
metric `B`.  This is the correction a recalibration step finds.

Empirical status: UNTESTED. -/
def sharedCorrectionOptimum (B : Matrix ι ι ℝ) (beta theta : ι → ℝ) : ℝ :=
  dot beta (B.mulVec theta) / coefficientEnergy B beta

/-- **The part of the degradation no rescaling can remove.**

`theta' B theta - (beta' B theta)^2 / (beta' B beta)`, which is the target
signal energy times the squared sine of the `B`-angle between `beta` and
`theta`.  It vanishes when the transported direction is `B`-parallel to the
target truth and is strictly positive otherwise.

Empirical status: UNTESTED. -/
def irreducibleDegradation (B : Matrix ι ι ℝ) (beta theta : ι → ℝ) : ℝ :=
  coefficientEnergy B theta -
    dot beta (B.mulVec theta) ^ 2 / coefficientEnergy B beta

/-- **No rescaling reaches below the angle term.**  The recalibration orbit
`{a * beta}` is bounded below by `irreducibleDegradation`, uniformly in `a`. -/
theorem irreducibleDegradation_le_rescaled
    (B : Matrix ι ι ℝ) (beta theta : ι → ℝ) (a : ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B)
    (hbeta : 0 < coefficientEnergy B beta) :
    irreducibleDegradation B beta theta ≤
      coefficientEnergy B (fun i ↦ a * beta i - theta i) := by
  rw [coefficientEnergy_rescaled_expand B beta theta a hsymmetric]
  have hkey : 2 * a * dot beta (B.mulVec theta) -
      a ^ 2 * coefficientEnergy B beta ≤
      dot beta (B.mulVec theta) ^ 2 / coefficientEnergy B beta := by
    rw [le_div_iff₀ hbeta]
    nlinarith [sq_nonneg (a * coefficientEnergy B beta -
      dot beta (B.mulVec theta))]
  unfold irreducibleDegradation
  linarith

/-- **And the bound is attained, at the optimal recalibration.**  So
`irreducibleDegradation` is the value of the recalibration problem, not merely a
lower bound for it. -/
theorem rescaled_at_optimum_eq_irreducibleDegradation
    (B : Matrix ι ι ℝ) (beta theta : ι → ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B)
    (hbeta : 0 < coefficientEnergy B beta) :
    coefficientEnergy B
        (fun i ↦ sharedCorrectionOptimum B beta theta * beta i - theta i) =
      irreducibleDegradation B beta theta := by
  rw [coefficientEnergy_rescaled_expand B beta theta _ hsymmetric]
  unfold sharedCorrectionOptimum irreducibleDegradation
  have hu : coefficientEnergy B beta * (coefficientEnergy B beta)⁻¹ = 1 :=
    mul_inv_cancel₀ (ne_of_gt hbeta)
  linear_combination
    (dot beta (B.mulVec theta) ^ 2 * (coefficientEnergy B beta)⁻¹) * hu

/-- **The degradation splits into a removable part and a class, and the
removable part is a perfect square.**

Degradation at correction `a` minus the angle term equals
`(beta' B beta) * (a - a*)^2`: the coboundary is the squared distance from the
correction actually applied to the correction that target wanted, weighted by
the transported direction's energy in the target metric.

Three consequences, and this is why the identity is worth having rather than
the three statements separately: the removable part is nonnegative; it is zero
when `a = a*`; and it is zero *only* then, so recalibration removes the whole
coboundary and nothing of the class.  A predictor that is merely mis-scaled has
degradation entirely of the first kind; a rotated predictor has degradation of
the second, and refitting rather than recalibration is the only remedy. -/
theorem rescaled_energy_sub_irreducible_eq_sq
    (B : Matrix ι ι ℝ) (beta theta : ι → ℝ) (a : ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B)
    (hbeta : 0 < coefficientEnergy B beta) :
    coefficientEnergy B (fun i ↦ a * beta i - theta i) -
        irreducibleDegradation B beta theta =
      coefficientEnergy B beta *
        (a - sharedCorrectionOptimum B beta theta) ^ 2 := by
  rw [coefficientEnergy_rescaled_expand B beta theta a hsymmetric]
  unfold sharedCorrectionOptimum irreducibleDegradation
  have hu : coefficientEnergy B beta * (coefficientEnergy B beta)⁻¹ = 1 :=
    mul_inv_cancel₀ (ne_of_gt hbeta)
  linear_combination
    (2 * a * dot beta (B.mulVec theta) -
      dot beta (B.mulVec theta) ^ 2 * (coefficientEnergy B beta)⁻¹) * hu

/-- The removable part is nonnegative, so the split is a decomposition into two
nonnegative pieces rather than a cancellation. -/
theorem removable_part_nonneg
    (B : Matrix ι ι ℝ) (beta theta : ι → ℝ) (a : ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B)
    (hbeta : 0 < coefficientEnergy B beta) :
    0 ≤ coefficientEnergy B (fun i ↦ a * beta i - theta i) -
      irreducibleDegradation B beta theta := by
  rw [rescaled_energy_sub_irreducible_eq_sq B beta theta a hsymmetric hbeta]
  exact mul_nonneg (le_of_lt hbeta) (sq_nonneg _)

/-- **Recalibration removes the coboundary and only the coboundary.**  The
degradation drops to the angle term exactly when the correction applied is the
one that target wanted; any other scalar leaves a strictly positive remainder on
top of the irreducible part. -/
theorem rescaled_eq_irreducible_iff_optimal
    (B : Matrix ι ι ℝ) (beta theta : ι → ℝ) (a : ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B)
    (hbeta : 0 < coefficientEnergy B beta) :
    coefficientEnergy B (fun i ↦ a * beta i - theta i) =
        irreducibleDegradation B beta theta ↔
      a = sharedCorrectionOptimum B beta theta := by
  have hfactor :=
    rescaled_energy_sub_irreducible_eq_sq B beta theta a hsymmetric hbeta
  constructor
  · intro hEq
    have hzero : coefficientEnergy B beta *
        (a - sharedCorrectionOptimum B beta theta) ^ 2 = 0 := by
      rw [← hfactor, hEq, sub_self]
    have hsq : (a - sharedCorrectionOptimum B beta theta) ^ 2 = 0 := by
      rcases mul_eq_zero.mp hzero with hcase | hcase
      · exact absurd hcase (ne_of_gt hbeta)
      · exact hcase
    have hdiff : a - sharedCorrectionOptimum B beta theta = 0 :=
      sq_eq_zero_iff.mp hsq
    linarith
  · intro hEq
    have hzero : coefficientEnergy B beta *
        (a - sharedCorrectionOptimum B beta theta) ^ 2 = 0 := by
      rw [hEq, sub_self]
      norm_num
    linarith [hfactor, hzero]

end RescalingAndRotation

end

end Calibrator
