import Calibrator.SecondMomentShift
import Calibrator.QuadraticShift
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

namespace Calibrator

noncomputable section

/-!
# Discrepancy--curvature bounds for projection movement

This module isolates the analytic engine behind sharp projection-artifact
bounds.  The expectation abstraction used by the project is only linear, so
Cauchy--Schwarz and positivity are stated explicitly.  Actual probability
measures discharge those hypotheses in the usual `L²` space.
-/

variable {Ω ι : Type*} [Fintype ι] [DecidableEq ι]

/-- Squared `L²` magnitude of a density-ratio perturbation. -/
def chiSquareBudget (P : ExpFunctional Ω) (densityRatio : Ω → ℝ) : ℝ :=
  P (fun ω => (densityRatio ω - 1) ^ 2)

/-- Residual curvature seen along a coefficient direction. -/
def directionalResidualCurvature (P : ExpFunctional Ω)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ) (direction : ι → ℝ) : ℝ :=
  P (fun ω => (dot direction (X ω) * residual ω) ^ 2)

/-- Moment movement generated by reweighting a residual with a density ratio. -/
def weightedResidualMoment (P : ExpFunctional Ω)
    (densityRatio : Ω → ℝ) (X : Ω → ι → ℝ)
    (residual : Ω → ℝ) : ι → ℝ :=
  rawCrossMoment P X (fun ω => (densityRatio ω - 1) * residual ω)

/-- Pairing the shifted residual moment with a direction is exactly the scalar
`L²` pairing to which Cauchy--Schwarz applies. -/
theorem dot_weightedResidualMoment
    (P : ExpFunctional Ω) (densityRatio : Ω → ℝ)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ) (direction : ι → ℝ) :
    dot direction (weightedResidualMoment P densityRatio X residual) =
      P (fun ω =>
        (densityRatio ω - 1) * (dot direction (X ω) * residual ω)) := by
  unfold weightedResidualMoment rawCrossMoment dot
  have hexpand :
      (fun ω =>
        (densityRatio ω - 1) *
          ((∑ i, direction i * X ω i) * residual ω)) =
        ∑ i, (direction i) •
          (fun ω => X ω i * ((densityRatio ω - 1) * residual ω)) := by
    funext ω
    calc
      (densityRatio ω - 1) *
          ((∑ i, direction i * X ω i) * residual ω) =
          ((densityRatio ω - 1) * residual ω) *
            ∑ i, direction i * X ω i := by ring
      _ = ∑ i, ((densityRatio ω - 1) * residual ω) *
            (direction i * X ω i) := by rw [Finset.mul_sum]
      _ = ∑ i, (direction i) •
            (fun ω => X ω i * ((densityRatio ω - 1) * residual ω)) ω := by
          apply Finset.sum_congr rfl
          intro i _
          simp only [smul_eq_mul]
          ring
      _ = (∑ i, (direction i) •
            (fun ω => X ω i * ((densityRatio ω - 1) * residual ω))) ω := by
          simp only [Finset.sum_apply, Pi.smul_apply]
  rw [hexpand, ExpFunctional.eval_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [P.smul_eval]

/-- Directional chi-square bound.  This is the exact product of distributional
discrepancy and residual nonlinearity before optimizing over directions. -/
theorem weighted_residual_moment_directional_bound
    (P : ExpFunctional Ω) (densityRatio : Ω → ℝ)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ) (direction : ι → ℝ)
    (hCauchySchwarz : ∀ f g : Ω → ℝ,
      P (fun ω => f ω * g ω) ^ 2 ≤
        P (fun ω => f ω ^ 2) * P (fun ω => g ω ^ 2)) :
    dot direction (weightedResidualMoment P densityRatio X residual) ^ 2 ≤
      chiSquareBudget P densityRatio *
        directionalResidualCurvature P X residual direction := by
  rw [dot_weightedResidualMoment]
  exact hCauchySchwarz
    (fun ω => densityRatio ω - 1)
    (fun ω => dot direction (X ω) * residual ω)

/-- Quadratic energy associated with a second-moment matrix. -/
def coefficientEnergy (B : Matrix ι ι ℝ) (x : ι → ℝ) : ℝ :=
  dot x (B.mulVec x)

theorem dot_add_right_shift (x y z : ι → ℝ) :
    dot x (y + z) = dot x y + dot x z := by
  simp [dot, mul_add, Finset.sum_add_distrib]

/-- Sharp discrepancy--curvature product bound for projection artifacts.

`B a = g` is the residual-score equation for the coefficient movement `a`.
The curvature-domination hypothesis is the generalized Rayleigh bound
`M ≤ Λ B` evaluated in the relevant direction.  The conclusion is the full
quadratic excess-risk bound, with no invertibility assumption on `B`. -/
theorem projection_artifact_energy_le_chiSquare_mul_curvature
    (P : ExpFunctional Ω) (densityRatio : Ω → ℝ)
    (X : Ω → ι → ℝ) (residual : Ω → ℝ)
    (B : Matrix ι ι ℝ) (artifact : ι → ℝ) (Λ : ℝ)
    (hmoment : B.mulVec artifact =
      weightedResidualMoment P densityRatio X residual)
    (hCauchySchwarz : ∀ f g : Ω → ℝ,
      P (fun ω => f ω * g ω) ^ 2 ≤
        P (fun ω => f ω ^ 2) * P (fun ω => g ω ^ 2))
    (henergy : 0 ≤ coefficientEnergy B artifact)
    (hchiSquare : 0 ≤ chiSquareBudget P densityRatio)
    (hΛ : 0 ≤ Λ)
    (hcurvature : directionalResidualCurvature P X residual artifact ≤
      Λ * coefficientEnergy B artifact) :
    coefficientEnergy B artifact ≤ chiSquareBudget P densityRatio * Λ := by
  have hdirectional := weighted_residual_moment_directional_bound
    P densityRatio X residual artifact hCauchySchwarz
  have hpairing :
      dot artifact (weightedResidualMoment P densityRatio X residual) =
        coefficientEnergy B artifact := by
    unfold coefficientEnergy
    rw [← hmoment]
  rw [hpairing] at hdirectional
  have hproduct :
      chiSquareBudget P densityRatio *
          directionalResidualCurvature P X residual artifact ≤
        chiSquareBudget P densityRatio *
          (Λ * coefficientEnergy B artifact) :=
    mul_le_mul_of_nonneg_left hcurvature hchiSquare
  have hquadratic :
      coefficientEnergy B artifact ^ 2 ≤
        (chiSquareBudget P densityRatio * Λ) *
          coefficientEnergy B artifact := by
    calc
      coefficientEnergy B artifact ^ 2
          ≤ chiSquareBudget P densityRatio *
              directionalResidualCurvature P X residual artifact := hdirectional
      _ ≤ chiSquareBudget P densityRatio *
              (Λ * coefficientEnergy B artifact) := hproduct
      _ = (chiSquareBudget P densityRatio * Λ) *
              coefficientEnergy B artifact := by ring
  by_cases hzero : coefficientEnergy B artifact = 0
  · rw [hzero]
    exact mul_nonneg hchiSquare hΛ
  · have hpositive : 0 < coefficientEnergy B artifact :=
      lt_of_le_of_ne henergy (Ne.symm hzero)
    nlinarith

/-- Under identifiability of the target second-moment operator, the moment-level
genuine/artifact decomposition uniquely lifts to coefficient space.  This is
the precise point at which nonsingularity is required: all preceding moment and
risk identities remain valid without it. -/
theorem projection_shift_eq_genuine_add_artifact
    (Q : ExpFunctional Ω) (X : Ω → ι → ℝ)
    (hOld hNew : Ω → ℝ) (u v genuine artifact : ι → ℝ)
    (htarget : residualScoreMoment Q X hNew v = 0)
    (hgenuine : (secondMomentMatrix Q X).mulVec genuine =
      rawCrossMoment Q X (fun ω => hNew ω - hOld ω))
    (hartifact : (secondMomentMatrix Q X).mulVec artifact =
      residualScoreMoment Q X hOld u)
    (hinjective : Function.Injective (secondMomentMatrix Q X).mulVec) :
    (fun i => v i - u i) = fun i => genuine i + artifact i := by
  apply hinjective
  rw [projection_shift_genuine_artifact_decomposition Q X hOld hNew u v htarget]
  rw [matrix_mulVec_add, hgenuine, hartifact]

/-- Exact energy expansion for the sum of a genuine component and a projection
artifact. -/
theorem coefficientEnergy_add
    (B : Matrix ι ι ℝ) (x y : ι → ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B) :
    coefficientEnergy B (fun i => x i + y i) =
      coefficientEnergy B x + coefficientEnergy B y +
        2 * dot x (B.mulVec y) := by
  unfold coefficientEnergy
  rw [matrix_mulVec_add, dot_add_left]
  rw [dot_add_right_shift, dot_add_right_shift]
  rw [hsymmetric y x]
  ring

/-- Risk-level genuine/artifact decomposition with sharp norm budgets.  If the
cross term obeys the corresponding Cauchy--Schwarz budget, total movement is
bounded by the square of the sum of component budgets. -/
theorem total_shift_energy_le_sum_budget_sq
    (B : Matrix ι ι ℝ) (genuine artifact : ι → ℝ)
    (genuineBudget artifactBudget : ℝ)
    (hsymmetric : IsSymmetricBilinearMatrix B)
    (hgenuine : coefficientEnergy B genuine ≤ genuineBudget ^ 2)
    (hartifact : coefficientEnergy B artifact ≤ artifactBudget ^ 2)
    (hcross : dot genuine (B.mulVec artifact) ≤
      genuineBudget * artifactBudget) :
    coefficientEnergy B (fun i => genuine i + artifact i) ≤
      (genuineBudget + artifactBudget) ^ 2 := by
  rw [coefficientEnergy_add B genuine artifact hsymmetric]
  nlinarith

end

end Calibrator
