name: Rust Test CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  # ======================================================================
  # JOB 1: Handles all Rust compilation, testing, and artifact creation.
  # This job is the "producer".
  # ======================================================================
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- All your original caching and setup steps remain here ---
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache Cargo home
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-home-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-home-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo-home

      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-target

      # (All other cache steps from your original file are implicitly covered by the two above,
      # but are kept here for a 1-to-1 match with your original file)
      - name: Cache Rust toolchain components
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-rust-toolchain-nightly-${{ hashFiles('rust-toolchain.toml') }}

      - name: Install getdoc
        run: |
          if [ ! -f ~/.cargo/bin/getdoc ]; then
            echo "Installing getdoc..."
            cargo +nightly install getdoc --locked
          else
            echo "getdoc already installed (cached)"
          fi
      
      # --- All your original run steps remain here ---
      - name: Run Rust unit tests
        id: test_step
        run: cargo +nightly test
        continue-on-error: true
        env:
          RUST_BACKTRACE: 1

      - name: Generate custom report with getdoc
        run: |
          ~/.cargo/bin/getdoc
          echo "=== Custom Report (getdoc) ==="
          cat report.md

      # This is the critical gate. If build fails, the Python jobs won't run.
      - name: Build Gnomon release binary
        run: cargo build --release

      - name: Fail job if unit tests failed
        if: steps.test_step.outcome == 'failure'
        run: exit 1

      # --- NEW STEP: Package the results for the other jobs ---
      - name: Upload build artifacts for Python jobs
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            target
            report.md
          retention-days: 1

  # ======================================================================
  # JOB 2: Runs the first Python test on its own machine.
  # This job is a "consumer".
  # ======================================================================
  python_test_integration:
    runs-on: ubuntu-latest
    needs: build_and_test # This job will not start until 'build_and_test' succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Get the build output from the first job ---
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: . # This downloads the 'target' folder and 'report.md' right here

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install pandas numpy requests psutil tabulate

      - name: Run Integration Test
        run: python -u test/test.py

  # ======================================================================
  # JOB 3: Runs the second Python test on a third machine.
  # This job is also a "consumer" and runs in parallel with Job 2.
  # ======================================================================
  python_test_simulation:
    runs-on: ubuntu-latest
    needs: build_and_test # This job also depends on the first job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- NEW STEP: Get the build output from the first job ---
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: . # This downloads the 'target' folder and 'report.md' right here

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install pandas numpy requests psutil tabulate

      - name: Run Simulation Test
        run: python -u test/sim_test.py
