name: Rust Test CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # ======================================================================
  # JOB 1: Handles all Rust compilation, testing, and artifact creation.
  # ======================================================================
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Generate cache keys
        id: cache_keys
        run: |
          SOURCE_HASH=$(find . -name "Cargo.toml" -o -name "Cargo.lock" -o -path "./src/*" -type f | sort | xargs cat | sha256sum | cut -d' ' -f1)
          echo "source_hash=$SOURCE_HASH" >> $GITHUB_OUTPUT
          DEPS_HASH=$(find . -name "Cargo.toml" -o -name "Cargo.lock" | sort | xargs cat | sha256sum | cut -d' ' -f1)
          echo "deps_hash=$DEPS_HASH" >> $GITHUB_OUTPUT

      - name: Cache release binary
        uses: actions/cache@v4
        with:
          path: target/release/gnomon
          key: ${{ runner.os }}-release-binary-${{ steps.cache_keys.outputs.source_hash }}

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.cache_keys.outputs.deps_hash }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build artifacts
        uses: actions/cache@v4
        with:
          path: |
            target
            !target/release/gnomon
          key: ${{ runner.os }}-cargo-build-nightly-${{ steps.cache_keys.outputs.source_hash }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-nightly-${{ steps.cache_keys.outputs.deps_hash }}
            ${{ runner.os }}-cargo-build-nightly-

      - name: Build Gnomon binaries
        run: |
          if [ "${{ steps.binary_cache.outputs.cache-hit }}" != "true" ]; then
            echo "Binary cache miss - building release binary..."
            cargo build --release
          fi
          # Build using the new 'profiling' profile for perf analysis.
          echo "Building binary with profiling symbols..."
          cargo build --profile profiling

      - name: Verify cached binary
        if: steps.binary_cache.outputs.cache-hit == 'true'
        run: |
          echo "Binary cache hit - verifying cached binary..."
          ls -la target/release/gnomon
          chmod +x target/release/gnomon
          ./target/release/gnomon --version || echo "Binary verification complete"

      - name: Upload build artifacts for all downstream jobs
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          # Upload the entire target directory, which now includes 'release' and 'profiling'
          path: target
          retention-days: 1

  # ======================================================================
  # JOBS 2-4: Python tests (unchanged)
  # ======================================================================
  python_test_integration:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: build-output, path: . }
      - uses: actions/setup-python@v4
        with: { python-version: '3.13' }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-integration-${{ hashFiles('test/test.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-integration-
      - run: pip install pandas numpy requests psutil tabulate polars pyarrow
      - run: chmod +x target/release/gnomon
      - run: python -u test/test.py

  python_test_simulation:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: build-output, path: . }
      - uses: actions/setup-python@v4
        with: { python-version: '3.13' }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-simulation-${{ hashFiles('test/sim_test.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-simulation-
      - run: pip install pandas numpy requests psutil tabulate polars pyarrow gmpy2
      - run: chmod +x target/release/gnomon
      - id: sim_test
        run: python -u test/sim_test.py
      - if: failure()
        run: |
          echo "The simulation test failed. Checking for OOM errors in kernel logs..."
          sudo dmesg | grep -i -E 'killed process|out of memory' || echo "No OOM messages found."

  python_test_benchmark:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: build-output, path: . }
      - uses: actions/setup-python@v4
        with: { python-version: '3.13' }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-benchmark-${{ hashFiles('test/bench.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-benchmark-
      - run: pip install pandas numpy requests psutil tabulate polars pyarrow
      - run: chmod +x target/release/gnomon
      - run: python -u test/bench.py

  # ======================================================================
  # JOB 5: Performance Profiling (FIXED and ROBUST)
  # ======================================================================
  performance_reports:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: build-output, path: . }

      - name: Make profiling binary executable
        # Correct path for the new profile
        run: chmod +x target/profiling/gnomon

      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }

      - name: Install Python dependencies
        run: pip install pandas numpy requests psutil

      - name: Get Kernel Version for Cache Key
        id: kernel_version
        run: echo "version=$(uname -r)" >> $GITHUB_OUTPUT
      
      - name: Cache APT packages for perf
        id: apt_cache
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-perf-tools-cache-${{ steps.kernel_version.outputs.version }}

      - name: Install Perf Tools
        run: |
          echo "--- Installing Perf Tools ---"
          CURRENT_KERNEL=$(uname -r)
          echo "Identified running kernel: $CURRENT_KERNEL"
          REQUIRED_PACKAGES="linux-tools-common linux-tools-${CURRENT_KERNEL}"
          echo "Required packages: ${REQUIRED_PACKAGES}"
          
          if [ "${{ steps.apt_cache.outputs.cache-hit }}" != 'true' ]; then
            echo "APT cache miss, running apt-get update..."
            sudo apt-get update -y
          else
            echo "APT cache hit, skipping apt-get update."
          fi
          
          sudo apt-get install -y --no-install-recommends ${REQUIRED_PACKAGES}
          
          echo "--- Verifying Installation ---"
          echo "Location of perf: $(which perf || echo 'perf not found')"
          echo "Version of perf: $(perf --version || echo 'perf not found')"
          dpkg -l | grep 'linux-tools' || echo "No linux-tools packages found."

      - name: Configure Profiler Permissions
        run: |
          echo "--- Configuring Kernel Permissions for Profiling ---"
          # Set perf_event_paranoid to -1 to allow collection by any user.
          sudo sh -c 'echo -1 > /proc/sys/kernel/perf_event_paranoid'
          # Set kptr_restrict to 0 to allow kernel symbol resolution.
          sudo sh -c 'echo 0 > /proc/sys/kernel/kptr_restrict'
          echo "Permissions configured."
          
      - name: Run Profiling Harness
        run: |
          echo "--- Starting Profiling Harness ---"
          # Run the python script. It will now only run perf.
          python test/perf.py
          echo "--- Profiling Harness Finished ---"
          
      - name: Grant Cache Permissions
        # This step MUST run, even if the previous step failed, to allow the cache to be saved.
        if: always()
        run: |
          echo "Fixing permissions on APT cache directories for saving..."
          sudo chown -R runner:runner /var/cache/apt/archives /var/lib/apt/lists
          
      - name: Upload Profiling Data
        if: always() # Upload even if the run fails
        uses: actions/upload-artifact@v4
        with:
          name: perf-data-${{ github.run_id }}
          path: perf.data
          if-no-files-found: ignore
