/-
Copyright (c) 2026 Sauers. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sauers
-/
import Lean

/-!
One answer to the question "did a person write this declaration".

WHY THIS MODULE EXISTS.  Three detectors under `proofs/validation/` each carried
their own private copy of this filter and no two agreed.  The disagreement was
not cosmetic: the INFLATION scan in Check.lean excluded projection functions and the constructor
family, the RFL scan in Check.lean excluded equation lemmas and used the broader
`Name.isInternalDetail`, and neither list was a superset of the other.  Two tools
therefore reported totals over different populations while looking equally
authoritative.  `proofs/validation/code/CROSSCHECK.md` §4 has the full table.

This module is that filter, once.  It deliberately imports only `Lean`: it must
never import `Calibrator`, because the detectors import both, and a filter that
depended on the corpus it audits could not be loaded before the corpus built.
-/

open Lean

namespace Shared

/-- Final name components Lean generates for an inductive type or structure and
that no author types.  One line per entry, giving the reason it is not
hand-written, because a filter nobody can audit is how the three copies drifted
apart in the first place.

* `mk`               — the constructor, synthesised with the structure.
* `injEq`            — constructor injectivity, `S.mk a = S.mk b ↔ a = b`.
* `eta`              — the eta rule for the structure.
* `sizeOf`           — the `SizeOf` measure used for termination.
* `sizeOf_spec`      — its defining equation.
* `mk.sizeOf_spec`   — the same, stated at the constructor.
* `noConfusion`      — distinct constructors are unequal, distinct fields differ.
* `noConfusionType`  — the motive `noConfusion` eliminates into.
* `rec`              — the primitive recursor Lean derives from the type.
* `ndrec`            — its non-dependent form.
* `recOn`            — the recursor with the major premise moved first.
* `casesOn`          — the recursor restricted to case analysis.
* `brecOn`           — the course-of-values recursor built for structural recursion.
* `below`            — the motive `brecOn` recurses over.
* `toCtorIdx`        — the constructor index, generated for enumerations.
* `ofNat`            — the `OfNat` instance field, generated for numeric literals.
* `ext`              — extensionality, generated by the `@[ext]` machinery.
* `ext_iff`          — its iff form, generated alongside.

`ndrec` and `noConfusion` are in this list because the RFL scan in Check.lean was the one
copy that omitted them and would report `Foo.ndrec` as hand-written. -/
def generatedComponents : List String :=
  ["mk", "injEq", "eta", "sizeOf", "sizeOf_spec", "mk.sizeOf_spec",
   "noConfusion", "noConfusionType", "rec", "ndrec", "recOn", "casesOn",
   "brecOn", "below", "toCtorIdx", "ofNat", "ext", "ext_iff"]

/-- Is this final name component an equation lemma that Lean generated for a
definition?  Lean emits `f.eq_1`, `f.eq_2`, … for the branches of a definition,
plus `f.eq_def` and `f.eq_unfold` for its unfolding rule.  They are `rfl` by
construction and answer a different question than "which hand-written theorems
close by `rfl`".

NOT a blanket `startsWith "eq_"`, which is what the two copies that filtered
equation lemmas at all actually tested.  That test also swallows hand-written
theorems whose name begins `eq_of_`, `eq_zero_of_`, and this corpus has four of
them:

  Calibrator.Probability.eq_of_ae_eq_of_continuous
  Calibrator…Realizability.eq_zero_of_bounded_by_linear
  Calibrator…Coverage.eq_empty_of_core_empty
  Calibrator…Operator.eq_zero_of_tauOdd_of_tauEven

Under the blanket test the AXIOMS scan in Check.lean silently skipped the axiom closure of all
four, which is the opposite of what an axiom guard is for.  The digits-or-`def`-
or-`unfold` test below catches every generated equation lemma and none of these. -/
def isEquationLemma (component : String) : Bool :=
  component == "eq_def" || component == "eq_unfold" ||
  (component.startsWith "eq_" &&
    (let rest := component.drop 3
     !rest.isEmpty && rest.all Char.isDigit))

/-- Was this declaration generated by Lean rather than written by a person?

The union of the three exclusion sets the detectors used to maintain separately.
Each clause, and why the declaration is not hand-written:

1. `Name.isInternalDetail` — macro scopes, `_private.…`, and Lean's own internal
   naming.  The broader of the two internal tests the copies used; `Name.isInternal`
   misses cases this catches, so the union takes this one.
2. `Environment.isProjectionFn` — a structure field accessor.  Its value *is* the
   projection, necessarily; that is what a projection is.  Counting
   `R2DecompositionData.hVarYhat_pos` as an author asserting a hypothesis is a
   category error, and before this clause existed it produced 332 false hits.
3. `proof_` prefix — proof obligations Lean lifts out of a definition, `f.proof_1`.
4. `match_` prefix — match auxiliaries Lean lifts out of a definition, `f.match_1`.
5. `isEquationLemma` — see above.
6. `generatedComponents` — see above.
7. Any name that is not `.str`, i.e. anonymous or numeric.  Nothing an author
   typed has such a name, and `Name.getString!` panics on them. -/
def isGenerated (env : Environment) (n : Name) : Bool :=
  n.isInternalDetail
  || env.isProjectionFn n
  || (match n with
      | .str _ f =>
          f.startsWith "proof_" || f.startsWith "match_"
          || isEquationLemma f
          || generatedComponents.contains f
      | _ => true)

/-- Was this declaration written by a person?  The negation of `isGenerated`;
both spellings exist because the detectors read more clearly with one or the
other, and a second private definition of either is the defect this module
was created to remove. -/
def userWritten (env : Environment) (n : Name) : Bool :=
  !isGenerated env n

end Shared
